import {test,expect} from '@playwright/test';
import {mkdir} from 'node:fs/promises';
const modes=['recolte','dizaines','mosaique'];
async function ready(page){await page.waitForFunction(()=>window.__pocketDebug?.scene&&window.__pocketDebug.ready);}
async function hintStep(page){await ready(page);await page.locator('#pocket-hint').click();await page.waitForFunction(()=>window.__pocketDebug.hint?.action!==undefined);await page.keyboard.press('Enter');}
async function pointerAction(page,mode,action,touch=false){
  const points=await page.evaluate(({mode,action})=>{const d=window.__pocketDebug;return mode==='recolte'?action.path.map(id=>d.scene.screenPoint(id)):mode==='dizaines'?[d.scene.screenPoint(action.a),d.scene.screenPoint(action.b)]:[d.scene.screenPoint({piece:action.id}),d.scene.screenPoint(action.y*d.game.level.size+action.x)];},{mode,action});
  const session=touch?await page.context().newCDPSession(page):null;
  if(mode==='dizaines'){for(const p of points)if(session){await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[p]});await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}else await page.mouse.click(p.x,p.y);}
  else if(session){await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[points[0]]});for(const p of points.slice(1))await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[p]});await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}
  else{await page.mouse.move(points[0].x,points[0].y);await page.mouse.down();for(const p of points.slice(1))await page.mouse.move(p.x,p.y,{steps:8});await page.mouse.up();}await session?.detach();
}
for(const mode of modes){
  test(`${mode}: real pointer play, exact save and undo, complete hints and next puzzle`,async({page})=>{
    const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`/${mode}.html`);await ready(page);const initial=await page.evaluate(()=>window.__pocketDebug.game.state),action=await page.evaluate(()=>window.__pocketDebug.game.level.solution[0]);await pointerAction(page,mode,action);await expect.poll(()=>page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(1);await ready(page);const moved=await page.evaluate(()=>window.__pocketDebug.game.state);await page.reload();await ready(page);expect(await page.evaluate(()=>window.__pocketDebug.game.state)).toEqual(moved);await page.locator('#pocket-undo').click();expect(await page.evaluate(()=>window.__pocketDebug.game.state)).toEqual(initial);
    let guard=0;while(!await page.evaluate(()=>window.__pocketDebug.game.won)&&guard++<80)await hintStep(page);await expect(page.locator('#pocket-finish')).toBeVisible();await expect(page.locator('#pocket-total')).toHaveText('1 / 48');await page.locator('#pocket-next').click();await expect(page.locator('#pocket-number')).toContainText('02 / 48');await page.reload();await ready(page);await expect(page.locator('#pocket-total')).toHaveText('1 / 48');expect(errors).toEqual([]);
  });
  test(`${mode}: expert chapters, verified hints, desktop and mobile layouts`,async({page})=>{
    await mkdir('.local/screenshots',{recursive:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));for(const width of [1440,390,320]){await page.setViewportSize({width,height:width===1440?1000:844});await page.goto(`/${mode}.html`);await ready(page);await page.locator('#pocket-collection').click();await expect(page.locator('#pocket-levels button')).toHaveCount(12);await page.locator('[data-chapter="3"]').click();await page.locator('[data-level="47"]').click();await ready(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.locator('#pocket-hint').click();await page.waitForFunction(()=>window.__pocketDebug.hint?.action!==undefined);await page.screenshot({path:`.local/screenshots/${mode}-${width}.png`,fullPage:true});await page.keyboard.press('Enter');await ready(page);await expect.poll(()=>page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(1);await page.locator('#pocket-help').click();await expect(page.locator('#pocket-help-dialog')).toBeVisible();await page.getByRole('button',{name:'Fermer les règles',exact:true}).click();await page.locator('#pocket-restart').click();}expect(errors).toEqual([]);
  });
  test(`${mode}: native touch gestures on mobile and exact undo`,async({browser})=>{
    const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true}),page=await context.newPage();await page.goto(`/${mode}.html`);await ready(page);await page.locator('#pocket-stage').scrollIntoViewIfNeeded();const action=await page.evaluate(()=>window.__pocketDebug.game.level.solution[0]);await pointerAction(page,mode,action,true);await expect.poll(()=>page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(1);await ready(page);await page.locator('#pocket-undo').click();expect(await page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(0);await context.close();
  });
}
test('recolte: sidebar tracing and keyboard commit, shortened drag and invalid short chains',async({page})=>{
  await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/recolte.html');await ready(page);const action=await page.evaluate(()=>window.__pocketDebug.game.level.solution[0]);for(const id of action.path)await page.locator(`[data-chain="${id}"]`).click();await page.keyboard.press('Enter');expect(await page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(1);expect(await page.evaluate(()=>window.__pocketDebug.game.moves[0])).toEqual(action);await page.locator('#pocket-undo').click();
  await pointerAction(page,'recolte',{path:[action.path[0],action.path[1],action.path[0]]});expect(await page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(0);await expect(page.locator('#pocket-status')).toContainText('trois');
});
test('dizaines: selecting the same tile cancels, blocked pairs reject without changing the board',async({page})=>{
  await page.goto('/dizaines.html');await ready(page);const initial=await page.evaluate(()=>window.__pocketDebug.game.state),a=await page.evaluate(()=>window.__pocketDebug.game.level.solution[0].a);await page.locator(`[data-number="${a}"]`).click();expect(await page.evaluate(()=>window.__pocketDebug.selected)).toBe(a);await page.locator(`[data-number="${a}"]`).click();expect(await page.evaluate(()=>window.__pocketDebug.selected)).toBe(null);
  const bad=await page.evaluate(async()=>{const {matchingNumbers}=await import('/src/dizaines-puzzle.js'),g=window.__pocketDebug.game;for(let a=0;a<g.state.field.length;a++)for(let b=a+1;b<g.state.field.length;b++)if(g.state.field[a]!==null&&g.state.field[b]!==null&&!matchingNumbers(g.level,g.state,a,b))return {a,b};});await pointerAction(page,'dizaines',bad);expect(await page.evaluate(()=>window.__pocketDebug.game.state)).toEqual(initial);expect(await page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(0);
});
test('mosaique: keyboard placement, finite trios and final expert completion return to the collection',async({page})=>{
  await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/mosaique.html');await ready(page);const action=await page.evaluate(()=>window.__pocketDebug.game.level.solution[0]);await page.keyboard.press('1');for(let x=0;x<action.x;x++)await page.keyboard.press('ArrowRight');for(let y=0;y<action.y;y++)await page.keyboard.press('ArrowDown');await page.keyboard.press(' ');expect(await page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(1);expect(await page.evaluate(()=>window.__pocketDebug.scene.motion)).toBe(null);await page.locator('#pocket-collection').click();await page.locator('[data-chapter="3"]').click();await page.locator('[data-level="47"]').click();let guard=0;while(!await page.evaluate(()=>window.__pocketDebug.game.won)&&guard++<40)await hintStep(page);await expect(page.locator('#pocket-finish')).toBeVisible();await page.locator('#pocket-next').click();await expect(page.locator('#pocket-collection-dialog')).toBeVisible();await expect(page.locator('#pocket-levels button')).toHaveCount(12);
});
test('twenty-one illustrated home cards link to the three new collections',async({page})=>{
  await mkdir('.local/screenshots',{recursive:true});for(const width of [1440,390,320]){await page.setViewportSize({width,height:1000});await page.goto('/');await expect(page.locator('.game-card')).toHaveCount(21);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);if(width!==320)await page.screenshot({path:`.local/screenshots/twenty-one-games-${width}.png`,fullPage:true});}
  for(const [mode,name] of [['recolte','Récolte'],['dizaines','Dizaines'],['mosaique','Mosaïque']]){await page.getByRole('link',{name:`Jouer à ${name}`,exact:true}).click();await ready(page);await expect(page).toHaveURL(new RegExp(`/${mode}\\.html$`));await page.getByRole('link',{name:'Les jeux',exact:true}).click();await expect(page.locator('.game-card')).toHaveCount(21);}
});
test('mosaique: arrows adjust a hinted preview and Space places the visible origin',async({page})=>{
  await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/mosaique.html');await ready(page);await page.locator('#pocket-hint').click();await page.waitForFunction(()=>window.__pocketDebug.hint?.action);const action=await page.evaluate(()=>window.__pocketDebug.hint.action);await page.keyboard.press('ArrowLeft');expect(await page.evaluate(()=>window.__pocketDebug.hint)).toBe(null);expect(await page.evaluate(()=>window.__pocketDebug.scene.cursor)).toEqual({x:Math.max(0,action.x-1),y:action.y});await page.locator('#pocket-restart').click();await page.locator('#pocket-hint').click();await page.waitForFunction(()=>window.__pocketDebug.hint?.action);await page.keyboard.press(' ');expect(await page.evaluate(()=>window.__pocketDebug.game.moves[0])).toEqual(action);
});
