import {test,expect} from '@playwright/test';
import {mkdir} from 'node:fs/promises';
const modes=['etageres','duos','terriers'];
async function ready(page){await page.waitForFunction(()=>window.__pocketDebug?.scene&&window.__pocketDebug.ready);}
async function hintStep(page){await ready(page);await page.locator('#pocket-hint').click();await page.waitForFunction(()=>window.__pocketDebug.hint?.action!==undefined);await page.keyboard.press('Enter');}
async function pointerAction(page,mode,action,touch=false){
  await page.locator('#pocket-stage').scrollIntoViewIfNeeded();const points=await page.evaluate(({mode,action})=>{const d=window.__pocketDebug;return mode==='etageres'?[d.scene.screenPoint({shelf:action.from,cell:action.slot}),d.scene.screenPoint({shelf:action.to,cell:action.cell})]:mode==='duos'?[d.scene.screenPoint(action.a),d.scene.screenPoint(action.b)]:action.path.map(p=>d.scene.screenPoint(p));},{mode,action});
  const session=touch?await page.context().newCDPSession(page):null;
  if(mode==='duos'){for(const p of points)if(session){await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[p]});await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}else await page.mouse.click(p.x,p.y);}
  else if(session){await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[points[0]]});for(const p of points.slice(1))await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[p]});await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}
  else{await page.mouse.move(points[0].x,points[0].y);await page.mouse.down();for(const p of points.slice(1))await page.mouse.move(p.x,p.y,{steps:10});await page.mouse.up();}await session?.detach();
}
for(const mode of modes){
  test(`${mode}: actual pointer move, save/reload, exact undo, complete first puzzle and next`,async({page})=>{
    const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`/${mode}.html`);await ready(page);const initial=await page.evaluate(()=>window.__pocketDebug.game.state),action=await page.evaluate(()=>window.__pocketDebug.game.level.solution[0]);await pointerAction(page,mode,action);await expect.poll(()=>page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(1);await ready(page);const moved=await page.evaluate(()=>window.__pocketDebug.game.state);await page.reload();await ready(page);expect(await page.evaluate(()=>window.__pocketDebug.game.state)).toEqual(moved);await page.locator('#pocket-undo').click();expect(await page.evaluate(()=>window.__pocketDebug.game.state)).toEqual(initial);
    let guard=0;while(!await page.evaluate(()=>window.__pocketDebug.game.won)&&guard++<80)await hintStep(page);await ready(page);await expect(page.locator('#pocket-finish')).toBeVisible();await expect(page.locator('#pocket-total')).toHaveText('1 / 48');await page.locator('#pocket-next').click();await expect(page.locator('#pocket-number')).toContainText('02 / 48');await page.reload();await ready(page);await expect(page.locator('#pocket-total')).toHaveText('1 / 48');expect(errors).toEqual([]);
  });
  test(`${mode}: expert 48, all chapter controls, desktop and narrow layouts`,async({page})=>{
    await mkdir('.local/screenshots',{recursive:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));for(const width of [1440,390,320]){await page.setViewportSize({width,height:width===1440?1000:844});await page.goto(`/${mode}.html`);await ready(page);await page.locator('#pocket-collection').click();await expect(page.locator('#pocket-levels button')).toHaveCount(12);await page.locator('[data-chapter="3"]').click();await page.locator('[data-level="47"]').click();await ready(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.locator('#pocket-hint').click();await page.waitForFunction(()=>window.__pocketDebug.hint?.action!==undefined);await page.screenshot({path:`.local/screenshots/${mode}-${width}.png`,fullPage:true});await page.keyboard.press('Enter');await ready(page);expect(await page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(1);await page.locator('#pocket-help').click();await expect(page.locator('#pocket-help-dialog')).toBeVisible();await page.getByRole('button',{name:'Fermer les règles',exact:true}).click();await page.locator('#pocket-restart').click();}expect(errors).toEqual([]);
  });
  test(`${mode}: native mobile touch and undo`,async({browser})=>{
    const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true}),page=await context.newPage();await page.goto(`/${mode}.html`);await ready(page);const action=await page.evaluate(()=>window.__pocketDebug.game.level.solution[0]);await pointerAction(page,mode,action,true);await expect.poll(()=>page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(1);await ready(page);await page.locator('#pocket-undo').click();expect(await page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(0);await context.close();
  });
}
test('@core etageres and duos: sidebar choices cancel and invalid destinations preserve the board',async({page})=>{
  await page.emulateMedia({reducedMotion:'reduce'});for(const mode of ['etageres','duos']){await page.goto(`/${mode}.html`);await ready(page);const a=await page.evaluate(()=>window.__pocketDebug.game.level.solution[0]),id=mode==='duos'?a.a:a.from*3+a.slot,selector=mode==='duos'?'duo':'goods';
    const initial=await page.evaluate(()=>window.__pocketDebug.game.state),bad=await page.evaluate(({mode,a})=>{const g=window.__pocketDebug.game;return mode==='duos'?{a:a.a,b:g.state.field.findIndex(v=>v!==null&&v>=0&&v!==g.state.field[a.a])}:{...a,to:a.from,cell:(a.slot+1)%3};},{mode,a});await pointerAction(page,mode,bad);expect(await page.evaluate(()=>window.__pocketDebug.game.state)).toEqual(initial);await page.locator('#pocket-restart').click();await page.locator(`[data-${selector}="${id}"]`).click();await page.locator(`[data-${selector}="${id}"]`).click();expect(await page.evaluate(()=>window.__pocketDebug.selected)).toBe(null);await page.locator(`[data-${selector}="${id}"]`).click();const target=mode==='duos'?a.b:a.to*3+a.cell;await page.locator(`[data-${selector}="${target}"]`).click();expect(await page.evaluate(()=>window.__pocketDebug.game.moves[0])).toEqual(a);}
});
test('@core terriers: coordinate input, live trial lock, dialog pause and undo during descent',async({page})=>{
  await page.goto('/terriers.html');await ready(page);const action=await page.evaluate(()=>window.__pocketDebug.game.level.solution[0]);await page.locator('.cabinet-points summary').click();for(const [x,y] of action.path){await page.locator('#soil-x').fill(String(x));await page.locator('#soil-y').fill(String(y));await page.locator('[data-soil-point]').click();}await page.locator('[data-soil-place]').click();expect(await page.evaluate(()=>window.__pocketDebug.game.moves[0])).toEqual(action);const dug=await page.evaluate(()=>window.__pocketDebug.game.state);await page.keyboard.press('e');await page.waitForFunction(()=>window.__pocketDebug.scene.running);await expect(page.locator('[data-soil-run]')).toBeDisabled();await page.locator('#pocket-help').click();const ticks=await page.evaluate(()=>window.__pocketDebug.scene.flow.ticks);await page.waitForTimeout(180);expect(await page.evaluate(()=>window.__pocketDebug.scene.flow.ticks)).toBe(ticks);await page.getByRole('button',{name:'Fermer les règles',exact:true}).click();await page.locator('#pocket-undo').click();expect(await page.evaluate(()=>window.__pocketDebug.scene.running)).toBe(false);expect(await page.evaluate(()=>window.__pocketDebug.game.state)).toEqual(dug);await page.keyboard.press('e');await ready(page);expect(await page.evaluate(()=>window.__pocketDebug.game.won)).toBe(true);
});
test('@core terriers: failed empty trial persists, cancelled stroke does not excavate and reduced motion is immediate',async({page})=>{
  await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/terriers.html');await ready(page);await page.keyboard.press('e');await ready(page);expect(await page.evaluate(()=>window.__pocketDebug.game.won)).toBe(false);expect(await page.evaluate(()=>window.__pocketDebug.scene.running)).toBe(false);await page.reload();await ready(page);expect(await page.evaluate(()=>window.__pocketDebug.game.state.result.caught)).toBe(0);await page.locator('#pocket-undo').click();await page.locator('#pocket-stage').scrollIntoViewIfNeeded();const p=await page.evaluate(()=>window.__pocketDebug.scene.screenPoint([320,180]));await page.mouse.move(p.x,p.y);await page.mouse.down();await page.dispatchEvent('#pocket-canvas','pointercancel',{pointerId:1});await page.mouse.up();expect(await page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(0);while(!await page.evaluate(()=>window.__pocketDebug.game.won))await hintStep(page);expect(await page.evaluate(()=>window.__pocketDebug.scene.running)).toBe(false);
});
test('twenty-four home illustrations open the three new games and return home',async({page})=>{
  await mkdir('.local/screenshots',{recursive:true});await page.goto('/');await expect(page.locator('.game-card')).toHaveCount(33);await page.screenshot({path:'.local/screenshots/twenty-four-games.png',fullPage:true});for(const [mode,name] of [['etageres','Étagères'],['duos','Duos'],['terriers','Terriers']]){await page.getByRole('link',{name:`Jouer à ${name}`,exact:true}).click();await ready(page);await expect(page).toHaveURL(new RegExp(`/${mode}\\.html$`));await page.getByRole('link',{name:'Les jeux',exact:true}).click();await expect(page.locator('.game-card')).toHaveCount(33);}
});
test('all three final puzzles complete via visible verified hints and return to collection',async({page})=>{
  await page.emulateMedia({reducedMotion:'reduce'});for(const mode of modes){await page.goto(`/${mode}.html`);await ready(page);await page.locator('#pocket-collection').click();await page.locator('[data-chapter="3"]').click();await page.locator('[data-level="47"]').click();let guard=0;while(!await page.evaluate(()=>window.__pocketDebug.game.won)&&guard++<90)await hintStep(page);await expect(page.locator('#pocket-finish')).toBeVisible();await page.locator('#pocket-next').click();await expect(page.locator('#pocket-collection-dialog')).toBeVisible();}
});
