import {test,expect} from '@playwright/test';
import {mkdir} from 'node:fs/promises';
const modes=['ecluses','dunes','fringale'];
async function ready(page){await page.waitForFunction(()=>window.__pocketDebug?.scene&&window.__pocketDebug.ready);}
async function hintStep(page){await ready(page);await page.locator('#pocket-hint').click();await page.waitForFunction(()=>window.__pocketDebug.hint?.action!==undefined);await page.keyboard.press('Enter');}
async function pointerAction(page,mode,action,touch=false){
  const points=await page.evaluate(({mode,action})=>{const d=window.__pocketDebug;return mode==='ecluses'?[d.scene.screenPoint(action)]:mode==='dunes'?[d.scene.screenPoint({q:action.q}),d.scene.screenPoint(action)]:[d.scene.screenPoint(d.game.state.hole),d.scene.screenPoint(action.id)];},{mode,action});
  const session=touch?await page.context().newCDPSession(page):null;
  const tap=async p=>{if(session){await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[p]});await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}else await page.mouse.click(p.x,p.y);};
  if(mode!=='fringale')for(const p of points)await tap(p);
  else if(session){await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[points[0]]});for(let n=1;n<=12;n++)await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:points[0].x+(points[1].x-points[0].x)*n/12,y:points[0].y+(points[1].y-points[0].y)*n/12}]});await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}
  else{await page.mouse.move(points[0].x,points[0].y);await page.mouse.down();await page.mouse.move(points[1].x,points[1].y,{steps:12});await page.mouse.up();}
  await session?.detach();
}
for(const mode of modes){
  test(`${mode}: real pointer play, exact reload and undo, complete hints and next puzzle`,async({page})=>{
    const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`/${mode}.html`);await ready(page);const initial=await page.evaluate(()=>window.__pocketDebug.game.state),action=await page.evaluate(()=>window.__pocketDebug.game.level.solution[0]);
    await pointerAction(page,mode,action);await expect.poll(()=>page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(1);await ready(page);const moved=await page.evaluate(()=>window.__pocketDebug.game.state);if(mode==='fringale')expect(moved.collected.length).toBeGreaterThan(0);
    await page.reload();await ready(page);expect(await page.evaluate(()=>window.__pocketDebug.game.state)).toEqual(moved);await page.locator('#pocket-undo').click();expect(await page.evaluate(()=>window.__pocketDebug.game.state)).toEqual(initial);
    let guard=0;while(!await page.evaluate(()=>window.__pocketDebug.game.won)&&guard++<80)await hintStep(page);await expect(page.locator('#pocket-finish')).toBeVisible({timeout:10000});await expect(page.locator('#pocket-total')).toHaveText('1 / 48');await page.locator('#pocket-next').click();await expect(page.locator('#pocket-number')).toContainText('02 / 48');await page.reload();await ready(page);await expect(page.locator('#pocket-total')).toHaveText('1 / 48');expect(errors).toEqual([]);
  });
  test(`${mode}: expert chapters, verified hints and desktop/mobile layouts`,async({page})=>{
    await mkdir('.local/screenshots',{recursive:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));
    for(const width of [1440,390,320]){await page.setViewportSize({width,height:width===1440?1000:844});await page.goto(`/${mode}.html`);await ready(page);await page.locator('#pocket-collection').click();await expect(page.locator('#pocket-levels button')).toHaveCount(12);await page.locator('[data-chapter="3"]').click();await page.locator('[data-level="47"]').click();await ready(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.locator('#pocket-hint').click();await page.waitForFunction(()=>window.__pocketDebug.hint?.action!==undefined);await page.screenshot({path:`.local/screenshots/${mode}-${width}.png`,fullPage:true});await page.keyboard.press('Enter');await ready(page);await expect.poll(()=>page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(1);await page.locator('#pocket-help').click();await expect(page.locator('#pocket-help-dialog')).toBeVisible();await page.getByRole('button',{name:'Fermer les règles',exact:true}).click();await page.locator('#pocket-restart').click();}expect(errors).toEqual([]);
  });
  test(`${mode}: native touch play and undo on mobile`,async({browser})=>{
    const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true}),page=await context.newPage();await page.goto(`/${mode}.html`);await ready(page);await page.locator('#pocket-stage').scrollIntoViewIfNeeded();const action=await page.evaluate(()=>window.__pocketDebug.game.level.solution[0]);await pointerAction(page,mode,action,true);await expect.poll(()=>page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(1);await ready(page);if(mode==='fringale')expect(await page.evaluate(()=>window.__pocketDebug.game.state.collected.length)).toBeGreaterThan(0);await page.locator('#pocket-undo').click();expect(await page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(0);await context.close();
  });
}
test('ecluses: a wrong outlet loses grey balls and undo recovers the entire board',async({page})=>{
  await page.goto('/ecluses.html');await ready(page);const initial=await page.evaluate(()=>window.__pocketDebug.game.state),pins=await page.evaluate(()=>window.__pocketDebug.game.level.solution);await page.locator(`[data-gate="${pins[0]}"]`).click();await ready(page);await page.locator(`[data-gate="${pins[2]}"]`).click();await ready(page);await expect(page.locator('#pocket-status')).toContainText('perdues');await expect(page.locator('#pocket-finish')).not.toBeVisible();await page.locator('#pocket-undo').click();await page.locator('#pocket-undo').click();expect(await page.evaluate(()=>window.__pocketDebug.game.state)).toEqual(initial);
});
test('dunes: animated grains lock extra drops, undo cancels gravity, keyboard works with reduced motion',async({page})=>{
  await page.goto('/dunes.html');await ready(page);const initial=await page.evaluate(()=>window.__pocketDebug.game.state);await hintStep(page);await page.waitForFunction(()=>window.__pocketDebug.scene.running);await page.keyboard.press(' ');expect(await page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(1);await page.locator('#pocket-undo').click();expect(await page.evaluate(()=>window.__pocketDebug.scene.running)).toBe(false);expect(await page.evaluate(()=>window.__pocketDebug.game.state)).toEqual(initial);
  await page.emulateMedia({reducedMotion:'reduce'});await page.reload();await ready(page);const action=await page.evaluate(()=>window.__pocketDebug.game.level.solution[0]);await page.locator('#pocket-hint').click();await page.waitForFunction(()=>window.__pocketDebug.hint?.action);await page.keyboard.press(' ');expect(await page.evaluate(()=>window.__pocketDebug.game.moves[0])).toEqual(action);await page.locator('#pocket-undo').click();await page.keyboard.press(String(action.q+1));await page.keyboard.press('ArrowLeft');await page.keyboard.press(' ');expect(await page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(1);expect(await page.evaluate(()=>window.__pocketDebug.scene.running)).toBe(false);
});
test('fringale: keyboard motion, inaccessible large objects, growth and exact undo',async({page})=>{
  await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/fringale.html');await ready(page);const initial=await page.evaluate(()=>window.__pocketDebug.game.state);await expect(page.locator('[data-food]:disabled').first()).toBeVisible();await page.keyboard.press('ArrowLeft');expect(await page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(1);await page.locator('#pocket-undo').click();expect(await page.evaluate(()=>window.__pocketDebug.game.state)).toEqual(initial);await hintStep(page);expect(await page.evaluate(()=>window.__pocketDebug.game.state.mass)).toBeGreaterThan(0);await page.locator('#pocket-undo').click();expect(await page.evaluate(()=>window.__pocketDebug.game.state)).toEqual(initial);
});
test('twenty-one illustrated home games link to the three new collections',async({page})=>{
  await mkdir('.local/screenshots',{recursive:true});await page.goto('/');await expect(page.locator('.game-card')).toHaveCount(21);await page.screenshot({path:'.local/screenshots/eighteen-games.png',fullPage:true});
  for(const [mode,name] of [['ecluses','Écluses'],['dunes','Dunes'],['fringale','Fringale']]){await page.getByRole('link',{name:`Jouer à ${name}`,exact:true}).click();await ready(page);await expect(page).toHaveURL(new RegExp(`/${mode}\\.html$`));await page.getByRole('link',{name:'Les jeux',exact:true}).click();await expect(page.locator('.game-card')).toHaveCount(21);}
});
