import {test,expect} from '@playwright/test';
import {mkdir} from 'node:fs/promises';
const modes=['plis','lucioles','aiguillages'];
async function ready(page){await page.waitForFunction(()=>window.__pocketDebug?.scene&&window.__pocketDebug.ready);}
async function hintStep(page){await ready(page);await page.locator('#pocket-hint').click();await page.waitForFunction(()=>window.__pocketDebug.hint?.action!==undefined);await page.keyboard.press('Enter');}
async function pointer(page,mode,a,touch=false){await page.locator('#pocket-stage').scrollIntoViewIfNeeded();const points=await page.evaluate(({mode,a})=>{const d=window.__pocketDebug;return mode==='plis'?d.scene.foldScreenPoints(a):[d.scene.screenPoint(mode==='lucioles'?a.id:d.game.level.switches[a.id].cell)];},{mode,a});
  if(touch){const session=await page.context().newCDPSession(page);await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[points[0]]});for(const p of points.slice(1))await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[p]});await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await session.detach();}
  else if(points.length===1)await page.mouse.click(points[0].x,points[0].y);else{await page.mouse.move(points[0].x,points[0].y);await page.mouse.down();await page.mouse.move(points[1].x,points[1].y,{steps:12});await page.mouse.up();}}
for(const mode of modes){
  test(`${mode}: real pointer play, exact reload and undo, complete first puzzle and next`,async({page})=>{
    const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`/${mode}.html`);await ready(page);const initial=await page.evaluate(()=>window.__pocketDebug.game.state),a=await page.evaluate(()=>window.__pocketDebug.game.level.solution[0]);await pointer(page,mode,a);await expect.poll(()=>page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(1);await ready(page);const moved=await page.evaluate(()=>window.__pocketDebug.game.state);await page.reload();await ready(page);expect(await page.evaluate(()=>window.__pocketDebug.game.state)).toEqual(moved);await page.locator('#pocket-undo').click();expect(await page.evaluate(()=>window.__pocketDebug.game.state)).toEqual(initial);let guard=0;while(!await page.evaluate(()=>window.__pocketDebug.game.won)&&guard++<60)await hintStep(page);await ready(page);await expect(page.locator('#pocket-finish')).toBeVisible();await expect(page.locator('#pocket-total')).toHaveText('1 / 48');await page.locator('#pocket-next').click();await expect(page.locator('#pocket-number')).toContainText('02 / 48');expect(errors).toEqual([]);
  });
  test(`${mode}: expert 48, four chapters and layouts at 1440, 390 and 320 pixels`,async({page})=>{
    await mkdir('.local/screenshots',{recursive:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));for(const width of [1440,390,320]){await page.setViewportSize({width,height:width===1440?1000:844});await page.goto(`/${mode}.html`);await ready(page);await page.locator('#pocket-collection').click();await expect(page.locator('#pocket-chapters button')).toHaveCount(4);await page.locator('[data-chapter="3"]').click();await expect(page.locator('#pocket-levels button')).toHaveCount(12);await page.locator('[data-level="47"]').click();await ready(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.locator('#pocket-hint').click();await page.waitForFunction(()=>window.__pocketDebug.hint?.action!==undefined);await page.screenshot({path:`.local/screenshots/${mode}-${width}.png`,fullPage:true});await page.keyboard.press('Enter');await ready(page);expect(await page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(1);await page.locator('#pocket-help').click();await expect(page.locator('#pocket-help-dialog')).toBeVisible();await page.getByRole('button',{name:'Fermer les règles',exact:true}).click();await page.locator('#pocket-restart').click();}expect(errors).toEqual([]);
  });
  test(`${mode}: native mobile touch and undo`,async({browser})=>{const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),page=await context.newPage();await page.goto(`/${mode}.html`);await ready(page);const a=await page.evaluate(()=>window.__pocketDebug.game.level.solution[0]);await pointer(page,mode,a,true);await expect.poll(()=>page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(1);await ready(page);await page.locator('#pocket-undo').click();expect(await page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(0);await context.close();});
}
test('@core plis: sidebar fold, cancelled gesture and immediate reduced motion preserve exact paper layers',async({page})=>{
  await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/plis.html');await ready(page);const a=await page.evaluate(()=>window.__pocketDebug.game.level.solution[0]),index=await page.evaluate(a=>window.__pocketDebug.game.rules.actions(window.__pocketDebug.game.level,window.__pocketDebug.game.state).findIndex(n=>JSON.stringify(n)===JSON.stringify(a)),a);await page.locator(`[data-fold="${index}"]`).click();expect(await page.evaluate(()=>window.__pocketDebug.scene.motion)).toBe(null);expect(await page.evaluate(()=>window.__pocketDebug.game.moves[0])).toEqual(a);await page.locator('#pocket-undo').click();await page.locator('#pocket-stage').scrollIntoViewIfNeeded();const points=await page.evaluate(a=>window.__pocketDebug.scene.foldScreenPoints(a),a);await page.mouse.move(points[0].x,points[0].y);await page.mouse.down();await page.dispatchEvent('#pocket-canvas','pointercancel',{pointerId:1});await page.mouse.up();expect(await page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(0);
});
test('@core lucioles: sidebar and keyboard turn the actual mirrors, fixed source clicks reject',async({page})=>{
  await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/lucioles.html');await ready(page);const a=await page.evaluate(()=>window.__pocketDebug.game.level.solution[0]);await page.locator(`[data-optic="${a.id}"]`).click();expect(await page.evaluate(()=>window.__pocketDebug.game.moves[0])).toEqual(a);await page.locator('#pocket-undo').click();const first=await page.evaluate(()=>window.__pocketDebug.game.rules.actions(window.__pocketDebug.game.level,window.__pocketDebug.game.state)[0]);await page.keyboard.press('1');expect(await page.evaluate(()=>window.__pocketDebug.game.moves[0])).toEqual(first);await page.locator('#pocket-restart').click();const source=await page.evaluate(()=>window.__pocketDebug.game.level.sources[0].cell);await pointer(page,'lucioles',{id:source});expect(await page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(0);
});
test('@core aiguillages: departure selects, live train lock, dialog pause and undo during travel',async({page})=>{
  await page.goto('/aiguillages.html');await ready(page);await page.locator('#pocket-collection').click();await page.locator('[data-chapter="3"]').click();await page.locator('[data-level="47"]').click();const a=await page.evaluate(()=>window.__pocketDebug.game.level.solution.find(a=>a.type==='delay'));await page.locator(`[data-rail-delay="${a.id}"]`).selectOption(String(a.value));expect(await page.evaluate(()=>window.__pocketDebug.game.moves[0])).toEqual(a);await page.locator(`[data-rail-delay="${a.id}"]`).focus();for(const key of ['r','h','e'])await page.keyboard.press(key);expect(await page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(1);expect(await page.evaluate(()=>window.__pocketDebug.hint)).toBe(null);expect(await page.evaluate(()=>window.__pocketDebug.scene.running)).toBe(false);await page.locator('#pocket-canvas').focus();await page.keyboard.press('e');await page.waitForFunction(()=>window.__pocketDebug.scene.running);await expect(page.locator('[data-rail-run]')).toBeDisabled();await expect(page.locator('[data-rail-delay="0"]')).toBeDisabled();await page.locator('#pocket-help').click();const tick=await page.evaluate(()=>window.__pocketDebug.scene.flow.tick);await page.waitForTimeout(160);expect(await page.evaluate(()=>window.__pocketDebug.scene.flow.tick)).toBe(tick);await page.getByRole('button',{name:'Fermer les règles',exact:true}).click();await page.locator('#pocket-undo').click();expect(await page.evaluate(()=>window.__pocketDebug.scene.running)).toBe(false);expect(await page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(1);expect(await page.evaluate(()=>window.__pocketDebug.game.state.result)).toBe(null);
});
test('all three final puzzles complete through verified hints and return to the collection',async({page})=>{
  await page.emulateMedia({reducedMotion:'reduce'});for(const mode of modes){await page.goto(`/${mode}.html`);await ready(page);await page.locator('#pocket-collection').click();await page.locator('[data-chapter="3"]').click();await page.locator('[data-level="47"]').click();let guard=0;while(!await page.evaluate(()=>window.__pocketDebug.game.won)&&guard++<60)await hintStep(page);await ready(page);await expect(page.locator('#pocket-finish')).toBeVisible();await page.locator('#pocket-next').click();await expect(page.locator('#pocket-collection-dialog')).toBeVisible();}
});
test('thirty illustrated home cards link to Plis, Lucioles and Aiguillages',async({page})=>{
  for(const width of [1440,390,320]){await page.setViewportSize({width,height:1000});await page.goto('/');await expect(page.locator('.game-card')).toHaveCount(36);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}for(const [mode,name] of [['plis','Plis'],['lucioles','Lucioles'],['aiguillages','Aiguillages']]){await page.getByRole('link',{name:`Jouer à ${name}`,exact:true}).click();await ready(page);await expect(page).toHaveURL(new RegExp(`/${mode}\\.html$`));await page.getByRole('link',{name:'Les jeux',exact:true}).click();await expect(page.locator('.game-card')).toHaveCount(36);}
});
