import {test,expect} from '@playwright/test';
import {mkdir} from 'node:fs/promises';

const modes=['bascules','sillons','raccords'];
async function ready(page){await page.waitForFunction(()=>window.__pocketDebug?.ready);}
async function hintStep(page){await ready(page);await page.locator('#pocket-hint').click();await page.waitForFunction(()=>window.__pocketDebug.hint?.action);await page.keyboard.press('Enter');}
async function pointer(page,mode,action,touch=false){
  await page.locator('#pocket-stage').scrollIntoViewIfNeeded();
  if(mode==='raccords'&&action.type==='turn')await page.locator(`[data-joint-pick="${action.id}"]`).click();
  const points=await page.evaluate(({mode,action})=>{const s=window.__pocketDebug.scene;return mode!=='raccords'?s.directionScreenPoints(action.dir):action.type==='shift'?[s.screenPoint({id:action.id}),s.screenPoint(action.to)]:[s.screenPoint({id:action.id})];},{mode,action});
  if(touch){const session=await page.context().newCDPSession(page);await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[points[0]]});for(const p of points.slice(1))await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[p]});await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await session.detach();}
  else if(points.length===1)await page.mouse.click(points[0].x,points[0].y);else{await page.mouse.move(points[0].x,points[0].y);await page.mouse.down();for(const p of points.slice(1))await page.mouse.move(p.x,p.y,{steps:12});await page.mouse.up();}
}
test.describe('meadow',()=>{
  for(const mode of modes){
    test(`${mode}: actual pointer move, exact save/reload/undo, first completion and next`,async({page})=>{
      const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`/${mode}.html`);await ready(page);const initial=await page.evaluate(()=>window.__pocketDebug.game.state),action=await page.evaluate(()=>window.__pocketDebug.game.level.solution[0]);await pointer(page,mode,action);await expect.poll(()=>page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(1);await ready(page);const moved=await page.evaluate(()=>window.__pocketDebug.game.state);await page.reload();await ready(page);expect(await page.evaluate(()=>window.__pocketDebug.game.state)).toEqual(moved);await page.locator('#pocket-undo').click();expect(await page.evaluate(()=>window.__pocketDebug.game.state)).toEqual(initial);let guard=0;while(!await page.evaluate(()=>window.__pocketDebug.game.won)&&guard++<180)await hintStep(page);await ready(page);await expect(page.locator('#pocket-finish')).toBeVisible();await page.locator('#pocket-next').click();await expect(page.locator('#pocket-number')).toContainText('02 / 48');expect(errors).toEqual([]);
    });
    test(`${mode}: expert chapters, keyboard hints and layouts at desktop, 390 and 320 pixels`,async({page})=>{
      await mkdir('.local/screenshots',{recursive:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));for(const width of [1440,390,320]){await page.setViewportSize({width,height:1000});await page.goto(`/${mode}.html`);await ready(page);await page.locator('#pocket-collection').click();await expect(page.locator('#pocket-chapters button')).toHaveCount(4);await page.locator('[data-chapter="3"]').click();await expect(page.locator('#pocket-levels button')).toHaveCount(12);await page.locator('[data-level="47"]').click();await ready(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.locator('#pocket-hint').click();await page.waitForFunction(()=>window.__pocketDebug.hint?.action);await page.screenshot({path:`.local/screenshots/${mode}-${width}.png`,fullPage:true});await page.keyboard.press('Enter');await ready(page);expect(await page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(1);await page.locator('#pocket-help').click();await expect(page.locator('#pocket-help-dialog')).toBeVisible();await page.getByRole('button',{name:'Fermer les règles',exact:true}).click();await page.locator('#pocket-restart').click();}expect(errors).toEqual([]);
    });
    test(`${mode}: native mobile touch performs one gesture and undo`,async({browser})=>{
      const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true}),page=await context.newPage();await page.goto(`/${mode}.html`);await ready(page);const action=await page.evaluate(()=>window.__pocketDebug.game.level.solution[0]);await pointer(page,mode,action,true);await expect.poll(()=>page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(1);await ready(page);await page.locator('#pocket-undo').click();expect(await page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(0);await context.close();
    });
  }
  test('@core bascules: actual rigid roll locks input, undo cancels animation, and native direction buttons work',async({page})=>{
    await page.goto('/bascules.html');await ready(page);const initial=await page.evaluate(()=>window.__pocketDebug.game.state),action=await page.evaluate(()=>window.__pocketDebug.game.level.solution[0]);await page.locator(`[data-meadow-dir="${action.dir}"]`).focus();await page.keyboard.press('Enter');await expect.poll(()=>page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(1);await page.waitForFunction(()=>window.__pocketDebug.scene.running);expect(await page.evaluate(()=>window.__pocketDebug.scene.motion.previous)).toEqual(initial);await page.locator('#pocket-undo').click();expect(await page.evaluate(()=>window.__pocketDebug.scene.motion)).toBeNull();expect(await page.evaluate(()=>window.__pocketDebug.game.state)).toEqual(initial);await page.waitForTimeout(400);await expect(page.locator('#pocket-finish')).not.toBeVisible();await page.locator('#pocket-canvas').focus();await page.keyboard.press(['ArrowUp','ArrowRight','ArrowDown','ArrowLeft'][action.dir]);expect(await page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(1);
  });
  test('sillons: an entire painted stroke restores exactly, cancelled touch does not draw',async({page})=>{
    await page.goto('/sillons.html');await ready(page);const initial=await page.evaluate(()=>window.__pocketDebug.game.state),action=await page.evaluate(()=>window.__pocketDebug.game.level.solution[0]);await pointer(page,'sillons',action);await ready(page);expect(await page.evaluate(()=>window.__pocketDebug.game.state.painted.filter(Boolean).length)).toBeGreaterThan(1);await page.locator('#pocket-undo').click();expect(await page.evaluate(()=>window.__pocketDebug.game.state)).toEqual(initial);const session=await page.context().newCDPSession(page),points=await page.evaluate(dir=>window.__pocketDebug.scene.directionScreenPoints(dir),action.dir);await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[points[0]]});await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[points[1]]});await session.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});await session.detach();expect(await page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(0);
  });
  test('raccords: native piece buttons select without moving; T rotates and cancelled drag preserves every place',async({page})=>{
    await page.goto('/raccords.html');await ready(page);const id=await page.evaluate(()=>window.__pocketDebug.game.level.pieces.find(p=>p.kind==='free').id),button=page.locator(`[data-joint-pick="${id}"]`);await button.focus();await page.keyboard.press(' ');await expect(button).toHaveAttribute('aria-pressed','true');expect(await page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(0);const initial=await page.evaluate(()=>window.__pocketDebug.game.state);await page.locator('#pocket-canvas').focus();await page.keyboard.press('t');await ready(page);expect(await page.evaluate(id=>window.__pocketDebug.game.state.turns[id],id)).toBe((initial.turns[id]+1)%4);await page.locator('#pocket-undo').click();const point=await page.evaluate(id=>window.__pocketDebug.scene.screenPoint({id}),id),session=await page.context().newCDPSession(page);await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[point]});await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:point.x+60,y:point.y+60}]});await session.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});await session.detach();expect(await page.evaluate(()=>window.__pocketDebug.game.state)).toEqual(initial);
  });
  test('three expert puzzles finish with reduced motion and return to their collections',async({page})=>{
    await page.emulateMedia({reducedMotion:'reduce'});for(const mode of modes){await page.goto(`/${mode}.html`);await ready(page);await page.locator('#pocket-collection').click();await page.locator('[data-chapter="3"]').click();await page.locator('[data-level="47"]').click();let guard=0;while(!await page.evaluate(()=>window.__pocketDebug.game.won)&&guard++<180)await hintStep(page);await ready(page);await expect(page.locator('#pocket-finish')).toBeVisible();await page.locator('#pocket-next').click();await expect(page.locator('#pocket-collection-dialog')).toBeVisible();}
  });
  test('thirty-nine home illustrations open each new game without overflow',async({page})=>{
    for(const width of [1440,390,320]){await page.setViewportSize({width,height:1000});await page.goto('/');await expect(page.locator('.game-card')).toHaveCount(39);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}for(const [mode,name]of [['bascules','Bascules'],['sillons','Sillons'],['raccords','Raccords']]){await page.getByRole('link',{name:`Jouer à ${name}`,exact:true}).click();await ready(page);await expect(page).toHaveURL(new RegExp(`/${mode}\\.html$`));await page.getByRole('link',{name:'Les jeux',exact:true}).click();}
  });
});
