import {test,expect} from '@playwright/test';
import {mkdir} from 'node:fs/promises';

const modes=['cagettes','cairns','jalons'];
async function ready(page){await page.waitForFunction(()=>window.__pocketDebug?.ready);}
async function hintStep(page){await ready(page);await page.locator('#pocket-hint').click();await page.waitForFunction(()=>window.__pocketDebug.hint?.action);await page.keyboard.press('Enter');}
async function pointsFor(page,mode,action){return page.evaluate(({mode,action})=>{const s=window.__pocketDebug.scene;return mode==='cagettes'?s.directionScreenPoints(action.dir):mode==='cairns'?[s.screenPoint(action.from),s.screenPoint(action.to)]:action.path.map(id=>s.screenPoint(id));},{mode,action});}
async function pointer(page,mode,action,touch=false){
  await page.locator('#pocket-stage').scrollIntoViewIfNeeded();const points=await pointsFor(page,mode,action);
  if(touch){const session=await page.context().newCDPSession(page);await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[points[0]]});for(const point of points.slice(1))await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[point]});await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await session.detach();}
  else{await page.mouse.move(points[0].x,points[0].y);await page.mouse.down();for(const point of points.slice(1))await page.mouse.move(point.x,point.y,{steps:10});await page.mouse.up();}
}
test.describe('orchard',()=>{
  for(const mode of modes){
    test(`${mode}: actual gesture, exact save/reload/undo, first finish and next`,async({page})=>{
      const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`/${mode}.html`);await ready(page);const initial=await page.evaluate(()=>window.__pocketDebug.game.state),action=await page.evaluate(()=>window.__pocketDebug.game.level.solution[0]);await pointer(page,mode,action);await expect.poll(()=>page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(1);await ready(page);const state=await page.evaluate(()=>window.__pocketDebug.game.state);await page.reload();await ready(page);expect(await page.evaluate(()=>window.__pocketDebug.game.state)).toEqual(state);await page.locator('#pocket-undo').click();expect(await page.evaluate(()=>window.__pocketDebug.game.state)).toEqual(initial);
      let guard=0;while(!await page.evaluate(()=>window.__pocketDebug.game.won)&&guard++<160)await hintStep(page);await ready(page);await expect(page.locator('#pocket-finish')).toBeVisible();await page.locator('#pocket-next').click();await expect(page.locator('#pocket-number')).toContainText('02 / 48');expect(errors).toEqual([]);
    });
    test(`${mode}: expert chapter, native hint and layouts at 1440, 390 and 320 pixels`,async({page})=>{
      await mkdir('.local/screenshots',{recursive:true});for(const width of [1440,390,320]){await page.setViewportSize({width,height:1000});await page.goto(`/${mode}.html`);await ready(page);await page.locator('#pocket-collection').click();await expect(page.locator('#pocket-chapters button')).toHaveCount(4);await page.locator('[data-chapter="3"]').click();await expect(page.locator('#pocket-levels button')).toHaveCount(12);await page.locator('[data-level="47"]').click();await ready(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.locator('#pocket-hint').click();await page.waitForFunction(()=>window.__pocketDebug.hint?.action);await page.screenshot({path:`.local/screenshots/${mode}-${width}.png`,fullPage:true});await page.keyboard.press('Enter');await ready(page);expect(await page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(1);await page.locator('#pocket-restart').click();}
    });
  }
  test('three expert puzzles finish through normal animated hints and return to their collection',async({page})=>{
    const errors=[];page.on('pageerror',e=>errors.push(e.message));for(const mode of modes){await page.goto(`/${mode}.html`);await ready(page);await page.locator('#pocket-collection').click();await page.locator('[data-chapter="3"]').click();await page.locator('[data-level="47"]').click();let guard=0;while(!await page.evaluate(()=>window.__pocketDebug.game.won)&&guard++<160)await hintStep(page);await ready(page);await expect(page.locator('#pocket-finish')).toBeVisible();await page.locator('#pocket-next').click();await expect(page.locator('#pocket-collection-dialog')).toBeVisible();}expect(errors).toEqual([]);
  });
  test('native mobile touch moves and cancels without changing the boards',async({browser})=>{
    const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true}),page=await context.newPage();for(const mode of modes){await page.goto(`/${mode}.html`);await ready(page);const initial=await page.evaluate(()=>window.__pocketDebug.game.state),action=await page.evaluate(()=>window.__pocketDebug.game.level.solution[0]);await pointer(page,mode,action,true);await expect.poll(()=>page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(1);await ready(page);await page.locator('#pocket-undo').click();expect(await page.evaluate(()=>window.__pocketDebug.game.state)).toEqual(initial);await page.locator('#pocket-stage').scrollIntoViewIfNeeded();const points=await pointsFor(page,mode,action),session=await context.newCDPSession(page);await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[points[0]]});await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[points.at(-1)]});await session.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});await session.detach();expect(await page.evaluate(()=>window.__pocketDebug.game.state)).toEqual(initial);}await context.close();
  });
  test('cairns: native buttons select without moving and number keys transfer the top ring',async({page})=>{
    await page.goto('/cairns.html');await ready(page);const action=await page.evaluate(()=>window.__pocketDebug.game.level.solution[0]),button=page.locator(`[data-cairn-peg="${action.from}"]`);await button.focus();await page.keyboard.press(' ');await expect(button).toHaveAttribute('aria-pressed','true');expect(await page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(0);await page.locator('#pocket-canvas').focus();await page.keyboard.press(String(action.to+1));await ready(page);expect(await page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(1);await page.locator('#pocket-undo').click();await page.locator(`[data-cairn-peg="${action.from}"]`).click();await page.locator(`[data-cairn-peg="${action.to}"]`).focus();await page.keyboard.press('Enter');await ready(page);expect(await page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(1);
  });
  test('@core jalons: a continuous route paints once and undoes as one complete gesture',async({page})=>{
    await page.goto('/jalons.html');await ready(page);const initial=await page.evaluate(()=>window.__pocketDebug.game.state),route=await page.evaluate(()=>window.__pocketDebug.game.level.route);await pointer(page,'jalons',{path:route});await ready(page);expect(await page.evaluate(()=>window.__pocketDebug.game.won)).toBe(true);expect(await page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(1);await page.locator('#pocket-undo').click();expect(await page.evaluate(()=>window.__pocketDebug.game.state)).toEqual(initial);await page.locator(`[data-jalon-cell="${route[1]}"]`).focus();await page.keyboard.press('Enter');await ready(page);expect(await page.evaluate(()=>window.__pocketDebug.game.state.path)).toEqual(route.slice(0,2));
  });
  test('cagettes: keyboard and native directional buttons animate actual bodies; undo cancels the move',async({page})=>{
    await page.goto('/cagettes.html');await ready(page);const initial=await page.evaluate(()=>window.__pocketDebug.game.state),a=await page.evaluate(()=>window.__pocketDebug.game.level.solution[0]);await page.locator(`[data-orchard-dir="${a.dir}"]`).focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>window.__pocketDebug.scene.running);await page.locator('#pocket-undo').click();expect(await page.evaluate(()=>window.__pocketDebug.game.state)).toEqual(initial);expect(await page.evaluate(()=>window.__pocketDebug.scene.motion)).toBeNull();await page.locator('#pocket-canvas').focus();await page.keyboard.press(['ArrowUp','ArrowRight','ArrowDown','ArrowLeft'][a.dir]);await ready(page);expect(await page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(1);
  });
  test('forty-two illustrated cards open the new games and rules without overflow',async({page})=>{
    for(const width of [1440,390,320]){await page.setViewportSize({width,height:1000});await page.goto('/');await expect(page.locator('.game-card')).toHaveCount(42);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}for(const name of ['Cagettes','Cairns','Jalons']){await page.getByRole('link',{name:`Jouer à ${name}`,exact:true}).click();await ready(page);await page.locator('#pocket-help').click();await expect(page.locator('#pocket-help-dialog')).toBeVisible();await page.getByRole('button',{name:'Fermer les règles',exact:true}).click();await page.getByRole('link',{name:'Les jeux',exact:true}).click();}
  });
});
