import {test,expect} from '@playwright/test';
import {mkdir} from 'node:fs/promises';
const modes=['noeuds','gouttes'];
async function ready(page){await page.waitForFunction(()=>window.__pocketDebug?.scene&&window.__pocketDebug.ready);}
async function hintStep(page){await ready(page);await page.locator('#pocket-hint').click();await page.waitForFunction(()=>window.__pocketDebug.hint?.action);await page.keyboard.press('Enter');}
async function pointerAction(page,mode,action,touch=false){
  const points=await page.evaluate(({mode,action})=>mode==='noeuds'?[window.__pocketDebug.scene.screenPoint({pin:action.pin}),window.__pocketDebug.scene.screenPoint({peg:action.peg})]:action.path.map(p=>window.__pocketDebug.scene.screenPoint(p)),{mode,action});
  if(touch){const session=await page.context().newCDPSession(page);await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[points[0]]});for(const p of points.slice(1))await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[p]});await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await session.detach();}
  else{await page.mouse.move(points[0].x,points[0].y);await page.mouse.down();for(const p of points.slice(1))await page.mouse.move(p.x,p.y,{steps:12});await page.mouse.up();}
}
for(const mode of modes){
  test(`${mode}: real dragging, exact save reload, undo, hints, completed game and next puzzle`,async({page})=>{
    const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`/${mode}.html`);await ready(page);const initial=await page.evaluate(()=>window.__pocketDebug.game.state),action=await page.evaluate(()=>window.__pocketDebug.game.level.solution[0]);
    await pointerAction(page,mode,action);await expect.poll(()=>page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(1);const moved=await page.evaluate(()=>window.__pocketDebug.game.state);await page.reload();await ready(page);expect(await page.evaluate(()=>window.__pocketDebug.game.state)).toEqual(moved);await page.locator('#pocket-undo').click();expect(await page.evaluate(()=>window.__pocketDebug.game.state)).toEqual(initial);
    let guard=0;while(!await page.evaluate(()=>window.__pocketDebug.game.won)&&guard++<40)await hintStep(page);await expect(page.locator('#pocket-finish')).toBeVisible({timeout:10000});await expect(page.locator('#pocket-total')).toHaveText('1 / 48');await page.locator('#pocket-next').click();await expect(page.locator('#pocket-number')).toContainText('02 / 48');await page.reload();await ready(page);await expect(page.locator('#pocket-total')).toHaveText('1 / 48');expect(errors).toEqual([]);
  });
  test(`${mode}: expert collection, verified hints, desktop and small-screen layouts`,async({page})=>{
    await mkdir('.local/screenshots',{recursive:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));
    for(const width of [1440,390,320]){await page.setViewportSize({width,height:width===1440?1000:844});await page.goto(`/${mode}.html`);await ready(page);await page.locator('#pocket-collection').click();await expect(page.locator('#pocket-levels button')).toHaveCount(12);await page.locator('[data-chapter="3"]').click();await page.locator('[data-level="47"]').click();await ready(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.locator('#pocket-hint').click();await page.waitForFunction(()=>window.__pocketDebug.hint?.action);await page.screenshot({path:`.local/screenshots/${mode}-${width}.png`,fullPage:true});await page.keyboard.press('Enter');await ready(page);await expect.poll(()=>page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(1);await page.locator('#pocket-help').click();await expect(page.locator('#pocket-help-dialog')).toBeVisible();await page.getByRole('button',{name:'Fermer les règles',exact:true}).click();await page.locator('#pocket-restart').click();}expect(errors).toEqual([]);
  });
  test(`${mode}: native touch dragging on mobile`,async({browser})=>{
    const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true}),page=await context.newPage();await page.goto(`/${mode}.html`);await ready(page);await page.locator('#pocket-stage').scrollIntoViewIfNeeded();const action=await page.evaluate(()=>window.__pocketDebug.game.level.solution[0]);await pointerAction(page,mode,action,true);await expect.poll(()=>page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(1);await page.locator('#pocket-undo').click();await expect.poll(()=>page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(0);await context.close();
  });
}
test('@core gouttes: failed water, direct hand-drawn victory, live animation and exact undo cancellation',async({page})=>{
  await page.goto('/gouttes.html');await ready(page);await page.getByRole('button',{name:/Laisser couler/}).click();await page.waitForFunction(()=>window.__pocketDebug.scene.running);await ready(page);await expect(page.locator('#pocket-status')).toContainText('ajustez');expect(await page.evaluate(()=>window.__pocketDebug.game.won)).toBe(false);
  await page.reload();await ready(page);expect(await page.evaluate(()=>window.__pocketDebug.game.state.result.caught)).toBe(0);await page.locator('#pocket-restart').click();const action=await page.evaluate(()=>window.__pocketDebug.game.level.solution[0]);await pointerAction(page,'gouttes',action);await page.keyboard.press('e');await page.waitForFunction(()=>window.__pocketDebug.scene.running);await page.waitForFunction(()=>window.__pocketDebug.scene.water.particles.length>5);await page.locator('#pocket-stage').screenshot({path:'.local/screenshots/gouttes-playing.png'});
  await expect(page.locator('#pocket-finish')).not.toBeVisible();await page.locator('#pocket-undo').click();expect(await page.evaluate(()=>window.__pocketDebug.scene.running)).toBe(false);expect(await page.evaluate(()=>window.__pocketDebug.game.state.result)).toBe(null);await page.waitForTimeout(300);await expect(page.locator('#pocket-finish')).not.toBeVisible();await page.keyboard.press('e');await expect(page.locator('#pocket-finish')).toBeVisible({timeout:10000});
});
test('@core gouttes: accessible point drawing and an expert two-ramp stream work with reduced motion',async({page})=>{
  await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/gouttes.html');await ready(page);await page.locator('#pocket-collection').click();await page.locator('[data-chapter="3"]').click();await page.locator('[data-level="47"]').click();await ready(page);const actions=await page.evaluate(()=>window.__pocketDebug.game.level.solution.filter(a=>a.type==='draw'));
  for(const action of actions){await page.locator('.physics-assisted summary').click();for(const [x,y] of action.path){await page.locator('#water-x').fill(String(x));await page.locator('#water-y').fill(String(y));await page.locator('[data-water-point]').click();}await page.locator('[data-water-place]').click();}
  await page.getByRole('button',{name:/Laisser couler/}).click();await expect(page.locator('#pocket-finish')).toBeVisible();expect(await page.evaluate(()=>window.__pocketDebug.game.state.result.caught)).toBe(60);expect(await page.evaluate(()=>window.__pocketDebug.scene.running)).toBe(false);
});
test('twenty-four illustrated home games open Nœuds and Gouttes and return home',async({page})=>{
  await mkdir('.local/screenshots',{recursive:true});for(const width of [1440,390,320]){await page.setViewportSize({width,height:1000});await page.goto('/');await expect(page.locator('.game-card')).toHaveCount(39);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);if(width!==320)await page.screenshot({path:`.local/screenshots/fifteen-games-${width}.png`,fullPage:true});}
  for(const [mode,name] of [['noeuds','Nœuds'],['gouttes','Gouttes']]){await page.getByRole('link',{name:`Jouer à ${name}`,exact:true}).click();await ready(page);await expect(page).toHaveURL(new RegExp(`/${mode}\\.html$`));await page.getByRole('link',{name:'Les jeux',exact:true}).click();await expect(page.locator('.game-card')).toHaveCount(39);}
});
