import {test,expect} from '@playwright/test';
import {mkdir} from 'node:fs/promises';
const modes=['ruisseaux','balancier','gelees'];
async function ready(page){await page.waitForFunction(()=>window.__pocketDebug?.scene&&window.__pocketDebug.ready);}
async function hintStep(page){await ready(page);await page.locator('#pocket-hint').click();await page.waitForFunction(()=>window.__pocketDebug.hint?.action!==undefined);await page.keyboard.press('Enter');}
async function pointer(page,mode,a,touch=false){
  await page.locator('#pocket-stage').scrollIntoViewIfNeeded();
  if(mode==='gelees'){await page.locator(`[data-jelly="${a.id}"]`).click();for(let n=0;n<a.turns;n++)await page.keyboard.press('t');await page.locator('#pocket-stage').scrollIntoViewIfNeeded();}
  const points=await page.evaluate(({mode,a})=>{const s=window.__pocketDebug.scene;return mode==='ruisseaux'?[s.screenPoint(a.from),s.screenPoint(a.to)]:mode==='balancier'?[s.ropeScreenPoint(a.rope)]:[s.screenPoint(a.x)];},{mode,a});
  if(touch){const session=await page.context().newCDPSession(page);await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[points[0]]});for(const p of points.slice(1))await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[p]});await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await session.detach();}
  else if(points.length===1)await page.mouse.click(points[0].x,points[0].y);else{await page.mouse.move(points[0].x,points[0].y);await page.mouse.down();await page.mouse.move(points[1].x,points[1].y,{steps:10});await page.mouse.up();}
}
for(const mode of modes){
  test(`${mode}: pointer action, exact save/reload and undo, visible hints complete puzzle and next`,async({page})=>{
    const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`/${mode}.html`);await ready(page);const initial=await page.evaluate(()=>window.__pocketDebug.game.state),a=await page.evaluate(()=>window.__pocketDebug.game.level.solution[0]);await pointer(page,mode,a);await expect.poll(()=>page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(1);await ready(page);const moved=await page.evaluate(()=>window.__pocketDebug.game.state);await page.reload();await ready(page);expect(await page.evaluate(()=>window.__pocketDebug.game.state)).toEqual(moved);await page.locator('#pocket-undo').click();expect(await page.evaluate(()=>window.__pocketDebug.game.state)).toEqual(initial);
    let guard=0;while(!await page.evaluate(()=>window.__pocketDebug.game.won)&&guard++<100)await hintStep(page);await ready(page);await expect(page.locator('#pocket-finish')).toBeVisible();await expect(page.locator('#pocket-total')).toHaveText('1 / 48');await page.locator('#pocket-next').click();await expect(page.locator('#pocket-number')).toContainText('02 / 48');expect(errors).toEqual([]);
  });
  test(`${mode}: expert 48, narrow layouts, rules and chapters`,async({page})=>{
    await mkdir('.local/screenshots',{recursive:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));for(const width of [1440,390,320]){await page.setViewportSize({width,height:width===1440?1000:844});await page.goto(`/${mode}.html`);await ready(page);await page.locator('#pocket-collection').click();await expect(page.locator('#pocket-chapters button')).toHaveCount(4);await page.locator('[data-chapter="3"]').click();await expect(page.locator('#pocket-levels button')).toHaveCount(12);await page.locator('[data-level="47"]').click();await ready(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.locator('#pocket-hint').click();await page.waitForFunction(()=>window.__pocketDebug.hint?.action!==undefined);await page.screenshot({path:`.local/screenshots/${mode}-${width}.png`,fullPage:true});await page.keyboard.press('Enter');await ready(page);expect(await page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(1);await page.locator('#pocket-help').click();await expect(page.locator('#pocket-help-dialog')).toBeVisible();await page.getByRole('button',{name:'Fermer les règles',exact:true}).click();await page.locator('#pocket-restart').click();}expect(errors).toEqual([]);
  });
  test(`${mode}: native touch performs a move and undo`,async({browser})=>{
    const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),page=await context.newPage();await page.goto(`/${mode}.html`);await ready(page);const a=await page.evaluate(()=>window.__pocketDebug.game.level.solution[0]);await pointer(page,mode,a,true);await expect.poll(()=>page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(1);await ready(page);await page.locator('#pocket-undo').click();expect(await page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(0);await context.close();
  });
}
test('@core ruisseaux: sidebar and arrows slide a chosen tile; fixed cells and cancelled drags do not move',async({page})=>{
  await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/ruisseaux.html');await ready(page);const a=await page.evaluate(()=>window.__pocketDebug.game.level.solution[0]),source=await page.evaluate(()=>window.__pocketDebug.game.level.source);await page.locator(`[data-stream="${source}"]`).click();expect(await page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(0);await page.locator(`[data-stream="${a.from}"]`).click();await page.locator(`[data-stream="${a.to}"]`).click();expect(await page.evaluate(()=>window.__pocketDebug.game.moves[0])).toEqual(a);await page.locator('#pocket-undo').click();await page.locator(`[data-stream="${a.from}"]`).click();const size=await page.evaluate(()=>window.__pocketDebug.game.level.size),delta=a.to-a.from;await page.keyboard.press(delta===1?'ArrowRight':delta===-1?'ArrowLeft':delta===size?'ArrowDown':'ArrowUp');expect(await page.evaluate(()=>window.__pocketDebug.game.moves[0])).toEqual(a);await page.locator('#pocket-restart').click();await page.locator('#pocket-stage').scrollIntoViewIfNeeded();const p=await page.evaluate(a=>window.__pocketDebug.scene.screenPoint(a.from),a);await page.mouse.move(p.x,p.y);await page.mouse.down();await page.dispatchEvent('#pocket-canvas','pointercancel',{pointerId:1});await page.mouse.up();expect(await page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(0);
});
test('@core balancier: real pendulum starts paused, advances, pauses in dialog and records exact live cut time',async({page})=>{
  await page.goto('/balancier.html');await ready(page);expect(await page.evaluate(()=>window.__pocketDebug.scene.flow.tick)).toBe(0);await page.locator('[data-swing-pause]').click();await page.waitForFunction(()=>window.__pocketDebug.scene.flow.tick>20);await page.keyboard.press('Space');const tick=await page.evaluate(()=>window.__pocketDebug.scene.flow.tick);await page.waitForTimeout(120);expect(await page.evaluate(()=>window.__pocketDebug.scene.flow.tick)).toBe(tick);await page.keyboard.press('Space');await page.locator('#pocket-help').click();const paused=await page.evaluate(()=>window.__pocketDebug.scene.flow.tick);await page.waitForTimeout(120);expect(await page.evaluate(()=>window.__pocketDebug.scene.flow.tick)).toBe(paused);await page.getByRole('button',{name:'Fermer les règles',exact:true}).click();await page.keyboard.press('Space');const cut=await page.evaluate(()=>window.__pocketDebug.scene.flow.tick);await page.locator('[data-rope="0"]').click();expect(await page.evaluate(()=>window.__pocketDebug.game.moves[0])).toEqual({rope:0,tick:cut});await page.locator('#pocket-undo').click();expect(await page.evaluate(()=>window.__pocketDebug.scene.flow.tick)).toBe(0);expect(await page.evaluate(()=>window.__pocketDebug.scene.paused)).toBe(true);
});
test('@core gelees: actual tray drag, rotations, preview column and undo during spring animation',async({page})=>{
  await page.goto('/gelees.html');await ready(page);const a=await page.evaluate(()=>window.__pocketDebug.game.level.solution[0]);await page.locator(`[data-jelly="${a.id}"]`).click();for(let n=0;n<a.turns;n++)await page.locator('[data-jelly-rotate]').click();for(let n=0;n<a.x;n++)await page.keyboard.press('ArrowRight');expect(await page.evaluate(()=>window.__pocketDebug.scene.cursor)).toBe(a.x);await page.keyboard.press('Space');await page.waitForFunction(()=>window.__pocketDebug.scene.running);await expect(page.locator('[data-jelly-rotate]')).toBeDisabled();await page.locator('#pocket-help').click();const age=await page.evaluate(()=>window.__pocketDebug.scene.motion.age);await page.waitForTimeout(150);expect(await page.evaluate(()=>window.__pocketDebug.scene.motion.age)).toBe(age);await page.getByRole('button',{name:'Fermer les règles',exact:true}).click();await page.locator('#pocket-undo').click();expect(await page.evaluate(()=>window.__pocketDebug.scene.running)).toBe(false);expect(await page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(0);
  const tray=await page.evaluate(()=>window.__pocketDebug.scene.tray()[0]);await page.locator(`[data-jelly="${tray}"]`).click();await page.keyboard.press('t');await page.locator('#pocket-stage').scrollIntoViewIfNeeded();const pts=await page.evaluate(id=>{const s=window.__pocketDebug.scene;return[s.jellyScreenPoint(id),s.screenPoint(0)];},tray);await page.mouse.move(pts[0].x,pts[0].y);await page.mouse.down();await page.mouse.move(pts[1].x,pts[1].y,{steps:10});await page.mouse.up();await expect.poll(()=>page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(1);expect(await page.evaluate(()=>window.__pocketDebug.game.moves[0].turns)).toBe(1);
});
test('all three expert puzzles finish with visible hints and reduced motion; last puzzle returns to collection',async({page})=>{
  await page.emulateMedia({reducedMotion:'reduce'});for(const mode of modes){await page.goto(`/${mode}.html`);await ready(page);await page.locator('#pocket-collection').click();await page.locator('[data-chapter="3"]').click();await page.locator('[data-level="47"]').click();let guard=0;while(!await page.evaluate(()=>window.__pocketDebug.game.won)&&guard++<100)await hintStep(page);await ready(page);await expect(page.locator('#pocket-finish')).toBeVisible();expect(await page.evaluate(()=>window.__pocketDebug.scene.running)).toBe(false);await page.locator('#pocket-next').click();await expect(page.locator('#pocket-collection-dialog')).toBeVisible();}
});
test('twenty-seven illustrations link to the new games and return home without overflow',async({page})=>{
  for(const width of [1440,390,320]){await page.setViewportSize({width,height:1000});await page.goto('/');await expect(page.locator('.game-card')).toHaveCount(36);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}for(const [mode,name] of [['ruisseaux','Ruisseaux'],['balancier','Balancier'],['gelees','Gelées']]){await page.getByRole('link',{name:`Jouer à ${name}`,exact:true}).click();await ready(page);await expect(page).toHaveURL(new RegExp(`/${mode}\\.html$`));await page.getByRole('link',{name:'Les jeux',exact:true}).click();await expect(page.locator('.game-card')).toHaveCount(36);}
});
