import {test,expect} from '@playwright/test';
import {mkdir} from 'node:fs/promises';

test.describe('travel',()=>{
const modes=['valises','sangles','traces'];
async function ready(page){await page.waitForFunction(()=>window.__pocketDebug?.scene&&window.__pocketDebug.ready);}
async function hintStep(page){await ready(page);await page.locator('#pocket-hint').click();await page.waitForFunction(()=>window.__pocketDebug.hint?.action!==undefined);await page.keyboard.press('Enter');}
async function pointer(page,mode,a,touch=false){
  if(mode==='valises'){await page.locator(`[data-bag-pick="${a.id}"]`).click();for(let n=0;n<a.turns;n++)await page.keyboard.press('t');}if(mode==='sangles')await page.locator(`[data-strap-pick="${a.id}"]`).click();
  await page.locator('#pocket-stage').scrollIntoViewIfNeeded();const points=await page.evaluate(({mode,a})=>{const s=window.__pocketDebug.scene;return mode==='valises'?s.bagScreenPoints(a):(mode==='sangles'?a.path:a.path).map(id=>s.screenPoint(id));},{mode,a});
  if(touch){const session=await page.context().newCDPSession(page);await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[points[0]]});for(const p of points.slice(1))await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[p]});await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await session.detach();}
  else{await page.mouse.move(points[0].x,points[0].y);await page.mouse.down();for(const p of points.slice(1))await page.mouse.move(p.x,p.y,{steps:12});await page.mouse.up();}
}
for(const mode of modes){
  test(`${mode}: pointer gameplay, exact reload/undo, verified first completion and next`,async({page})=>{const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`/${mode}.html`);await ready(page);const a=await page.evaluate(()=>window.__pocketDebug.game.level.solution[0]);await pointer(page,mode,a);await expect.poll(()=>page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(1);await ready(page);const state=await page.evaluate(()=>window.__pocketDebug.game.state);await page.reload();await ready(page);expect(await page.evaluate(()=>window.__pocketDebug.game.state)).toEqual(state);await page.locator('#pocket-undo').click();expect(await page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(0);let guard=0;while(!await page.evaluate(()=>window.__pocketDebug.game.won)&&guard++<160)await hintStep(page);await ready(page);await expect(page.locator('#pocket-finish')).toBeVisible();await page.locator('#pocket-next').click();expect(await page.evaluate(()=>window.__pocketDebug.game.level.index)).toBe(1);expect(errors).toEqual([]);});
  test(`${mode}: expert chapters, hints, rules and layouts at 1440, 390 and 320`,async({page})=>{await mkdir('.local/screenshots',{recursive:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));for(const width of [1440,390,320]){await page.setViewportSize({width,height:width===1440?1000:844});await page.goto(`/${mode}.html`);await ready(page);await page.locator('#pocket-collection').click();await expect(page.locator('#pocket-chapters button')).toHaveCount(4);await page.locator('[data-chapter="3"]').click();await expect(page.locator('#pocket-levels button')).toHaveCount(12);await page.locator('[data-level="47"]').click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.locator('#pocket-hint').click();await page.waitForFunction(()=>window.__pocketDebug.hint?.action);await page.screenshot({path:`.local/screenshots/${mode}-${width}.png`,fullPage:true});await page.keyboard.press('Enter');await ready(page);expect(await page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(1);await page.locator('#pocket-help').click();await expect(page.locator('#pocket-help-dialog')).toBeVisible();await page.getByRole('button',{name:'Fermer les règles',exact:true}).click();await page.locator('#pocket-restart').click();}expect(errors).toEqual([]);});
  test(`${mode}: native mobile touch and undo`,async({browser})=>{const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),page=await context.newPage();await page.goto(`/${mode}.html`);await ready(page);const a=await page.evaluate(()=>window.__pocketDebug.game.level.solution[0]);await pointer(page,mode,a,true);await expect.poll(()=>page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(1);await ready(page);await page.locator('#pocket-undo').click();expect(await page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(0);await context.close();});
}
test('@core valises: sidebar placement, keyboard rotation and cancelled drag preserve the packing',async({page})=>{await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/valises.html');await ready(page);for(const id of [0,1]){await page.locator(`[data-bag-pick="${id}"]`).focus();await page.keyboard.press('Space');expect(await page.evaluate(()=>window.__pocketDebug.selected)).toBe(id);expect(await page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(0);}const a=await page.evaluate(()=>window.__pocketDebug.game.level.solution[0]);await page.locator(`[data-bag-pick="${a.id}"]`).click();for(let n=0;n<a.turns;n++)await page.keyboard.press('t');const cell=await page.evaluate(a=>a.y*window.__pocketDebug.game.level.cols+a.x,a);await page.locator(`[data-bag-cell="${cell}"]`).click();expect(await page.evaluate(()=>window.__pocketDebug.game.moves[0])).toEqual(a);expect(await page.evaluate(()=>window.__pocketDebug.scene.motion)).toBe(null);await page.locator('#pocket-undo').click();await page.locator('#pocket-stage').scrollIntoViewIfNeeded();const points=await page.evaluate(a=>window.__pocketDebug.scene.bagScreenPoints(a),a);await page.mouse.move(points[0].x,points[0].y);await page.mouse.down();await page.dispatchEvent('#pocket-canvas','pointercancel',{pointerId:1});await page.mouse.up();expect(await page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(0);});
test('@core sangles: anchor buttons, real trial lock, dialog pause and undo cancel travel',async({page})=>{await page.goto('/sangles.html');await ready(page);await page.locator('#pocket-collection').click();await page.locator('[data-chapter="3"]').click();await page.locator('[data-level="47"]').click();const a=await page.evaluate(()=>window.__pocketDebug.game.level.solution[0]);await page.locator(`[data-strap-pick="${a.id}"]`).click();for(const id of a.path)await page.locator(`[data-strap-post="${id}"]`).click();await page.locator('[data-strap-place]').click();expect(await page.evaluate(()=>window.__pocketDebug.game.moves[0])).toEqual(a);await page.keyboard.press('e');await page.waitForFunction(()=>window.__pocketDebug.scene.running);await expect(page.locator('[data-cargo-run]')).toBeDisabled();await expect(page.locator('[data-strap-post="0"]')).toBeDisabled();await page.locator('#pocket-help').click();const tick=await page.evaluate(()=>window.__pocketDebug.scene.flow.tick);await page.waitForTimeout(160);expect(await page.evaluate(()=>window.__pocketDebug.scene.flow.tick)).toBe(tick);await page.getByRole('button',{name:'Fermer les règles',exact:true}).click();await page.locator('#pocket-undo').click();expect(await page.evaluate(()=>window.__pocketDebug.scene.running)).toBe(false);expect(await page.evaluate(()=>window.__pocketDebug.game.state.result)).toBe(null);expect(await page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(1);});
test('@core traces: a whole mouse stroke is one undoable action, sidebar drafting and Backspace work',async({page})=>{await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/traces.html');await ready(page);const path=await page.evaluate(()=>window.__pocketDebug.game.level.route.slice(0,4));for(const id of path.slice(0,3)){await page.locator(`[data-trace-node="${id}"]`).focus();await page.keyboard.press('Enter');}expect(await page.evaluate(()=>window.__pocketDebug.selected)).toEqual(path.slice(0,3));expect(await page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(0);await page.keyboard.press('Escape');await pointer(page,'traces',{path});expect(await page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(1);expect(await page.evaluate(()=>window.__pocketDebug.game.state.path)).toEqual(path);await page.locator('#pocket-undo').click();expect(await page.evaluate(()=>window.__pocketDebug.game.state.path)).toEqual([]);for(const id of path)await page.locator(`[data-trace-node="${id}"]`).click();await page.keyboard.press('Backspace');expect(await page.evaluate(()=>window.__pocketDebug.selected)).toEqual(path.slice(0,-1));await page.keyboard.press('Enter');expect(await page.evaluate(()=>window.__pocketDebug.game.state.path)).toEqual(path.slice(0,-1));await page.locator('#pocket-undo').click();expect(await page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(0);});
test('all three expert puzzles complete with reduced motion and return to the collection',async({page})=>{await page.emulateMedia({reducedMotion:'reduce'});for(const mode of modes){await page.goto(`/${mode}.html`);await ready(page);await page.locator('#pocket-collection').click();await page.locator('[data-chapter="3"]').click();await page.locator('[data-level="47"]').click();let guard=0;while(!await page.evaluate(()=>window.__pocketDebug.game.won)&&guard++<160)await hintStep(page);await ready(page);await expect(page.locator('#pocket-finish')).toBeVisible();if(mode==='sangles')expect(await page.evaluate(()=>window.__pocketDebug.game.state.result.caught)).toBe(9);await page.locator('#pocket-next').click();await expect(page.locator('#pocket-collection-dialog')).toBeVisible();}});
test('thirty-three illustrated home cards open Valises, Sangles and Tracés',async({page})=>{for(const width of [1440,390,320]){await page.setViewportSize({width,height:1000});await page.goto('/');await expect(page.locator('.game-card')).toHaveCount(42);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}for(const [mode,name] of [['valises','Valises'],['sangles','Sangles'],['traces','Tracés']]){await page.getByRole('link',{name:`Jouer à ${name}`,exact:true}).click();await ready(page);await expect(page).toHaveURL(new RegExp(`/${mode}\\.html$`));await page.getByRole('link',{name:'Les jeux',exact:true}).click();await expect(page.locator('.game-card')).toHaveCount(42);}});

});
