import {test,expect} from '@playwright/test';
import {mkdir} from 'node:fs/promises';

const modes=['bosquets','gravures','veillees'];
async function ready(page){await page.waitForFunction(()=>window.__pocketDebug?.ready);}
async function step(page){await ready(page);await page.locator('#pocket-hint').click();await page.waitForFunction(()=>window.__pocketDebug.hint?.action);await page.keyboard.press('Enter');}
async function pointer(page,ids,touch=false,cancel=false){
  await page.locator('#pocket-stage').scrollIntoViewIfNeeded();const points=await page.evaluate(ids=>ids.map(id=>window.__pocketDebug.scene.screenPoint(id)),ids);
  if(touch){const session=await page.context().newCDPSession(page);await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[points[0]]});for(const point of points.slice(1))await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[point]});await session.send('Input.dispatchTouchEvent',{type:cancel?'touchCancel':'touchEnd',touchPoints:[]});await session.detach();}
  else{await page.mouse.move(points[0].x,points[0].y);await page.mouse.down();for(const point of points.slice(1))await page.mouse.move(point.x,point.y,{steps:12});await page.mouse.up();}
}
test.describe('@current twilight',()=>{
  for(const mode of modes){
    test(`${mode}: actual pointer, exact reload/undo and first completion`,async({page})=>{
      const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`/${mode}.html`);await ready(page);const initial=await page.evaluate(()=>window.__pocketDebug.game.state),cell=await page.evaluate(()=>{const a=window.__pocketDebug.game.level.solution[0];return a.cell??a.cells[0];});await pointer(page,[cell]);await expect.poll(()=>page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(1);await ready(page);const state=await page.evaluate(()=>window.__pocketDebug.game.state);await page.reload();await ready(page);expect(await page.evaluate(()=>window.__pocketDebug.game.state)).toEqual(state);await page.locator('#pocket-undo').click();expect(await page.evaluate(()=>window.__pocketDebug.game.state)).toEqual(initial);let guard=0;while(!await page.evaluate(()=>window.__pocketDebug.game.won)&&guard++<100)await step(page);await ready(page);await expect(page.locator('#pocket-finish')).toBeVisible();await page.locator('#pocket-next').click();await expect(page.locator('#pocket-number')).toContainText('02 / 48');expect(errors).toEqual([]);
    });
    test(`${mode}: expert collection, hints and layouts at 1440, 390 and 320 pixels`,async({page})=>{
      await mkdir('.local/screenshots',{recursive:true});for(const width of [1440,390,320]){await page.setViewportSize({width,height:1000});await page.goto(`/${mode}.html`);await ready(page);await page.locator('#pocket-collection').click();await expect(page.locator('#pocket-chapters button')).toHaveCount(4);await page.locator('[data-chapter="3"]').click();await expect(page.locator('#pocket-levels button')).toHaveCount(12);await page.locator('[data-level="47"]').click();await ready(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.locator('#pocket-hint').click();await page.waitForFunction(()=>window.__pocketDebug.hint?.action);if(mode==='gravures'){await expect(page.locator('.twilight-clues')).toHaveAttribute('open','');await expect(page.locator('.twilight-clues span')).toHaveCount(16);}await page.screenshot({path:`.local/screenshots/${mode}-${width}.png`,fullPage:true});if(mode==='gravures'){await page.locator('.twilight-clues summary').click();await page.locator('#pocket-canvas').focus();}await page.keyboard.press('Enter');await ready(page);expect(await page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(1);if(mode==='gravures')await expect(page.locator('.twilight-clues')).not.toHaveAttribute('open','');await page.locator('#pocket-restart').click();if(mode==='gravures')await page.locator('.twilight-clues summary').click();}
    });
  }
  test('three expert boards finish using normal animations and reduced motion executes exactly one hinted action',async({page})=>{
    const errors=[];page.on('pageerror',e=>errors.push(e.message));for(const reduce of [false,true]){await page.emulateMedia({reducedMotion:reduce?'reduce':'no-preference'});for(const mode of modes){await page.goto(`/${mode}.html`);await ready(page);await page.locator('#pocket-collection').click();await page.locator('[data-chapter="3"]').click();await page.locator('[data-level="47"]').click();await step(page);expect(await page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(1);let guard=0;while(!await page.evaluate(()=>window.__pocketDebug.game.won)&&guard++<100)await step(page);await ready(page);await expect(page.locator('#pocket-finish')).toBeVisible();await page.locator('#pocket-next').click();await expect(page.locator('#pocket-collection-dialog')).toBeVisible();}}expect(errors).toEqual([]);
  });
  test('native mobile drawing is one action and cancelled gestures preserve all three boards',async({browser})=>{
    const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true}),page=await context.newPage();for(const mode of modes){await page.goto(`/${mode}.html`);await ready(page);const initial=await page.evaluate(()=>window.__pocketDebug.game.state);await pointer(page,mode==='veillees'?[0]:[0,1,2],true);await expect.poll(()=>page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(1);await ready(page);if(mode!=='veillees')expect(await page.evaluate(()=>window.__pocketDebug.game.state.field.slice(0,3))).toEqual([1,1,1]);await page.locator('#pocket-undo').click();expect(await page.evaluate(()=>window.__pocketDebug.game.state)).toEqual(initial);await pointer(page,mode==='veillees'?[0]:[0,1,2],true,true);expect(await page.evaluate(()=>window.__pocketDebug.game.state)).toEqual(initial);}await context.close();
  });
  test('field tools stay selected; native buttons and cursor keys mark once; contradictions are visible',async({page})=>{
    for(const mode of ['bosquets','gravures']){await page.goto(`/${mode}.html`);await ready(page);const cross=page.locator('[data-field-tool="2"]');await cross.focus();await page.keyboard.press(' ');await expect(cross).toHaveAttribute('aria-pressed','true');expect(await page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(0);await page.locator('[data-twilight-cell="0"]').focus();await page.keyboard.press('Enter');await ready(page);await expect(cross).toHaveAttribute('aria-pressed','true');expect(await page.evaluate(()=>window.__pocketDebug.game.state.field[0])).toBe(2);await page.locator('#pocket-canvas').focus();await page.keyboard.press('ArrowRight');await page.keyboard.press(' ');await ready(page);expect(await page.evaluate(()=>window.__pocketDebug.game.state.field[1])).toBe(2);await page.locator('#pocket-restart').click();if(mode==='bosquets'){await page.locator('[data-field-tool="1"]').click();await pointer(page,[0,1]);await ready(page);await expect(page.locator('.twilight-summary')).toHaveClass(/conflict/);await page.locator('#pocket-hint').click();await page.waitForFunction(()=>window.__pocketDebug.hint?.action);const hinted=await page.evaluate(()=>window.__pocketDebug.hint.action),first=hinted.cells[0];await page.locator(`[data-twilight-cell="${first}"]`).focus();await page.keyboard.press('Enter');await ready(page);expect(await page.evaluate(first=>window.__pocketDebug.game.state.field[first],first)).toBe(hinted.value);}}
  });
  test('veillees: native cell toggle animates neighbors and undo cancels every light; keyboard has one effect',async({page})=>{
    await page.goto('/veillees.html');await ready(page);const initial=await page.evaluate(()=>window.__pocketDebug.game.state);await page.locator('[data-twilight-cell="0"]').focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>window.__pocketDebug.scene.running);await page.locator('#pocket-undo').click();expect(await page.evaluate(()=>window.__pocketDebug.game.state)).toEqual(initial);expect(await page.evaluate(()=>window.__pocketDebug.scene.motion)).toBeNull();await page.locator('#pocket-canvas').focus();await page.keyboard.press(' ');await ready(page);expect(await page.evaluate(()=>window.__pocketDebug.game.moves.length)).toBe(1);await page.keyboard.press(' ');await ready(page);expect(await page.evaluate(()=>window.__pocketDebug.game.state)).toEqual(initial);
  });
  test('forty-two original cards open the new games and their rules without overflow',async({page})=>{
    for(const width of [1440,390,320]){await page.setViewportSize({width,height:1000});await page.goto('/');await expect(page.locator('.game-card')).toHaveCount(42);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}for(const name of ['Bosquets','Gravures','Veillées']){await page.getByRole('link',{name:`Jouer à ${name}`,exact:true}).click();await ready(page);await page.locator('#pocket-help').click();await expect(page.locator('#pocket-help-dialog')).toBeVisible();await page.getByRole('button',{name:'Fermer les règles',exact:true}).click();await page.getByRole('link',{name:'Les jeux',exact:true}).click();}
  });
});
