import { CAMPAIGN_SAMPLE } from './campaign-sample.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import {PocketGame,clone,encodePocket,decodePocket} from '../src/pocket-core.js';
import {valisesRules,luggageCells} from '../src/valises-puzzle.js';
import {tracesRules,traceStep,traceLayoutKey} from '../src/traces-puzzle.js';
import {sanglesRules,beltLength,validBelt} from '../src/sangles-puzzle.js';
import {CargoFlow,simulateCargo} from '../src/cargo-simulation.js';
const modes={valises:valisesRules,sangles:sanglesRules,traces:tracesRules};
for(const [name,rules] of Object.entries(modes)){
  test(`${name}: distinct sampled deterministic boards with complete solutions and exact undo`,()=>{const unique=new Set();for(const index of CAMPAIGN_SAMPLE){const g=new PocketGame(rules,index),initial=clone(g.state);assert.deepEqual(rules.create(index),g.level);const signature=clone(g.level);delete signature.index;delete signature.title;delete signature.solution;unique.add(name==='traces'?traceLayoutKey(g.level):JSON.stringify(signature));assert.equal(g.won,false);for(const a of g.level.solution){const before=clone(g.state);assert.ok(g.play(a));assert.ok(g.undo());assert.deepEqual(g.state,before);assert.ok(g.play(a));}assert.ok(g.won);while(g.undo()){}assert.deepEqual(g.state,initial);}assert.equal(unique.size,CAMPAIGN_SAMPLE.length);});
  test(`${name}: sampled hint routes are legal and complete`,()=>{for(const index of CAMPAIGN_SAMPLE){const g=new PocketGame(rules,index);let guard=0;while(!g.won&&guard++<160){const hint=g.hint();assert.ok(hint?.action);assert.ok(g.play(hint.action));}assert.ok(g.won,`${name} ${index}`);}});
  test(`${name}: replay saves reconstruct history and reject invented actions`,()=>{const g=new PocketGame(rules,47);for(const a of g.level.solution.slice(0,2))g.play(a);const saved=encodePocket(g,new Set([0,47]),true),restored=decodePocket(rules,saved);assert.deepEqual(restored.game.state,g.state);assert.deepEqual(restored.game.history,g.history);assert.deepEqual([...restored.completed],[0,47]);assert.equal(restored.sound,true);g.undo();restored.game.undo();assert.deepEqual(restored.game.state,g.state);assert.equal(decodePocket(rules,{...saved,moves:[{bad:true}]}),null);});
}
test('valises: actual rotated footprints enforce pockets, bounds and collisions transactionally',()=>{const l={cols:3,rows:3,mask:[true,true,true,true,false,true,true,true,true],pieces:[{id:0,cells:[[0,0],[1,0]]},{id:1,cells:[[0,0]]}]},s=valisesRules.initial(l);assert.deepEqual(luggageCells(l.pieces[0],1),[[0,0],[0,1]]);assert.equal(valisesRules.move(l,s,{type:'place',id:0,turns:0,x:0,y:1}),null);assert.equal(valisesRules.move(l,s,{type:'place',id:0,turns:0,x:2,y:0}),null);const next=valisesRules.move(l,s,{type:'place',id:0,turns:1,x:0,y:0});assert.ok(next);assert.equal(valisesRules.move(l,next,{type:'place',id:1,turns:0,x:0,y:1}),null);assert.deepEqual(s,valisesRules.initial(l));const removed=valisesRules.move(l,next,{type:'remove',id:0});assert.deepEqual(removed,s);});
test('valises: hints remove a wrong arrangement and verify the complete packing from it',()=>{const g=new PocketGame(valisesRules,0);let alternative=null;for(const p of g.level.pieces)for(let y=0;y<g.level.rows&&!alternative;y++)for(let x=0;x<g.level.cols&&!alternative;x++){const a={type:'place',id:p.id,turns:0,x,y},s=valisesRules.move(g.level,g.state,a);if(s&&JSON.stringify(a)!==JSON.stringify(g.level.solution.find(n=>n.id===p.id)))alternative=a;}assert.ok(alternative);assert.ok(g.play(alternative));const plan=valisesRules.plan(g.level,g.state);assert.ok(plan?.length);for(const a of plan)assert.ok(g.play(a));assert.ok(g.won);});
test('traces: a vertex may be revisited, every edge quota and arrow direction are enforced',()=>{const l={nodes:[{},{},{},{}],edges:[{a:0,b:1,count:2,dir:null},{a:1,b:2,count:1,dir:1},{a:2,b:3,count:1,dir:null},{a:3,b:1,count:1,dir:null}]},s=tracesRules.initial(l);assert.equal(tracesRules.move(l,s,{path:[2,1]}),null);const next=tracesRules.move(l,s,{path:[0,1,2,3,1,0]});assert.ok(next);assert.ok(tracesRules.won(l,next));assert.equal(traceStep(l,next,0,1),null);assert.equal(tracesRules.move(l,s,{path:[0,3]}),null);assert.deepEqual(s,tracesRules.initial(l));});
test('traces: a legal alternate circuit gets a verified completion without invented edges',()=>{const l={nodes:[{},{},{},{}],edges:[{a:0,b:1,count:1,dir:null},{a:1,b:2,count:1,dir:null},{a:2,b:3,count:1,dir:null},{a:3,b:0,count:1,dir:null}],solution:[{path:[0,1]},{path:[1,2]},{path:[2,3]},{path:[3,0]}]},s=tracesRules.move(l,tracesRules.initial(l),{path:[2,1]});const plan=tracesRules.plan(l,s);assert.ok(plan);let next=s;for(const a of plan){next=tracesRules.move(l,next,a);assert.ok(next);}assert.ok(tracesRules.won(l,next));});
test('sangles: anchors, length, initial cargo and repeated hooks constrain actual belts',()=>{const l=sanglesRules.create(47);assert.ok(validBelt(l,0,l.targets[0]));assert.ok(beltLength(l,l.targets[0])<=l.belts[0].maxLength);assert.equal(validBelt(l,0,[0,0]),false);assert.equal(validBelt(l,0,[0,1,2,3,4]),false);assert.equal(validBelt(l,0,[0,9]),false);assert.equal(validBelt(l,0,[99,0]),false);assert.equal(validBelt(l,0,[0]),false);});
test('sangles: unrestrained parcels escape, strong belts retain them and weak straps actually break',()=>{const l=sanglesRules.create(47),s=sanglesRules.initial(l);const empty=simulateCargo(l,s);assert.ok(empty.lost>0);assert.equal(empty.caught+empty.lost,l.parcels.length);s.routes=clone(l.targets);const safe=simulateCargo(l,s);assert.equal(safe.caught,l.parcels.length);assert.ok(safe.peaks.some(n=>n>0));assert.ok(safe.parcels.some((p,id)=>Math.hypot(p.x-l.parcels[id].x,p.y-l.parcels[id].y)>20));const weak=clone(l);weak.belts.forEach(b=>b.strength=.01);const broken=simulateCargo(weak,s);assert.ok(broken.broken.some(Boolean));assert.ok(broken.lost>0);});
test('sangles: live fixed steps and audited trials match exactly and replay failed runs',()=>{const g=new PocketGame(sanglesRules,35);assert.ok(g.play({type:'run'}));assert.equal(g.won,false);const saved=decodePocket(sanglesRules,encodePocket(g,new Set()));assert.deepEqual(saved.game.state,g.state);assert.ok(g.undo());assert.equal(g.state.result,null);for(const a of g.level.solution)g.play(a);const flow=new CargoFlow(g.level,g.state);while(!flow.done)flow.step();assert.deepEqual(flow.result(),g.state.result);assert.equal(flow.result().caught+flow.result().lost,g.level.parcels.length);});
