import {COLORS} from './pocket-core.js';
import {recolteRules} from './recolte-puzzle.js';
import {dizainesRules} from './dizaines-puzzle.js';
import {mosaiqueRules,activePieces,pieceWidth,pieceHeight} from './mosaique-puzzle.js';
export const mosaicSvg=p=>`<svg viewBox="0 0 ${pieceWidth(p)*20+8} ${pieceHeight(p)*20+8}" aria-hidden="true">${p.cells.map(([x,y])=>`<rect x="${4+x*20}" y="${4+y*20}" width="18" height="18" rx="3" fill="${COLORS[p.color].hex}"/><path d="M${7+x*20} ${8+y*20}h9" stroke="#fff8"/>`).join('')}</svg>`;
const cells=(game,mode,selected,hint)=>`<div class="bounty-cells" style="--cols:${game.level.cols??game.level.size}">${game.state.field.map((v,id)=>`<button data-${mode==='recolte'?'chain':'number'}="${id}" ${v===null?'disabled':''} aria-pressed="${mode==='recolte'?selected?.includes?.(id)??false:selected===id}" class="${mode==='recolte'?hint?.action?.path.includes(id)?'hinted':'':[hint?.action?.a,hint?.action?.b].includes(id)?'hinted':''}" aria-label="Case ${id+1}${v===null?', vide':mode==='recolte'?`, ${COLORS[v].name}`:`, nombre ${v}`}" style="${mode==='recolte'&&v!==null?`--color:${COLORS[v].hex}`:''}">${v===null?'·':mode==='recolte'?`<span>${COLORS[v].mark}</span><small>${id+1}</small>`:v}</button>`).join('')}</div>`;
export const bountyConfigs={
  recolte:{name:'Récolte',rules:recolteRules,eyebrow:'DE PROCHE EN PROCHE, LE PANIER SE REMPLIT',title:'Une baie.<br> <em>Et toute une récolte.</em>',copy:'Reliez les petites couleurs.<br>Remplissez vos paniers.',steps:[['Tracez une chaîne.','Reliez au moins trois billes de la même couleur. Les voisines en diagonale comptent aussi.'],['Préparez la suite.','Les billes restantes tombent pour combler les trous. Une petite chaîne peut ouvrir un grand passage.']],note:'Tracez au moins trois billes de même couleur',unit:'billes à récolter',reserve:'Les petits paniers.',reserveCopy:'Chaque couleur a son panier. Récoltez toutes les billes, en gardant assez de voisines pour la suite.',finish:'Le jardin a tout donné.',delay:400,invalid:'Reliez au moins trois billes voisines de la même couleur, sans repasser sur une bille.',
    rulesText:['Tracez une chaîne de trois billes ou plus de même couleur, avec la souris ou le doigt. Les voisins horizontaux, verticaux et diagonaux sont autorisés.','Une bille ne peut apparaître qu’une fois dans une chaîne. Revenez sur une bille de votre tracé pour raccourcir la chaîne avant de relâcher.','Les billes récoltées rejoignent leur panier. Les autres tombent verticalement dans les trous ; aucune bille aléatoire ne remplit le jardin. Récoltez tout le plateau.','Vous pouvez aussi choisir les cases dans les commandes, puis valider la chaîne avec le bouton ou Entrée. Échap efface ce tracé. Annulez un geste ou suivez un indice vérifié si des billes restent isolées.'],
    total:game=>game.level.total,remaining:game=>game.state.field.filter(v=>v!==null).length,
    controls(game,selected,hint){return `<div class="bounty-quotas">${game.level.quotas.map((n,color)=>n?`<div><span style="--color:${COLORS[color].hex}">${COLORS[color].mark}</span><strong>${game.state.collected[color]} / ${n}</strong><small>${COLORS[color].name}</small></div>`:'').join('')}</div><span class="pocket-reserve-label">UNE AUTRE FAÇON DE TRACER</span>${cells(game,'recolte',selected,hint)}<div class="bounty-actions"><button data-chain-commit ${selected?.length>=3?'':'disabled'}>Récolter ${selected?.length??0} billes ↗</button><button data-chain-clear>Effacer le tracé</button></div>`;},
  },
  dizaines:{name:'Dizaines',rules:dizainesRules,eyebrow:'DEUX PETITS NOMBRES, UN PEU DE LOGIQUE',title:'Deux nombres.<br> <em>Et ça fait dix.</em>',copy:'Réunissez les bonnes paires.<br>Laissez le bois respirer.',steps:[['Choisissez deux nombres.','Ils sont identiques, ou leur somme vaut dix. Ils doivent pouvoir se rejoindre sans chiffre entre les deux.'],['Regardez plus loin.','Les cases vides ouvrent des lignes, des colonnes et des diagonales. La fin d’une rangée rejoint le début de la suivante.']],note:'Choisissez deux nombres identiques, ou qui font dix',unit:'nombres à réunir',reserve:'Les petites paires.',reserveCopy:'Les espaces vides comptent : une paire éloignée peut devenir accessible après quelques retraits.',finish:'Tous les nombres se sont retrouvés.',delay:340,invalid:'Ces nombres ne font pas une paire libre : même nombre ou somme dix, sans chiffre sur le chemin.',
    rulesText:['Cliquez deux nombres identiques, ou deux nombres dont la somme vaut dix. Un chiffre sélectionné peut être désélectionné en cliquant dessus.','La paire doit être alignée horizontalement, verticalement ou en diagonale, avec uniquement des cases vides entre ses deux nombres.','Deux nombres consécutifs dans la lecture du plateau peuvent également se rejoindre : à la fin d’une rangée et au début de la suivante, y compris à travers les cases déjà vides.','Retirez tous les nombres. Les cases et rangées restent à leur place, pour garder le chemin lisible. Les 48 plateaux sont finis et disposent chacun d’une solution : aucun ajout de chiffres ni outil payant ne sont nécessaires. Annulation et indices restent disponibles.'],
    total:game=>game.level.total,remaining:game=>game.state.field.filter(v=>v!==null).length,
    controls(game,selected,hint){return `<div class="harvest-basket"><strong>${game.state.pairs}</strong><small>Paires réunies</small></div><span class="pocket-reserve-label">LES NOMBRES DU PLATEAU</span>${cells(game,'dizaines',selected,hint)}<p class="bounty-note">Même nombre, ou une somme de dix.<br>Horizontale · Verticale · Diagonale · Suite des rangées</p>`;},
  },
  mosaique:{name:'Mosaïque',rules:mosaiqueRules,eyebrow:'DE PETITES PIÈCES, UN GRAND TABLEAU',title:'Chaque pièce<br> <em>trouve sa place.</em>',copy:'Complétez les petites lignes.<br>Retrouvez un tableau vide.',steps:[['Posez une pièce.','Choisissez l’une des trois formes disponibles. Faites-la glisser dans les cases libres du tableau.'],['Préparez les lignes.','Une rangée ou une colonne complète disparaît. Posez les trois pièces avant de recevoir la réserve suivante.']],note:'Choisissez une pièce et posez-la dans les cases libres',unit:'cases à nettoyer',reserve:'Les pièces du tableau.',reserveCopy:'Trois pièces à la fois. Pensez aux espaces que la prochaine ligne fera apparaître.',finish:'Un tableau bien rangé.',delay:420,invalid:'Cette pièce ne tient pas ici : chaque carré doit rester dans une case libre.',
    rulesText:['Faites glisser une pièce depuis le bas du tableau. Vous pouvez aussi la sélectionner, puis cliquer sa case de départ sur le plateau ou dans les commandes.','Chaque carré doit tenir dans une case vide. Les pièces gardent leur orientation et ne peuvent ni dépasser le tableau ni recouvrir une case occupée.','Les rangées et colonnes complètes disparaissent ensemble. Un croisement n’est effacé qu’une fois. Les trois pièces disponibles peuvent être posées dans l’ordre de votre choix ; la réserve suivante arrive après les trois placements.','Utilisez toute la réserve et videz entièrement le tableau. Chaque réserve est finie et auditée. Un placement dans un détour reste possible : annulez si nécessaire. 1–3 choisit une pièce ; les flèches déplacent son aperçu et Espace la pose.'],
    total:game=>game.level.total,remaining:game=>game.level.total-game.state.cleared,
    controls(game,selected,hint){const active=activePieces(game.level,game.state);return `<div class="harvest-basket"><strong>${game.state.lines}</strong><small>Lignes dégagées · ${game.state.used.length} / ${game.level.pieces.length} pièces</small></div><div class="bounty-pieces">${active.map((p,n)=>`<button data-select="${p.id}" aria-pressed="${selected===p.id}" class="${hint?.action?.id===p.id?'hinted':''}" aria-label="Pièce ${p.id+1}, ${p.cells.length} carrés">${mosaicSvg(p)}<small>${n+1} · ${p.cells.length} carrés</small></button>`).join('')}</div><span class="pocket-reserve-label">LA CASE DE DÉPART DE LA PIÈCE</span><div class="bounty-cells bounty-origins" style="--cols:${game.level.size}">${game.state.field.map((v,id)=>`<button data-mosaic="${id}" ${selected===null||v!==null?'disabled':''} class="${hint?.action?.x===id%game.level.size&&hint?.action?.y===Math.floor(id/game.level.size)?'hinted':''}" aria-label="Poser à la case ${id+1}">${id+1}</button>`).join('')}</div><div class="bounty-reserve"><span class="pocket-reserve-label">LE PROCHAIN TRIO</span>${game.level.pieces.slice(Math.floor(game.state.used.length/3)*3+3,Math.floor(game.state.used.length/3)*3+6).map(mosaicSvg).join('')||'<small>Les dernières pièces sont sorties.</small>'}</div>`;},
  },
};
