import {COLORS} from './pocket-core.js';
import {etageresRules,GOODS} from './etageres-puzzle.js';
import {duosRules} from './duos-puzzle.js';
import {terriersRules} from './terriers-puzzle.js';
export const MOTIFS=['Feuille','Fleur','Oiseau','Soleil','Papillon','Cœur'];
const dot=color=>`<span class="color-dot" style="--color:${COLORS[color].hex}">${COLORS[color].mark}</span>`;
export const cabinetConfigs={
  etageres:{name:'Étagères',rules:etageresRules,eyebrow:'LES BONNES CHOSES VONT PAR TROIS',title:'Un petit<br> <em>garde-manger.</em>',copy:'Rangez les bonnes choses.<br>Faites de la place pour la suite.',steps:[['Déplacez une petite chose.','Faites glisser un produit vers une place vide, ou choisissez son départ et son arrivée.'],['Réunissez trois identiques.','Une tablette complète disparaît. Les produits cachés avancent lorsque tout le devant est vide.']],note:'Trois produits identiques sur une tablette · Déplacez vers une place vide',unit:'produits à ranger',reserve:'Les petites tablettes.',reserveCopy:'Les réserves attendent derrière. Libérez tout le devant d’une étagère pour les découvrir.',finish:'Tout est bien rangé.',delay:320,invalid:'Choisissez un produit et une place vide. Trois identiques remplissent une tablette.',
    total:g=>g.level.total,remaining:g=>g.level.total-g.state.collected.reduce((a,b)=>a+b,0),
    rulesText:['Déplacez un produit découvert vers une case vide. Faites-le glisser, ou cliquez son départ puis sa destination, sur le plateau ou dans les commandes.','Trois produits identiques occupent les trois cases d’une tablette : ils sont rangés et disparaissent ensemble. Deux produits ne suffisent pas.','La réserve d’une étagère avance seulement lorsque ses trois cases avant sont vides. Les petits motifs au fond annoncent la prochaine rangée.','Rangez tous les produits visibles et cachés. Les deux étagères libres vous donnent de la place pour préparer vos groupes. Annulation et indices vérifiés sont disponibles.'],
    controls(g,selected,hint){return `<div class="cabinet-shelves">${g.state.fronts.map((row,shelf)=>`<section><span>TABLETTE ${shelf+1} <small>${g.level.shelves[shelf].length-g.state.cursors[shelf]} en réserve</small></span><div>${row.map((color,cell)=>`<button data-goods="${shelf*3+cell}" aria-pressed="${selected?.shelf===shelf&&selected?.cell===cell}" class="${hint?.action?.from===shelf&&hint.action.slot===cell||hint?.action?.to===shelf&&hint.action.cell===cell?'hinted':''}" aria-label="Tablette ${shelf+1}, case ${cell+1}, ${color===null?'place vide':GOODS[color]}">${color===null?'<i>+</i>':`${dot(color)}<small>${GOODS[color]}</small>`}</button>`).join('')}</div></section>`).join('')}</div>`;},
  },
  duos:{name:'Duos',rules:duosRules,eyebrow:'DEUX PETITS MOTIFS, UN CHEMIN LIBRE',title:'Deux amis.<br> <em>Un détour.</em>',copy:'Retrouvez les petites paires.<br>Ouvrez leurs chemins.',steps:[['Choisissez deux motifs identiques.','Ils se rejoignent par un chemin vide. Deux virages au maximum, même autour du plateau.'],['Libérez les voisins.','Une paire retirée ouvre de nouvelles routes. Les pierres restent à leur place.']],note:'Deux motifs identiques · Un chemin vide avec deux virages au maximum',unit:'motifs à réunir',reserve:'Les petits duos.',reserveCopy:'Regardez aussi autour du tableau : un chemin peut passer par le bord extérieur.',finish:'Tous les amis réunis.',delay:350,invalid:'Ces motifs doivent être identiques, reliés par une route vide avec deux virages au maximum.',
    total:g=>g.level.total,remaining:g=>g.state.field.filter(v=>v!==null&&v>=0).length,
    rulesText:['Cliquez deux motifs identiques. Ils disparaissent si un chemin horizontal et vertical les relie à travers les cases vides.','Le chemin peut avoir deux virages au maximum, soit trois segments. La bordure extérieure du plateau est un passage libre.','Les autres motifs et les pierres bloquent la route. Retirer une paire libère ses deux cases : aucun nouveau motif ne les remplace.','Réunissez toutes les paires. Cliquez de nouveau le motif choisi pour le désélectionner. Le plateau et les commandes donnent accès aux mêmes cases ; H et Entrée permettent de suivre un indice vérifié.'],
    controls(g,selected,hint){return `<div class="harvest-basket"><strong>${g.state.pairs}</strong><small>Paires réunies</small></div><div class="cabinet-duos" style="--cols:${g.level.cols}">${g.state.field.map((color,id)=>`<button data-duo="${id}" ${color===null||color<0?'disabled':''} aria-pressed="${selected===id}" class="${hint?.action?.a===id||hint?.action?.b===id?'hinted':''}" aria-label="Case ${id+1}, ${color===null?'vide':color<0?'pierre':MOTIFS[color]}">${color===null?'·':color<0?'▧':dot(color)}</button>`).join('')}</div><p class="bounty-note">Deux virages au maximum.<br>Le bord extérieur reste libre.</p>`;},
  },
  terriers:{name:'Terriers',rules:terriersRules,eyebrow:'UN PEU DE TERRE, UN NOUVEAU CHEMIN',title:'Sous la terre,<br> <em>un passage.</em>',copy:'Creusez vos petits chemins.<br>Laissez les billes descendre.',steps:[['Creusez avec le doigt.','Dessinez un tunnel dans la terre. Les pierres restent solides, et votre pelle garde un peu de terre en réserve.'],['Laissez la gravité agir.','Libérez les billes. Chaque couleur doit rejoindre son terrier. Annulez un essai pour ajuster votre pente.']],note:'Creusez un tunnel · Libérez les billes avec le bouton ou E',unit:'billes à guider',reserve:'Les terriers du jardin.',reserveCopy:'Les billes suivent réellement la pente. Un tunnel trop étroit ou trop horizontal peut les retenir.',finish:'Tous les terriers heureux.',delay:0,invalid:'Creusez de la terre dans le jardin, sans dépasser la réserve de votre pelle. Les pierres ne se creusent pas.',
    total:g=>g.level.balls.length,remaining:g=>g.level.balls.length-(g.state.result?.caught??0),
    afterStatus:g=>g.state.result?(g.won?'Les billes ont retrouvé leur terrier.':`${g.state.result.caught} / ${g.level.balls.length} billes arrivées. Annulez l’essai pour ajuster le tunnel.`):null,
    rulesText:['Tracez un tunnel dans la terre avec la souris ou le doigt. Un geste devient un creusement lorsque vous relâchez ; un geste annulé ne change rien.','Les pierres restent solides. La réserve de la pelle compte uniquement les cellules de terre retirées : repasser dans un tunnel déjà ouvert ne consomme rien.','Cliquez Libérer les billes, ou appuyez sur E. Elles tombent par gravité et rencontrent les parois que vous avez réellement creusées. Chaque bille doit atteindre le terrier de sa couleur.','Annulez l’essai pour retravailler vos tunnels, ou effacez-les. Vous pouvez aussi tracer en ajoutant des coordonnées dans les commandes. Les indices proposent une route complète vérifiée, et peuvent demander d’effacer un détour.'],
    controls(g){return `<div class="cabinet-cups">${g.level.cups.map(c=>`<span>${dot(c.color)}<small>Terrier ${COLORS[c.color].name}</small></span>`).join('')}</div><div class="cabinet-earth"><span>LA RÉSERVE DE LA PELLE</span><strong>${g.level.budget-g.state.removed} / ${g.level.budget}</strong><progress max="${g.level.budget}" value="${g.level.budget-g.state.removed}"></progress></div><div class="bounty-actions"><button data-soil-run>Libérer les billes <kbd>E</kbd></button><button data-soil-clear>Effacer les tunnels</button></div><details class="cabinet-points"><summary>Tracer avec des coordonnées</summary><p>X : 56–584 · Y : 80–528</p><div><label>X <input id="soil-x" type="number" min="56" max="584" value="320"></label><label>Y <input id="soil-y" type="number" min="80" max="528" value="120"></label></div><div class="bounty-actions"><button data-soil-point>Ajouter ce point</button><button data-soil-place>Creuser le tracé</button><button data-soil-cancel>Annuler le tracé</button></div><p id="soil-point-status" role="status">Ajoutez au moins deux points.</p></details>`;},
  },
};
