import { COLORS } from './pocket-core.js';
import { alveolesRules } from './alveoles-puzzle.js';
import { potionsRules, settledBottle, pourAmount } from './potions-puzzle.js';
import { liaisonsRules, connectedPath } from './liaisons-puzzle.js';

export const stackSvg = stack => `<svg viewBox="0 0 90 75" aria-hidden="true">${stack.map((color,n)=>`<path d="M45 ${58-n*3-14} 73 ${58-n*3-7}V${58-n*3+7}L45 ${58-n*3+14} 17 ${58-n*3+7}V${58-n*3-7}Z" fill="${COLORS[color].hex}" stroke="#ffffff80"/>`).join('')}<text x="45" y="${60-stack.length*3}" text-anchor="middle" fill="${stack.at(-1)===7?'#fffaf0':'#244c42'}" font-size="14">${COLORS[stack.at(-1)]?.mark||'·'}</text></svg>`;
export const bottleSvg = bottle => `<svg viewBox="0 0 50 76" aria-hidden="true"><path d="M17 5v12L9 26v41q0 5 5 5h22q5 0 5-5V26l-8-9V5" fill="#fffdf580" stroke="#9caf95" stroke-width="2"/>${bottle.map((color,n)=>`<rect x="11" y="${57-n*11}" width="28" height="10" rx="2" fill="${COLORS[color].hex}"/><text x="25" y="${65-n*11}" text-anchor="middle" fill="${color===7?'#fffaf0':'#244c42'}" font-size="8">${COLORS[color].mark}</text>`).join('')}<path d="M15 5h20" stroke="#c4aa7c" stroke-width="4" stroke-linecap="round"/></svg>`;
const highlight = test => test ? 'hinted' : '';
export const gardenConfigs = {
  alveoles:{name:'Alvéoles',rules:alveolesRules,eyebrow:'DE PROCHE EN PROCHE, LES COULEURS SE REJOIGNENT',title:'Une pile.<br> <em>Et tout se rejoint.</em>',copy:'Posez les petits hexagones.<br>Laissez les couleurs se rassembler.',steps:[['Choisissez une pile.','Prenez la première pile d’une des trois files, puis posez-la sur une alvéole vide.'],['Faites naître les fusions.','Les dessus identiques reliés se rassemblent. Six tuiles de même couleur disparaissent et révèlent la suite.']],note:'Choisissez une pile, puis une alvéole vide',unit:'tuiles à réunir',reserve:'La prochaine petite pile.',reserveCopy:'Le symbole du dessus indique la première couleur à rassembler. Les couches du dessous comptent aussi.',finish:'La ruche respire.',delay:380,invalid:'Cette alvéole est occupée, ou cette file est vide.',
    rulesText:['Choisissez la première pile d’une des trois files, puis cliquez une alvéole vide pour la déposer. Les petites piles du plateau montrent toutes leurs couches.','Les couleurs identiques du dessus, reliées de proche en proche, rejoignent la nouvelle pile. Les couches couvertes restent à leur place.','Chaque groupe de six tuiles identiques disparaît. La couleur ainsi découverte peut déclencher une nouvelle fusion sur la pile que vous venez de poser.','Utilisez toutes les piles et videz le plateau. Un placement sans fusion est possible, mais occupe de la place. Vous pouvez toujours annuler et demander un indice.'],
    total:game=>game.level.stacks.flat().length+game.level.queues.flat(2).length,remaining:game=>game.level.stacks.flat().length+game.level.queues.flat(2).length-game.state.cleared,
    controls(game,selected,hint){return `<span class="pocket-reserve-label">LES TROIS FILES · CHOISISSEZ UNE PILE</span><div class="garden-queues">${game.level.queues.map((queue,q)=>`<div>${queue.slice(game.state.queues[q],game.state.queues[q]+3).map((stack,n)=>`<button data-select="${q}" class="${n?'buried':''} ${highlight(!n&&hint?.action?.q===q)}" ${n?'disabled':''} aria-pressed="${!n&&selected===q}" aria-label="File ${q+1}, ${stack.length} tuiles, dessus ${COLORS[stack.at(-1)].name}">${stackSvg(stack)}<small>${stack.length} tuiles</small></button>`).join('')||'<span>✓</span>'}</div>`).join('')}</div><span class="pocket-reserve-label">LES ALVÉOLES VIDES</span><div class="garden-cells">${game.state.stacks.map((stack,cell)=>!stack.length?`<button data-hex="${cell}" ${selected===null?'disabled':''} class="${highlight(hint?.action?.cell===cell)}" aria-label="Alvéole ${cell+1}, vide">${cell+1}</button>`:'').join('')}</div>`;},
  },
  potions:{name:'Potions',rules:potionsRules,eyebrow:'QUELQUES GOUTTES, UNE COULEUR À LA FOIS',title:'Une couleur.<br> <em>Une petite fiole.</em>',copy:'Versez doucement les couleurs.<br>Retrouvez les recettes du jardin.',steps:[['Prenez une fiole.','Choisissez la fiole à verser, puis celle qui recevra sa couleur du dessus.'],['Gardez de la place.','Une fiole vide accepte toute couleur. Sinon, seuls les dessus de même couleur se mélangent.']],note:'Choisissez une fiole à verser, puis une destination',unit:'couleurs à trier',reserve:'Les recettes du jardin.',reserveCopy:'Quatre doses de la même couleur font une recette. Le symbole accompagne chaque couleur.',finish:'Toutes les recettes retrouvées.',delay:360,invalid:'Les dessus doivent avoir la même couleur et la fiole d’arrivée doit avoir de la place.',
    rulesText:['Cliquez une fiole contenant du liquide, puis une autre pour y verser le groupe de couleur du dessus. Cliquez à nouveau la fiole choisie pour la désélectionner.','Une fiole contient quatre doses. Le versement transfère autant de doses identiques que la place disponible le permet.','Une fiole vide accepte toute couleur. Une fiole qui contient déjà du liquide accepte uniquement la couleur de son dessus.','Pour terminer, chaque couleur doit remplir une fiole entière. Les autres fioles restent vides. Les choix sans issue peuvent être annulés, sans limite de coups.'],
    total:game=>game.level.colors.length,remaining:game=>game.level.colors.length-game.state.bottles.filter(settledBottle).length,
    controls(game,selected,hint){return `<span class="pocket-reserve-label">CHOISISSEZ LA SOURCE, PUIS L’ARRIVÉE</span><div class="garden-bottles">${game.state.bottles.map((b,id)=>`<button data-bottle="${id}" aria-pressed="${selected===id}" class="${highlight(hint?.action?.from===id||hint?.action?.to===id)}" aria-label="Fiole ${id+1}, ${b.length?b.map(c=>COLORS[c].name).join(', ')+', de bas en haut':'vide'}${selected!==null&&pourAmount(game.state,selected,id)?', destination possible':''}">${bottleSvg(b)}<small>${id+1} ${settledBottle(b)?'✓':''}</small></button>`).join('')}</div><span class="pocket-reserve-label">${selected===null?'AUCUNE FIOLE CHOISIE':`FIOLE ${selected+1} À VERSER`}</span><div class="pocket-trays">${game.level.colors.map(color=>`<span class="pocket-tray"><span class="color-dot" style="--color:${COLORS[color].hex};${color===7?'color:#fffaf0':''}">${COLORS[color].mark}</span><small>${game.state.bottles.some(b=>settledBottle(b)&&b[0]===color)?'✓':'4 doses'}</small></span>`).join('')}</div>`;},
  },
  liaisons:{name:'Liaisons',rules:liaisonsRules,eyebrow:'CHAQUE PETIT CHEMIN TROUVE SON AUTRE BOUT',title:'Deux points.<br> <em>Un joli détour.</em>',copy:'Reliez les couleurs.<br>Faites une place à chaque chemin.',steps:[['Partez d’un point.','Faites glisser le doigt ou la souris jusqu’à son partenaire de même couleur.'],['Remplissez le jardin.','Les chemins restent sur les cases et ne se croisent pas. Aucune case ne doit rester vide.']],note:'Tracez entre les points de même couleur, puis remplissez toutes les cases',unit:'cases à parcourir',reserve:'Les petits chemins.',reserveCopy:'Choisissez un point puis les cases voisines. Les boutons et les flèches du clavier permettent aussi de tracer.',finish:'Tous les chemins se rejoignent.',delay:0,invalid:'Ce chemin croise une autre couleur, un point voisin ou saute une case.',
    rulesText:['Partez d’un point coloré et dessinez jusqu’à l’autre point de sa couleur, de case voisine en case voisine, horizontalement ou verticalement.','Les chemins ne se croisent jamais et ne peuvent pas passer par le point d’une autre couleur. Toutes les cases doivent être parcourues pour terminer.','Repartir d’un point redessine sa couleur. Pendant le tracé, revenir sur une case de votre chemin efface la suite. Un trait est un seul coup annulable.','Vous pouvez aussi choisir une couleur dans les commandes puis cliquer les cases voisines, ou utiliser les flèches du clavier. Un indice peut proposer d’effacer un détour avant de tracer une route vérifiée.'],
    total:game=>game.level.size**2,remaining:game=>game.level.size**2-game.state.paths.flat().length,
    controls(game,selected,hint){const level=game.level;return `<div class="garden-links">${level.colors.map((color,id)=>`<button data-select="${id}" aria-pressed="${selected===id}" class="${highlight(hint?.action?.color===id)}" aria-label="Choisir le chemin ${COLORS[color].name}"><span class="color-dot" style="--color:${COLORS[color].hex};${color===7?'color:#fffaf0':''}">${COLORS[color].mark}</span><small>${COLORS[color].name} ${connectedPath(level,game.state.paths[id],id)?'✓':''}</small></button>`).join('')}</div><span class="pocket-reserve-label">LES CASES · POINT PUIS CASES VOISINES</span><div class="garden-grid" style="--size:${level.size}">${Array.from({length:level.size**2},(_,cell)=>{const pair=level.pairs.findIndex(p=>p.includes(cell)),path=game.state.paths.findIndex(p=>p.includes(cell)),color=pair>=0?pair:path;return `<button data-cell="${cell}" style="${color>=0?`background:${COLORS[level.colors[color]].hex};${level.colors[color]===7?'color:#fffaf0':''}`:''}" aria-label="Case ${cell%level.size+1}, ${Math.floor(cell/level.size)+1}${pair>=0?`, point ${COLORS[level.colors[pair]].name}`:path>=0?`, chemin ${COLORS[level.colors[path]].name}`:', libre'}">${pair>=0?COLORS[level.colors[pair]].mark:cell+1}</button>`;}).join('')}</div><button class="garden-clear" data-clear ${selected===null||!game.state.paths[selected].length?'disabled':''}>Effacer le chemin choisi</button>`;},
  },
};
