import { COLORS } from './pocket-core.js';
import { eclusesRules } from './ecluses-puzzle.js';
import { dunesRules, sandWidth } from './dunes-puzzle.js';
import { fringaleRules, holeRadius, itemNames } from './fringale-puzzle.js';
export const sandPieceSvg=piece=>`<svg viewBox="0 0 70 52" aria-hidden="true">${piece.shape.map(([x,y])=>`<rect x="${9+x*16}" y="${8+y*16}" width="15" height="15" rx="3" fill="${COLORS[piece.color].hex}" stroke="#ffffff90"/><path d="M${12+x*16} ${12+y*16}h8" stroke="#ffffff90"/>`).join('')}<text x="61" y="45" text-anchor="middle" font-size="10" fill="${piece.color===7?'#456052':'#6f8567'}">${COLORS[piece.color].mark}</text></svg>`;
export const harvestConfigs={
  ecluses:{name:'Écluses',rules:eclusesRules,eyebrow:'LE BON MÉLANGE, AU BON MOMENT',title:'Une vanne.<br> <em>Et tout s’écoule.</em>',copy:'Mélangez les petites billes.<br>Ouvrez les bons passages.',steps:[['Retirez une goupille.','Les billes descendent vers le prochain bassin, puis continuent à travers les passages déjà ouverts.'],['Colorez avant le départ.','Une bille grise prend la couleur de ses voisines. Toutes doivent arriver colorées dans le panier.']],note:'Retirez une goupille · Colorez les billes avant leur départ',unit:'billes à recueillir',reserve:'Les petits passages.',reserveCopy:'Les ouvertures restent libres. Réunissez les billes grises et les couleurs avant d’ouvrir le dernier bassin.',finish:'Toutes les billes au jardin.',delay:450,invalid:'Cette goupille est déjà retirée, ou des billes se sont perdues. Annulez pour réessayer.',
    rulesText:['Cliquez une goupille dans le jardin ou dans les commandes. Elle disparaît et laisse les billes de sa réserve tomber dans le bassin suivant.','Une bille grise devient colorée au contact d’une bille de couleur, dans le même bassin. Les billes continuent automatiquement à travers toutes les vannes déjà ouvertes.','Les billes grises qui arrivent directement au panier sont perdues. Une bombe détruit les billes qu’elle rencontre : les chapitres suivants demandent aussi d’éviter sa goupille.','Toutes les billes doivent rejoindre le panier, colorées et intactes. Une erreur se corrige avec Annuler ; chaque indice vérifie une suite qui termine tout le plateau.'],
    total:game=>game.level.total,remaining:game=>game.level.total-game.state.collected.length,
    afterStatus:game=>game.state.lost.length?'Des billes se sont perdues. Annulez la dernière ouverture pour réessayer.':null,
    controls(game,selected,hint){return `<div class="harvest-basket"><strong>${game.state.collected.length} / ${game.level.total}</strong><small>Billes au panier</small>${game.state.lost.length?`<p>${game.state.lost.length} perdues · Annulez pour réessayer</p>`:''}</div><span class="pocket-reserve-label">LES GOUPILLES À RETIRER</span><div class="harvest-gates">${game.level.pins.map((pin,id)=>`<button data-gate="${id}" ${game.state.opened.includes(id)||game.state.lost.length?'disabled':''} class="${hint?.action===id?'hinted':''}" aria-label="Goupille ${id+1}, ${pin.name}"><span>${game.state.opened.includes(id)?'✓':'⊣'}</span><strong>${id+1}</strong><small>${pin.name}</small></button>`).join('')}</div>`;},
  },
  dunes:{name:'Dunes',rules:dunesRules,eyebrow:'DE PETITS GRAINS, DE GRANDES CASCADES',title:'Un peu de sable.<br> <em>Une couleur de moins.</em>',copy:'Posez vos petits blocs.<br>Regardez les couleurs se rejoindre.',steps:[['Choisissez un bloc.','Prenez le premier d’une des trois files et choisissez sa colonne de chute dans le bac.'],['Reliez les deux bords.','Le bloc devient du sable. Une couleur qui rejoint les deux côtés disparaît et fait descendre les autres grains.']],note:'Choisissez un bloc, puis sa colonne dans le bac',unit:'bandes à dégager',reserve:'Les couleurs à venir.',reserveCopy:'Le sable glisse autour des pierres. Préparez un passage d’un bord à l’autre sans boucher le haut du bac.',finish:'Un dernier souffle de sable.',delay:0,invalid:'Le bloc ne tient pas à cet endroit, ou cette file est vide.',
    rulesText:['Choisissez le premier bloc d’une des trois files. Cliquez dans le bac pour définir sa colonne, ou choisissez une position dans les commandes. Le bloc se dépose par le haut.','Chaque case du bloc se transforme en petits grains. Ils tombent et glissent en diagonale, en contournant les grains voisins et les pierres.','Une zone de sable de la même couleur qui relie le bord gauche au bord droit disparaît entièrement. Elle peut être courbe : aucun besoin de faire une ligne droite.','Dégagez le nombre de bandes demandé avec votre réserve. Les chapitres suivants ajoutent davantage de couleurs, un bac plus large et des pierres. Annulation, indices et reprise restent disponibles.'],
    total:game=>game.level.goal,remaining:game=>Math.max(0,game.level.goal-game.state.bursts),
    controls(game,selected,hint){const piece=selected===null?null:game.level.queues[selected]?.[game.state.queues[selected]];return `<div class="harvest-basket"><strong>${game.state.bursts} / ${game.level.goal}</strong><small>Bandes de sable dégagées</small></div><div class="harvest-queues">${game.level.queues.map((queue,q)=>`<div><span class="eyebrow">0${q+1}</span>${queue.slice(game.state.queues[q],game.state.queues[q]+3).map((p,n)=>`<button data-select="${q}" aria-pressed="${!n&&selected===q}" ${n?'disabled':''} class="${!n&&hint?.action?.q===q?'hinted':''}" aria-label="File ${q+1}, bloc ${COLORS[p.color].name}">${sandPieceSvg(p)}<small>${n?'En réserve':COLORS[p.color].name}</small></button>`).join('')||'<small>✓</small>'}</div>`).join('')}</div><span class="pocket-reserve-label">LA POSITION DU BLOC · FLÈCHES PUIS ESPACE</span><div class="harvest-columns">${piece?Array.from({length:game.level.width-sandWidth(piece)+1},(_,x)=>`<button data-sand-x="${x}" class="${hint?.action?.x===x?'hinted':''}" aria-label="Déposer à la colonne ${x+1}">${x+1}</button>`).join(''):'<p>Choisissez d’abord un bloc.</p>'}</div>`;},
  },
  fringale:{name:'Fringale',rules:fringaleRules,eyebrow:'UNE PETITE FAIM, UN GRAND JARDIN',title:'Encore<br> <em>une petite bouchée.</em>',copy:'Un trou qui grandit.<br>Un jardin plein de bonnes choses.',steps:[['Commencez petit.','Guidez le trou sous les baies. Chaque bouchée l’agrandit et lui permet d’avaler des objets plus grands.'],['Pensez au chemin du retour.','Les haies barrent les passages. Un trou devenu grand ne peut plus emprunter une allée étroite.']],note:'Guidez le trou · Avalez les petites choses pour grandir',unit:'choses à avaler',reserve:'Le prochain petit goûter.',reserveCopy:'Faites glisser le trou ou choisissez un objet accessible. Récoltez les petits coins avant de devenir trop grand.',finish:'Un jardin bien rangé.',delay:540,invalid:'Cet objet est trop grand ou inaccessible. Choisissez une petite bouchée ou annulez un détour.',
    rulesText:['Faites glisser le trou dans le jardin. Un objet disparaît lorsqu’il tient entièrement dans l’ouverture. Commencez par les petites baies pour agrandir le trou.','Les haies et les limites du jardin empêchent de passer. Un trou qui grandit peut devenir trop large pour une allée : pensez à vider les petites cours avant de sortir.','Vous pouvez aussi cliquer un objet ou son bouton. Le trou cherche alors un chemin autour des haies. Les flèches du clavier permettent de se déplacer.','Avalez tous les objets pour terminer. Un geste entier peut être annulé, avec la taille précédente et tous ses objets. Un indice vérifie une tournée complète ; si elle n’est plus trouvée, il propose d’annuler.'],
    total:game=>game.level.items.length,remaining:game=>game.level.items.length-game.state.collected.length,
    controls(game,selected,hint){const radius=holeRadius(game.state.mass);return `<div class="harvest-appetite"><span style="--hole:${Math.min(80,radius*2)}px"></span><strong>${radius<22?'Une petite faim':radius<32?'Un bon appétit':'Une grande fringale'}</strong><small>${game.state.collected.length} / ${game.level.items.length} bouchées</small></div><span class="pocket-reserve-label">LES BONNES CHOSES DU JARDIN</span><div class="harvest-foods">${game.level.items.filter(p=>!game.state.collected.includes(p.id)).map(p=>`<button data-food="${p.id}" ${p.r+3>radius?'disabled':''} class="${hint?.action?.id===p.id?'hinted':''}" aria-label="${itemNames[p.kind]} ${p.id+1}${p.r+3>radius?', encore trop grand':''}"><span style="--color:${COLORS[p.color].hex}">${p.kind==='berry'?'●':p.kind==='apple'?'◆':p.kind==='cake'?'▰':p.kind==='melon'?'◉':'✿'}</span><strong>${p.id+1}</strong><small>${p.r+3>radius?'Trop grand':itemNames[p.kind]}</small></button>`).join('')}</div><div class="pocket-pad"><button data-hole-dir="0,-1" aria-label="Monter le trou">↑</button><button data-hole-dir="-1,0" aria-label="Déplacer le trou à gauche">←</button><button data-hole-dir="0,1" aria-label="Descendre le trou">↓</button><button data-hole-dir="1,0" aria-label="Déplacer le trou à droite">→</button></div>`;},
  },
};
