import './home-style.css';
import { atelierPreview, bobinesPreview, escapadePreview } from './pocket-previews.js';
import { passagesPreview, voyagePreview, carrouselPreview, broderiePreview } from './suite-previews.js';
import { alveolesPreview, potionsPreview, liaisonsPreview } from './garden-previews.js';
import { noeudsPreview, gouttesPreview } from './physics-previews.js';
import { eclusesPreview, dunesPreview, fringalePreview } from './harvest-previews.js';
import { recoltePreview, dizainesPreview, mosaiquePreview } from './bounty-previews.js';

import { etageresPreview, duosPreview, terriersPreview } from './cabinet-previews.js';

import { ruisseauxPreview, balancierPreview, geleesPreview } from './spring-previews.js';
const base = import.meta.env.BASE_URL;
const cubePreview = `<svg viewBox="0 0 360 260" fill="none" aria-hidden="true"><ellipse cx="180" cy="226" rx="80" ry="11" fill="#345344" opacity=".07"/><circle cx="180" cy="132" r="105" stroke="#ced9c6"/><circle cx="270" cy="78" r="4" fill="#9aaa8d"/><path d="m180 42 91 49v101l-91 50-91-50V91Z" fill="#eef0df"/><path d="m180 42 91 49-91 50-91-50Z" fill="#fdfbee"/><path d="m180 141 91-50v101l-91 50Z" fill="#e0e6d2"/><path d="m89 91 91 50v101l-91-50Z" fill="#eceddb"/><g stroke="#d1d7c2" stroke-width="1"><path d="m119 75 91 49m-61-65 91 49M119 108l91-49m-61 66 91-50M119 108v101m31-84v101m60-101v101m31-117v100M89 125l91 50 91-50m-182 33 91 50 91-50"/></g><g stroke="#759785" stroke-width="7" stroke-linecap="round" stroke-linejoin="round"><path d="m137 89 28 15 30-16 29 16m-13-1 13 1-2-12"/><path d="m105 128 30 16v39l30 17m-11-13 11 13-12 0"/><path d="m195 182 28-16v-34l31-17m-12 1 12-1-2 13"/></g></svg>`;
const imagePreview = `<svg viewBox="0 0 360 260" aria-hidden="true"><defs><clipPath id="picture-preview-frame"><rect x="64" y="42" width="232" height="180" rx="8"/></clipPath></defs><rect x="57" y="35" width="246" height="194" rx="13" fill="#fffdf5" stroke="#d9dac7"/><g clip-path="url(#picture-preview-frame)"><rect x="64" y="42" width="232" height="180" fill="#d1e4e5"/><circle cx="238" cy="80" r="22" fill="#f1dca3"/><path d="m64 170 77-79 62 62 48-41 45 39v72H64Z" fill="#95b3a0"/><path d="m64 205 78-57 62 50 44-37 48 21v40H64Z" fill="#688f7d"/><path d="m64 222 70-14 42 5 72-14 48 18v15H64Z" fill="#ddc8a0"/><g fill="none" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"><path stroke="#799dac" d="M80 66h65v20h42m-9-8 9 8-9 8M85 99v21h26v16H80m9-8-9 8 9 8"/><path stroke="#fcf2ce" d="M228 65h37v22h-35v16h45m-8-8 8 8-8 8"/><path stroke="#507867" d="M164 109v39h28v22h-32m8-8-8 8 8 8M280 132v38h-48v19m-8-8 8 8 8-8"/><path stroke="#d6e4cf" d="M108 155v25h-23v21h40m-8-8 8 8-8 8"/><path stroke="#a58665" d="M175 212h60m-8-8 8 8-8 8"/></g></g><rect x="244" y="203" width="69" height="29" rx="14" fill="#fdfcf4" stroke="#d9dac7"/><text x="278" y="221" fill="#697d6a" text-anchor="middle" font-size="10" font-family="Segoe UI, sans-serif">Votre image</text></svg>`;
// An original pixel fox and tiny workers, drawn as lightweight native SVG.
const fox = Array.from({ length: 100 }, (_, id) => {
  const x = id % 10, y = Math.floor(id / 10), d = Math.abs(x - 4.5);
  let c = '#b7cbd6';
  if ((y >= 1 && y <= 3 && (x === 1 || x === 2 || x === 7 || x === 8)) || y >= 3 && y <= 8 && d <= (y < 7 ? 3.5 : 9 - y)) c = '#df896c';
  if (y === 5 && (x === 2 || x === 7) || y === 8 && (x === 4 || x === 5)) c = '#3a514a';
  if (y === 7 && d <= 1.5 || y === 6 && (x === 1 || x === 8)) c = '#f6e6bc';
  return `<rect x="${110 + x * 14}" y="${27 + y * 14}" width="13" height="13" rx="1.5" fill="${c}"/>`;
}).join('');
const ant = (x, y, r = 0) => `<g transform="translate(${x} ${y}) rotate(${r})" fill="#577364" stroke="#577364" stroke-width="1.2"><ellipse cy="4" rx="3" ry="4"/><circle cy="-2" r="2"/><circle cy="-6" r="2.8"/><path d="m-1-8-2-4m4 4 2-4M-2 0l-5-3m5 4-6 2m6 1-5 4M2 0l5-3M2 1l6 2m-6 1 5 4" fill="none"/></g>`;
const colonyPreview = `<svg viewBox="0 0 360 260" aria-hidden="true"><rect x="102" y="19" width="156" height="156" rx="9" fill="#e2d7bb"/>${fox}<ellipse cx="180" cy="206" rx="13" ry="6" fill="#7b775e"/><ellipse cx="200" cy="208" rx="13" ry="6" fill="#d9c6a4"/>${ant(155, 185, -30)}${ant(214, 183, 25)}${ant(139, 209, 20)}${ant(225, 210, -40)}${['#97b896', '#e6816c', '#f4dfaa', '#84b9ce', '#77628e'].map((c, i) => `<rect x="${104 + i * 32}" y="230" width="25" height="18" rx="4" fill="${c}"/><text x="${116 + i * 32}" y="243" text-anchor="middle" fill="${i === 2 ? '#496357' : '#fffdf5'}" font-size="9" font-family="Segoe UI, sans-serif">${[24, 16, 30, 12, 20][i]}</text>`).join('')}</svg>`;
const games = [
  { file: 'cube.html', number: '01', label: 'The cube', tag: 'PUZZLE 3D', title: 'Un peu de perspective.', copy: 'Tournez le cube. Démêlez ses chemins. Laissez les flèches s’échapper, une à une.', preview: cubePreview, className: 'cube', details: '28 premiers puzzles · Voyage infini' },
  { file: 'image.html', number: '02', label: 'Picture puzzles', tag: 'VOS IMAGES, EN 2D', title: 'Vos souvenirs en jeu.', copy: 'Une photo, une illustration, un souvenir. Transformez vos images en chemins à démêler.', preview: imagePreview, className: 'pictures', details: 'Importez une image · Créez votre puzzle' },
  { file: 'colony.html', number: '03', label: 'Colony', tag: 'UNE COLONIE EN 3D', title: 'Un petit monde en marche.', copy: 'Choisissez les bonnes couleurs. Faites travailler vos fourmis. Gardez une place pour la suite.', preview: colonyPreview, className: 'colony', details: 'Cinq emplacements · Des fourmis à guider' },
  { file: 'atelier.html', number: '04', label: 'Atelier', tag: 'UN PETIT ATELIER EN 3D', title: 'Un tour. Et tout se libère.', copy: 'Retirez les vis. Triez leurs couleurs. Découvrez ce que cachent les petites planches.', preview: atelierPreview, className: 'atelier', details: '48 puzzles · Des pièces à libérer' },
  { file: 'bobines.html', number: '05', label: 'Bobines', tag: 'DES COULEURS À DÉROULER', title: 'Un fil, puis un autre.', copy: 'Choisissez vos bobines. Laissez les fils s’enrouler. Démêlez les couleurs, un nœud à la fois.', preview: bobinesPreview, className: 'bobines', details: '48 puzzles · Trois places à gérer' },
  { file: 'escapade.html', number: '06', label: 'Escapade', tag: 'DE PETITS VOISINS À GUIDER', title: 'Chacun son chemin.', copy: 'Un jardin plein de voisins. Faites glisser leurs petits corps jusqu’aux maisons de leur couleur.', preview: escapadePreview, className: 'escapade', details: '48 puzzles · Des chemins à trouver' },
  { file: 'passages.html', number: '07', label: 'Passages', tag: 'DES BLOCS À FAIRE GLISSER', title: 'Une porte, un passage.', copy: 'Poussez les couleurs. Faites de la place. Trouvez la bonne porte pour chaque petit bloc.', preview: passagesPreview, className: 'passages', details: '48 puzzles · Des portes à ouvrir' },
  { file: 'voyage.html', number: '08', label: 'Voyage', tag: 'TOUT LE MONDE À BORD', title: 'Les petits départs.', copy: 'Libérez les allées. Faites monter les bonnes couleurs. Gardez une place sur le banc.', preview: voyagePreview, className: 'voyage', details: '48 puzzles · Cinq places d’attente' },
  { file: 'carrousel.html', number: '09', label: 'Carrousel', tag: 'UN PETIT TOUR DE COULEURS', title: 'Et ça tourne encore.', copy: 'Lancez vos petits tireurs sur la piste. Faites disparaître les pixels, une couleur à la fois.', preview: carrouselPreview, className: 'carrousel', details: '48 puzzles · Des tireurs à relancer' },
  { file: 'broderie.html', number: '10', label: 'Broderie', tag: 'DE PETITS TABLEAUX À BRODER', title: 'Trois fils, une image.', copy: 'Réunissez les bobines de même couleur. Regardez votre tableau se broder, point après point.', preview: broderiePreview, className: 'broderie', details: '48 puzzles · Sept petites places' },
  { file: 'alveoles.html', number: '11', label: 'Alvéoles', tag: 'DES PILES QUI SE REJOIGNENT', title: 'De proche en proche.', copy: 'Posez les petits hexagones. Réunissez les couleurs du dessus. Faites naître une cascade de fusions.', preview: alveolesPreview, className: 'alveoles', details: '48 puzzles · Des couleurs à réunir' },
  { file: 'potions.html', number: '12', label: 'Potions', tag: 'LES RECETTES DU JARDIN', title: 'Une couleur, une fiole.', copy: 'Versez doucement les couleurs. Gardez un peu de place. Retrouvez toutes les petites recettes.', preview: potionsPreview, className: 'potions', details: '48 puzzles · Des couleurs à transvaser' },
  { file: 'liaisons.html', number: '13', label: 'Liaisons', tag: 'CHAQUE CHEMIN COMPTE', title: 'Deux points, un détour.', copy: 'Reliez les points de même couleur. Remplissez le jardin de chemins, sans jamais les croiser.', preview: liaisonsPreview, className: 'liaisons', details: '48 puzzles · Un jardin à parcourir' },
  { file: 'noeuds.html', number: '14', label: 'Nœuds', tag: 'UN PETIT MÉLI-MÉLO', title: 'Les fils se détendent.', copy: 'Déplacez les petites attaches. Séparez les cordes. Retrouvez un jardin sans nœuds.', preview: noeudsPreview, className: 'noeuds', details: '48 puzzles · Des cordes à démêler' },
  { file: 'gouttes.html', number: '15', label: 'Gouttes', tag: 'LE CHEMIN DE L’EAU', title: 'Un verre heureux.', copy: 'Dessinez vos petits ponts. Laissez couler les gouttes. Regardez la gravité faire le reste.', preview: gouttesPreview, className: 'gouttes', details: '48 puzzles · Des rampes à dessiner' },
  { file: 'ecluses.html', number: '16', label: 'Écluses', tag: 'LE BON MÉLANGE', title: 'Une vanne, un passage.', copy: 'Réunissez les billes et leurs couleurs. Retirez les goupilles. Préparez le dernier départ.', preview: eclusesPreview, className: 'ecluses', details: '48 puzzles · Des billes à colorer' },
  { file: 'dunes.html', number: '17', label: 'Dunes', tag: 'DE PETITS GRAINS DE COULEUR', title: 'De bord en bord.', copy: 'Posez vos petits blocs. Laissez le sable se rejoindre. Préparez les prochaines cascades.', preview: dunesPreview, className: 'dunes', details: '48 puzzles · Des cascades de sable' },
  { file: 'fringale.html', number: '18', label: 'Fringale', tag: 'UNE PETITE BOUCHÉE DE PLUS', title: 'Un jardin gourmand.', copy: 'Guidez le trou vers les petites douceurs. Grandissez, puis récoltez les bonnes choses du jardin.', preview: fringalePreview, className: 'fringale', details: '48 puzzles · Un trou qui grandit' },
  { file: 'recolte.html', number: '19', label: 'Récolte', tag: 'DES CHAÎNES À RÉCOLTER', title: 'Tout un panier de couleurs.', copy: 'Reliez les petites billes. Récoltez vos couleurs. Préparez les chemins que leur chute fait apparaître.', preview: recoltePreview, className: 'recolte', details: '48 puzzles · Des chaînes colorées' },
  { file: 'dizaines.html', number: '20', label: 'Dizaines', tag: 'DEUX NOMBRES FONT LA PAIRE', title: 'Un peu de logique.', copy: 'Trouvez les nombres qui se rejoignent. Réunissez les paires. Laissez les petites tuiles respirer.', preview: dizainesPreview, className: 'dizaines', details: '48 puzzles · Des paires de nombres' },
  { file: 'mosaique.html', number: '21', label: 'Mosaïque', tag: 'LES PIÈCES DU TABLEAU', title: 'Chaque pièce compte.', copy: 'Posez les formes. Complétez les lignes. Videz votre tableau, une petite pièce à la fois.', preview: mosaiquePreview, className: 'mosaique', details: '48 puzzles · Des lignes à nettoyer' },
  { file: 'etageres.html', number: '22', label: 'Étagères', tag: 'LES BONNES CHOSES PAR TROIS', title: 'Un petit garde-manger.', copy: 'Déplacez les produits. Réunissez trois identiques. Découvrez les réserves cachées derrière les tablettes.', preview: etageresPreview, className: 'etageres', details: '48 puzzles · Des étagères à ranger' },
  { file: 'duos.html', number: '23', label: 'Duos', tag: 'DEUX AMIS, UN CHEMIN LIBRE', title: 'Un petit détour.', copy: 'Retrouvez les motifs identiques. Reliez-les à travers les espaces vides, avec deux virages au maximum.', preview: duosPreview, className: 'duos', details: '48 puzzles · Des paires à relier' },
  { file: 'terriers.html', number: '24', label: 'Terriers', tag: 'UN PASSAGE SOUS LA TERRE', title: 'Sous les racines.', copy: 'Creusez les petits tunnels. Laissez la gravité guider chaque bille jusqu’au terrier de sa couleur.', preview: terriersPreview, className: 'terriers', details: '48 puzzles · Des tunnels à creuser' },
  { file:'ruisseaux.html', number:'25', label:'Ruisseaux', tag:'DE DALLE EN DALLE', title:'Un jardin bien arrosé.', copy:'Faites glisser les petits canaux. Reliez la source au bassin. Arrosez chaque fleur en chemin.', preview:ruisseauxPreview, className:'ruisseaux', details:'48 puzzles · Des canaux à faire glisser' },
  { file:'balancier.html', number:'26', label:'Balancier', tag:'UN FIL, UN ÉLAN', title:'Une baie, un joli vol.', copy:'Laissez la baie se balancer. Coupez les bons fils au bon moment. Récoltez les pétales et retrouvez le panier.', preview:balancierPreview, className:'balancier', details:'48 puzzles · Des cordes à couper' },
  { file:'gelees.html', number:'27', label:'Gelées', tag:'LES FORMES DU PETIT POT', title:'Un petit pot bien rempli.', copy:'Tournez les formes. Laissez tomber les petites gelées. Gardez les passages nécessaires pour la suite.', preview:geleesPreview, className:'gelees', details:'48 puzzles · Des formes à empiler' },
];
document.querySelector('#app').innerHTML = `<header class="home-header"><a href="${base}" class="home-brand"><span>↗</span><strong>cube cube cube<small>A small escape.</small></strong></a><span class="home-header-note">Vingt-sept petits mondes. Une vraie pause. <i>✳</i></span></header><main class="home-main"><section class="home-intro"><span class="eyebrow"><span class="tiny-line"></span>UNE PETITE PARENTHÈSE</span><h1>À quoi on joue<br><em>aujourd’hui ?</em></h1><p>Des chemins à trouver, des couleurs à récolter.<br>Choisissez votre petit monde et prenez votre temps.</p></section><section class="home-games" aria-label="Choisir un jeu">${games.map(g => `<article class="game-card ${g.className}"><a href="${base}${g.file}" class="game-preview" tabindex="-1" aria-hidden="true">${g.preview}<span class="game-number">${g.number}</span><span class="game-tag">${g.tag}</span></a><div class="game-card-content"><span class="game-label">${g.label}</span><h2>${g.title}</h2><p>${g.copy}</p><div class="game-card-foot"><span>${g.details}</span><a href="${base}${g.file}" aria-label="Jouer à ${g.label}">Jouer <span aria-hidden="true">↗</span></a></div></div></article>`).join('')}</section><div class="home-promise"><span>✳ Pas de chrono.</span><span>Pas de compte.</span><span>Votre progression reste ici.</span></div></main><footer class="home-footer"><span>Un petit jeu. Un peu d’air.</span><span>Fait pour jouer à votre rythme.</span></footer>`;
