import {plisRules,paperTop} from './plis-puzzle.js';
import {luciolesRules,lightTrace} from './lucioles-puzzle.js';
import {aiguillagesRules} from './aiguillages-puzzle.js';
import {COLORS} from './pocket-core.js';
export const lanternConfigs={
  plis:{name:'Plis',rules:plisRules,eyebrow:'UNE FEUILLE, UN PETIT PORTRAIT',title:'Sous les plis,<br> <em>une image.</em>',copy:'Retournez les coins de papier.<br>Retrouvez le petit dessin.',steps:[['Choisissez votre pli.','Faites glisser une partie de la feuille par-dessus sa voisine, ou choisissez une ligne dans la liste.'],['Retrouvez le dessin.','Chaque pli retourne le papier et ses couches. Leur ordre change ce qui reste visible.']],note:'Faites glisser le papier à travers une ligne · Retrouvez le petit dessin',unit:'détails à retrouver',reserve:'Les prochains plis.',reserveCopy:'La feuille entière située d’un côté de la ligne se retourne. Les plis disponibles sont indiqués ici.',finish:'Un portrait dans le papier.',delay:460,invalid:'Ce pli ne rejoint pas la feuille, ou sort du petit atelier.',total:()=>17,remaining:g=>g.level.target.filter((v,id)=>v!==null&&paperTop(g.level,g.state.field[id])!==v).length+Number(g.state.field.some((s,id)=>s.length&&g.level.target[id]===null)),
    rulesText:['Faites glisser un carré du papier jusqu’à son reflet de l’autre côté d’une ligne. La ligne se place à mi-chemin. Le bouton correspondant permet aussi de plier sans glisser.','Tout le papier du côté choisi se retourne, y compris les couches déjà empilées. Le recto devient verso, et l’ordre des couches se renverse.','Le pli doit toucher une autre partie de la feuille et rester dans l’atelier. L’image du petit modèle doit apparaître entièrement, sans papier dépassant de son cadre.','Le bon ordre compte : un morceau peut cacher le dessin qu’un autre révélait. Annulez chaque pli, recommencez ou suivez une suite complète vérifiée.'],
    controls(g,selected,hint){const options=plisRules.actions(g.level,g.state);return `<div class="lantern-folds">${options.map((a,n)=>`<button data-fold="${n}" class="${JSON.stringify(hint?.action)===JSON.stringify(a)?'hinted':''}" aria-label="Plier ${a.side<0?(a.axis==='x'?'la gauche':'le haut'):(a.axis==='x'?'la droite':'le bas')}, ligne ${a.line}"><span>${a.axis==='x'?(a.side<0?'→':'←'):(a.side<0?'↓':'↑')}</span><strong>${a.axis==='x'?'Verticale':'Horizontale'} ${a.line}</strong><small>${a.side<0?(a.axis==='x'?'Gauche':'Haut'):(a.axis==='x'?'Droite':'Bas')}</small></button>`).join('')}</div><p class="bounty-note">Chaque face du papier a son propre dessin.</p>`;},
  },
  lucioles:{name:'Lucioles',rules:luciolesRules,eyebrow:'UN REFLET POUR ÉCLAIRER LE JARDIN',title:'Un rayon.<br> <em>Mille reflets.</em>',copy:'Tournez les petits miroirs.<br>Réveillez tous les cristaux.',steps:[['Orientez la lumière.','Un miroir dévie le rayon. Un prisme le partage entre ses deux sorties.'],['Retrouvez les bonnes couleurs.','Chaque cristal attend une lumière de sa couleur. Les rayons peuvent se croiser dans une case vide.']],note:'Cliquez un miroir ou un prisme pour le tourner',unit:'cristaux à éclairer',reserve:'Les petits reflets.',reserveCopy:'Tournez un miroir d’un quart de tour. Les prismes ont trois ouvertures : une entrée et deux sorties.',finish:'Le jardin s’illumine.',delay:230,invalid:'Choisissez un miroir ou un prisme mobile.',total:g=>g.level.gems.length,remaining:g=>g.level.gems.length-lightTrace(g.level,g.state).lit.length,
    rulesText:['Cliquez un miroir ou son bouton pour le tourner. Il réfléchit réellement le rayon selon son orientation. Les sources de lumière, les cristaux et les pierres restent fixes.','Un prisme possède trois ouvertures. La lumière qui entre par l’une ressort par les deux autres ; une face fermée bloque le rayon.','Tous les cristaux doivent recevoir leur couleur. Un cristal absorbe le rayon, et une pierre l’arrête. Des lumières peuvent se croiser dans les espaces vides.','Les boucles de lumière sont détectées. Il faut éclairer tous les cristaux dans le même arrangement. Les indices vérifient une configuration complète depuis vos orientations actuelles. Annulation et sauvegarde sont disponibles.'],
    controls(g,selected,hint){return `<div class="lantern-optics">${g.level.field.flatMap((p,id)=>p&&!p.fixed&&['mirror','prism'].includes(p.type)?[`<button data-optic="${id}" class="${hint?.action?.id===id?'hinted':''}" aria-label="Tourner ${p.type==='prism'?'le prisme':'le miroir'} ${id+1}"><span>${p.type==='prism'?'✧':g.state.turns[id]?'╲':'╱'}</span><strong>${p.type==='prism'?'Prisme':'Miroir'} ${id+1}</strong><small>${g.state.turns[id]+1} / ${p.type==='prism'?4:2}</small></button>`]:[]).join('')}</div><p class="bounty-note">Les couleurs se croisent sans se mélanger.</p>`;},
  },
  aiguillages:{name:'Aiguillages',rules:aiguillagesRules,eyebrow:'LES PETITS TRAINS PRENNENT LEUR TEMPS',title:'Une voie.<br> <em>Un petit voyage.</em>',copy:'Préparez les rails et les départs.<br>Retrouvez chaque petite gare.',steps:[['Réglez les aiguillages.','Chaque levier choisit une des deux voies. Les petits lacs demandent parfois un détour.'],['Échelonnez les départs.','Un train peut attendre avant de partir. Gardez assez de place pour ses wagons aux croisements.']],note:'Réglez les voies et les départs · Puis lancez les petits trains',unit:'trains à la maison',reserve:'Les départs du jardin.',reserveCopy:'Les nombres indiquent les tours d’attente avant le départ. Observez librement avant de lancer les trains.',finish:'Tous les trains à la maison.',delay:0,invalid:'Choisissez un aiguillage ou un départ de 0 à 12 tours.',total:g=>g.level.trains.length,remaining:g=>g.level.trains.length-(g.state.result?.caught??0),
    afterStatus:g=>g.state.result?(g.won?'Chaque train a retrouvé sa gare.':`${g.state.result.caught} / ${g.level.trains.length} trains arrivés. Ajustez une voie ou un départ et réessayez.`):null,
    rulesText:['Cliquez un levier sur le plateau ou dans la liste pour changer sa voie. Les rails fixes, les lacs et les gares ne bougent pas.','Réglez le nombre de tours d’attente de chaque train, puis cliquez Lancer ou appuyez sur E. Les trains avancent ensemble, en suivant réellement les rails choisis.','Chaque train rejoint la gare de sa couleur. Une voie interrompue le fait dérailler. Deux trains qui se touchent ou échangent la même voie se heurtent ; les wagons occupent aussi les cases derrière la locomotive.','Les carrefours ne permettent pas de tourner : chaque train continue tout droit. Les départs décalés laissent le temps de libérer un passage. Les essais ne coûtent aucune vie. Une fenêtre ouverte suspend le voyage, et annuler restaure exactement les réglages avant l’essai.'],
    controls(g,selected,hint){return `<div class="lantern-switches">${g.level.switches.map(s=>`<button data-rail-switch="${s.id}" class="${hint?.action?.type==='switch'&&hint.action.id===s.id?'hinted':''}" aria-label="Changer l’aiguillage ${s.id+1}"><span>↔</span>Aiguillage ${s.id+1}<small>Voie ${g.state.switches[s.id]+1}</small></button>`).join('')}</div><div class="lantern-departures">${g.level.trains.map((t,id)=>`<label style="--color:${COLORS[t.color].hex}"><span>${COLORS[t.color].mark} Train ${id+1} · ${t.length} ${t.length>1?'voitures':'voiture'}</span><select data-rail-delay="${id}" aria-label="Départ du train ${id+1}">${Array.from({length:13},(_,n)=>`<option value="${n}" ${g.state.delays[id]===n?'selected':''}>${n===0?'Tout de suite':`${n} tours d’attente`}</option>`).join('')}</select>${hint?.action?.type==='delay'&&hint.action.id===id?`<small class="lantern-delay-hint">Indice : ${hint.action.value} tours · Entrée pour régler</small>`:''}</label>`).join('')}</div><div class="bounty-actions"><button data-rail-run>Lancer les petits trains <kbd>E</kbd></button></div><p class="bounty-note">Un tour après l’autre. Pas de limite de vies.</p>`;},
  },
};
