import {PocketCanvas} from './pocket-canvas.js';
import {COLORS,clone} from './pocket-core.js';
import {paperBounds,paperTop} from './plis-puzzle.js';
import {lightTrace,LIGHT_DIRS} from './lucioles-puzzle.js';
import {RailFlow,railMask,RAIL_DIRS} from './rail-simulation.js';
const W=640,H=600;
export class LanternCanvas extends PocketCanvas{
  constructor(container,mode,callbacks){
    super(container,mode,callbacks);this.canvas.setAttribute('aria-label',mode==='plis'?'Plis : faites glisser le papier à travers une ligne':mode==='lucioles'?'Lucioles : cliquez un miroir ou un prisme pour le tourner':'Aiguillages : réglez les leviers puis lancez les trains');
    this.canvas.addEventListener('pointerdown',e=>{if(!callbacks.enabled())return;this.canvas.focus({preventScroll:true});this.canvas.setPointerCapture(e.pointerId);const p=this.point(e),cell=this.at(p);if(cell===null)return;if(mode==='plis'){if(this.state.field[cell].length)this.grab={cell,start:p,point:p};}else this.pressed=cell;});
    this.canvas.addEventListener('pointermove',e=>{if(this.grab&&callbacks.enabled())this.grab.point=this.point(e);});
    this.canvas.addEventListener('pointerup',e=>{const p=this.point(e),cell=this.at(p),grab=this.grab;this.grab=null;if(!callbacks.enabled()){this.pressed=null;return;}
      if(grab&&Math.hypot(p[0]-grab.start[0],p[1]-grab.start[1])>8&&cell!==null){const size=this.level.size,axis=Math.abs(p[0]-grab.start[0])>=Math.abs(p[1]-grab.start[1])?'x':'y',from=axis==='x'?grab.cell%size:Math.floor(grab.cell/size),to=axis==='x'?cell%size:Math.floor(cell/size),line=Math.round((from+to+1)/2);callbacks.play({axis,line,side:from<line?-1:1});}
      if(this.pressed!==null&&this.pressed!==undefined&&this.pressed===cell){if(mode==='lucioles')callbacks.play({id:cell});if(mode==='aiguillages'&&this.level.field[cell]?.type==='switch')callbacks.play({type:'switch',id:this.level.field[cell].id});}this.pressed=null;
    });
    this.canvas.addEventListener('pointercancel',()=>{this.grab=null;this.pressed=null;});document.addEventListener('visibilitychange',this.visibility=()=>{this.last=performance.now();});
  }
  point(e){const r=this.canvas.getBoundingClientRect();return[(e.clientX-r.x)/r.width*W,(e.clientY-r.y)/r.height*H];}
  paperGrid(state=this.state){const b=paperBounds(this.level,state),w=b.right-b.left+1,h=b.bottom-b.top+1,cell=Math.min(74,456/w,370/h);return{cell,x:320-(b.left+w/2)*cell,y:335-(b.top+h/2)*cell};}
  grid(){if(this.mode!=='plis'){const cell=Math.min(73,470/this.level.size);return {cell,x:(640-cell*this.level.size)/2,y:67};}const g=this.paperGrid();if(!this.motion||this.motion.type!=='paper')return g;const old=this.paperGrid(this.motion.previous),t=Math.min(1,(performance.now()-this.motion.start)/420),ease=t*t*(3-2*t);return Object.fromEntries(['x','y','cell'].map(k=>[k,old[k]+(g[k]-old[k])*ease]));}
  at(p){const g=this.grid(),x=Math.floor((p[0]-g.x)/g.cell),y=Math.floor((p[1]-g.y)/g.cell);return x>=0&&y>=0&&x<this.level.size&&y<this.level.size?y*this.level.size+x:null;}
  position(id){const g=this.grid();return[g.x+(id%this.level.size+.5)*g.cell,g.y+(Math.floor(id/this.level.size)+.5)*g.cell];}
  screenPoint(value){const p=Array.isArray(value)?[this.grid().x+(value[0]+.5)*this.grid().cell,this.grid().y+(value[1]+.5)*this.grid().cell]:this.position(value),r=this.canvas.getBoundingClientRect();return{x:r.x+p[0]/W*r.width,y:r.y+p[1]/H*r.height};}
  foldScreenPoints(a){const n=this.level.size,id=this.state.field.findIndex((s,id)=>{const x=id%n,y=Math.floor(id/n),v=a.axis==='x'?x:y;if(!s.length||(a.side<0?v>=a.line:v<a.line))return false;const dest=a.axis==='x'?y*n+2*a.line-1-x:(2*a.line-1-y)*n+x;return this.state.field[dest]?.length;});if(id<0)return [];const x=id%n,y=Math.floor(id/n);return[this.screenPoint([x,y]),this.screenPoint(a.axis==='x'?[2*a.line-1-x,y]:[x,2*a.line-1-y])];}
  update(level,state,hint,selected,previous,action){const changed=level!==this.level||state!==this.state;this.level=level;this.state=state;this.hint=hint;this.selected=selected;
    if(changed){this.grab=null;this.pressed=null;this.motion=null;this.flow=null;this.running=false;this.last=performance.now();this.carry=0;this.before=null;
      if(this.mode==='plis'&&previous&&action&&!this.reduced)this.motion={type:'paper',previous,action,start:performance.now()};
      if(this.mode==='lucioles'){this.light=lightTrace(level,state);if(previous&&action&&!this.reduced)this.motion={type:'optic',id:action.id,from:previous.turns[action.id],start:performance.now()};}
      if(this.mode==='aiguillages'&&action?.type==='run'&&!this.reduced){this.flow=new RailFlow(level,state);this.running=true;}
    }this.draw();
  }
  line(points,color,width=2,dashed=false){const c=this.ctx;c.strokeStyle=color;c.lineWidth=width;c.lineCap=c.lineJoin='round';c.setLineDash(dashed?[5,5]:[]);c.beginPath();points.forEach((p,i)=>i?c.lineTo(...p):c.moveTo(...p));c.stroke();c.setLineDash([]);}
  paperCell(x,y,w,h,color,layers){this.round(x-w/2+2,y-h/2+4,Math.max(1,w),Math.max(1,h),0,'#5e644326');this.round(x-w/2,y-h/2,Math.max(1,w),Math.max(1,h),0,COLORS[color].hex,'#fff9e130');if(w>35&&h>35&&layers>1)this.text(`${layers}`,x+w*.34,y+h*.32,8,'#fff7dd');}
  targetPicture(){this.round(461,32,105,110,12,'#fcfaf0','#d7ddc9');this.text('LE PETIT MODÈLE',513,48,8,'#7e8c73');for(let y=6;y<10;y++)for(let x=6;x<10;x++)this.round(477+(x-6)*18,64+(y-6)*18,18,18,1,COLORS[this.level.target[y*this.level.size+x]].hex);}
  foldLine(a,g,color='#af975e'){const b=paperBounds(this.level,this.state);if(a.axis==='x')this.line([[g.x+a.line*g.cell,g.y+(b.top-.2)*g.cell],[g.x+a.line*g.cell,g.y+(b.bottom+1.2)*g.cell]],color,2,true);else this.line([[g.x+(b.left-.2)*g.cell,g.y+a.line*g.cell],[g.x+(b.right+1.2)*g.cell,g.y+a.line*g.cell]],color,2,true);}
  drawPaper(){const c=this.ctx,g=this.grid(),motion=this.motion,t=motion?Math.min(1,(performance.now()-motion.start)/420):1;this.round(40,30,560,527,24,'#e9e5d7','#d6d6c1');this.targetPicture();this.text('LE RECTO, LE VERSO ET LES PETITES COUCHES',261,76,9,'#899279');
    this.round(g.x+6*g.cell-4,g.y+6*g.cell-4,4*g.cell+8,4*g.cell+8,7,'#f5f3e3','#b8c6a4');
    const field=t<1?motion.previous.field:this.state.field,a=motion?.action;
    for(let id=0;id<field.length;id++){const stack=field[id];if(!stack.length)continue;const xx=id%this.level.size,yy=Math.floor(id/this.level.size),moving=t<1&&(a.side<0?(a.axis==='x'?xx:yy)<a.line:(a.axis==='x'?xx:yy)>=a.line);if(moving)continue;this.paperCell(g.x+(xx+.5)*g.cell,g.y+(yy+.5)*g.cell,g.cell,g.cell,paperTop(this.level,stack),stack.length);}
    if(t<1){const cos=Math.cos(t*Math.PI),lift=Math.sin(t*Math.PI)*25;for(let id=0;id<field.length;id++){const stack=field[id],xx=id%this.level.size,yy=Math.floor(id/this.level.size),v=a.axis==='x'?xx:yy;if(!stack.length||(a.side<0?v>=a.line:v<a.line))continue;let x=g.x+(xx+.5)*g.cell,y=g.y+(yy+.5)*g.cell,w=g.cell,h=g.cell;const crease=a.axis==='x'?g.x+a.line*g.cell:g.y+a.line*g.cell;if(a.axis==='x'){x=crease+(x-crease)*cos;w=Math.max(1,g.cell*Math.abs(cos));}else{y=crease+(y-crease)*cos;h=Math.max(1,g.cell*Math.abs(cos));}y-=lift;const top=t<.5?stack.at(-1):[stack[0][0],1-stack[0][1]];this.paperCell(x,y,w,h,this.level.faces[top[0]][top[1]],stack.length);}}
    if(this.hint?.action)this.foldLine(this.hint.action,g);if(this.grab){this.line([this.grab.start,this.grab.point],'#a98e54',3,true);}
    this.text('CHAQUE PLI RETOURNE AUSSI LES COUCHES DU DESSOUS',320,580,9,'#879077');
  }
  crystal(x,y,color,lit,scale=1){const c=this.ctx;c.save();c.translate(x,y);c.scale(scale,scale);if(lit){c.fillStyle=COLORS[color].hex+'40';c.beginPath();c.arc(0,0,27,0,7);c.fill();}c.fillStyle=lit?COLORS[color].hex:'#dddcca';c.strokeStyle=COLORS[color].hex;c.lineWidth=2;c.beginPath();c.moveTo(0,-18);c.lineTo(13,-6);c.lineTo(10,13);c.lineTo(0,20);c.lineTo(-10,13);c.lineTo(-13,-6);c.closePath();c.fill();c.stroke();this.line([[0,-17],[0,18],[-11,-5],[12,-5]],'#fff6dd80',1);this.text(lit?'✓':COLORS[color].mark,0,2,12,'#526b59');c.restore();}
  drawLights(){const c=this.ctx,g=this.grid(),now=this.reduced?0:performance.now();this.round(g.x-17,g.y-17,g.cell*this.level.size+34,g.cell*this.level.size+34,24,'#e4ebd8','#cfddc4');
    for(let id=0;id<this.level.field.length;id++){const [x,y]=this.position(id);this.round(x-g.cell*.47,y-g.cell*.47,g.cell*.94,g.cell*.94,8,'#f2f4e7');}
    for(const s of this.light.segments){const a=this.position(s.from),b=this.position(s.to);this.line([a,b],COLORS[s.color].hex+'55',9);this.line([a,b],COLORS[s.color].hex,3);if(!this.reduced){const t=(now/1100+s.from*.127)%1;c.fillStyle='#fff9da';c.beginPath();c.arc(a[0]+(b[0]-a[0])*t,a[1]+(b[1]-a[1])*t,2.5,0,7);c.fill();}}
    this.level.field.forEach((tile,id)=>{if(!tile)return;const [x,y]=this.position(id);if(tile.type==='rock'){this.round(x-g.cell*.3,y-g.cell*.28,g.cell*.6,g.cell*.56,10,'#a5af96','#929f85');this.text('▧',x,y,g.cell*.3,'#dae1cc');}
      if(tile.type==='gem')this.crystal(x,y,tile.color,this.light.lit.includes(id),g.cell/75);
      if(tile.type==='source'){this.round(x-g.cell*.27,y-g.cell*.27,g.cell*.54,g.cell*.54,12,COLORS[tile.color].hex,'#66816a');this.text(COLORS[tile.color].mark,x,y,20,'#fbf8e9');const s=this.level.sources.find(s=>s.cell===id),[dx,dy]=LIGHT_DIRS[s.dir];this.line([[x+dx*g.cell*.28,y+dy*g.cell*.28],[x+dx*g.cell*.4,y+dy*g.cell*.4]],'#769073',4);}
      if(tile.type==='mirror'||tile.type==='prism'){this.round(x-g.cell*.32,y-g.cell*.32,g.cell*.64,g.cell*.64,12,tile.type==='mirror'?'#ede5ce':'#e8e0bd','#c7bda0');const motion=this.motion?.id===id?this.motion:null,t=motion?Math.min(1,(now-motion.start)/220):1,turn=motion&&t<1?motion.from+t:this.state.turns[id];c.save();c.translate(x,y);c.rotate(tile.type==='mirror'?-Math.PI/4+turn*Math.PI/2:turn*Math.PI/2);if(tile.type==='mirror'){this.round(-g.cell*.34,-4,g.cell*.68,8,4,'#92abb0','#778f98');this.line([[-g.cell*.29,-2],[g.cell*.29,-2]],'#f9faf0',2);}else{for(const d of [0,1,3]){const [dx,dy]=LIGHT_DIRS[d];this.line([[0,0],[dx*g.cell*.3,dy*g.cell*.3]],'#b59f61',5);}this.crystal(0,0,3,true,.38);}c.restore();this.text(`${id+1}`,x+g.cell*.33,y+g.cell*.32,8,'#8e9277');if(this.hint?.action?.id===id)this.round(x-g.cell*.4,y-g.cell*.4,g.cell*.8,g.cell*.8,12,null,'#ac9254');}
    });this.text('DES COULEURS, DES REFLETS ET TOUS LES CRISTAUX',320,580,9,'#879077');
  }
  advance(){if(!this.running)return;const now=performance.now(),elapsed=Math.min(.05,(now-this.last)/1000);this.last=now;if(document.querySelector('dialog[open]'))return;this.carry+=elapsed/.14;while(this.carry>=1&&!this.flow.done){this.before=clone(this.flow.trains);this.flow.step();this.carry--;}this.callbacks.railProgress?.(this.flow.result().caught);if(this.flow.done){this.running=false;queueMicrotask(()=>this.callbacks.settled?.());}}
  track(id,mask){const g=this.grid(),[x,y]=this.position(id),ports=[0,1,2,3].filter(d=>mask&(1<<d));for(const d of ports){const [dx,dy]=RAIL_DIRS[d];this.line([[x,y],[x+dx*g.cell/2,y+dy*g.cell/2]],'#b2ae91',7);this.line([[x,y],[x+dx*g.cell/2,y+dy*g.cell/2]],'#fcf4de',2);for(const t of [.29,.75])this.line([[x+dx*g.cell/2*t-dy*5,y+dy*g.cell/2*t+dx*5],[x+dx*g.cell/2*t+dy*5,y+dy*g.cell/2*t-dx*5]],'#9c9f81',2);}}
  carriage(x,y,color,dir,head,scale){const c=this.ctx;c.save();c.translate(x,y);c.rotate((dir-1)*Math.PI/2);c.scale(scale,scale);this.round(-17,-12,34,24,6,COLORS[color].hex,'#5d755d');if(head){this.round(4,-9,15,18,4,'#e7d8b5');this.round(7,-6,8,9,2,'#537267');this.round(-11,-17,7,7,2,'#617962');}else this.round(-12,-8,24,16,3,'#ffffff30');for(const dx of [-10,10]){c.fillStyle='#58705d';c.beginPath();c.arc(dx,13,3.5,0,7);c.fill();}this.text(COLORS[color].mark,-5,0,12,'#faf5df');c.restore();}
  drawRails(){this.advance();const c=this.ctx,g=this.grid();this.round(g.x-18,g.y-18,g.cell*this.level.size+36,g.cell*this.level.size+36,24,'#dce6cf','#c9d9bd');
    this.level.field.forEach((tile,id)=>{const [x,y]=this.position(id);this.round(x-g.cell*.48,y-g.cell*.48,g.cell*.96,g.cell*.96,8,(id%this.level.size+Math.floor(id/this.level.size))%2?'#e7eddb':'#edf1e1');if(!tile){if(id%11===3){c.fillStyle='#a0b691';for(const [dx,dy] of [[0,-5],[-7,4],[7,4]]){c.beginPath();c.arc(x+dx,y+dy,g.cell*.13,0,7);c.fill();}}return;}if(tile.type==='pond'){this.round(x-g.cell*.4,y-g.cell*.3,g.cell*.8,g.cell*.6,20,'#a5c4c5');this.line([[x-9,y+3],[x+8,y+3]],'#d5e3d9',2);return;}this.track(id,railMask(this.level,this.state,id));
      if(tile.type==='switch'){this.round(x-12,y-10,24,20,6,'#c4af7c');this.line([[x,y],[x+(this.state.switches[tile.id]?9:-9),y-14]],'#71846c',3);this.text(`${tile.id+1}`,x,y,10,'#fff6d9');if(this.hint?.action?.type==='switch'&&this.hint.action.id===tile.id)this.round(x-g.cell*.38,y-g.cell*.38,g.cell*.76,g.cell*.76,12,null,'#af975c');}
      if(tile.type==='station'){this.round(x-18,y-10,36,27,5,'#f7f0dc','#c5c6a9');c.fillStyle=COLORS[tile.color].hex;c.beginPath();c.moveTo(x-22,y-9);c.lineTo(x,y-24);c.lineTo(x+22,y-9);c.fill();this.text(COLORS[tile.color].mark,x,y+3,15,'#68816a');}
      if(tile.type==='source'){this.round(x-18,y-18,36,36,12,COLORS[tile.color].hex+'60','#b9c8a8');this.text(COLORS[tile.color].mark,x,y,16,'#69816b');}
    });
    const trains=this.flow?.trains??this.state.result?.trains??this.level.trains.map(t=>({...t,status:'queued',cell:t.source,history:[]})),t=this.running?Math.min(1,this.carry):1;
    for(let id=0;id<trains.length;id++){const train=trains[id];if(train.status==='arrived'){this.text('✓',...this.position(train.cell),22,'#58795d');continue;}const old=this.before?.[id],body=train.history.slice(-train.length),prior=old?.history.slice(-train.length)??[];
      for(let part=train.length-1;part>=0;part--){const cell=body.at(-1-part)??train.cell,before=prior.at(-1-part)??old?.cell??cell,p=this.position(cell),q=this.position(before);if(part>0&&body.length<=part)continue;this.carriage(q[0]+(p[0]-q[0])*t,q[1]+(p[1]-q[1])*t,train.color,train.dir,part===0,g.cell/78);}
      if(['crashed','derailed'].includes(train.status)){const p=this.position(train.cell);this.text('×',p[0]+g.cell*.28,p[1]-g.cell*.24,24,'#b47861');}
      if(train.status==='queued')this.text(`${this.state.delays[id]}`,this.position(train.cell)[0],this.position(train.cell)[1]-g.cell*.3,10,'#927f50');
    }
    this.text(this.running?'LES PETITS TRAINS PRENNENT LA ROUTE…':'RÉGLEZ LES VOIES · PRÉPAREZ LES DÉPARTS · LANCEZ',320,580,9,'#879077');
  }
  draw(){if(!this.level||!this.canvas.width)return;const c=this.ctx;c.setTransform(this.canvas.width/W,0,0,this.canvas.height/H,0,0);c.clearRect(0,0,W,H);if(this.mode==='plis')this.drawPaper();else if(this.mode==='lucioles')this.drawLights();else this.drawRails();}
  dispose(){super.dispose();document.removeEventListener('visibilitychange',this.visibility);}
}
