import {basculesRules} from './bascules-puzzle.js';
import {sillonsRules} from './sillons-puzzle.js';
import {COLORS} from './pocket-core.js';
import {raccordsRules,jointConnections,jointCanShift,jointPorts} from './raccords-puzzle.js';

const arrows=['↑','→','↓','←'],labels=['Vers le haut','Vers la droite','Vers le bas','Vers la gauche'];
const directions=hint=>`<div class="meadow-directions">${arrows.map((a,dir)=>`<button data-meadow-dir="${dir}" aria-label="${labels[dir]}" class="${hint?.action?.dir===dir?'hinted':''}">${a}</button>`).join('')}</div>`;
export const JOINT_NAMES={fixed:'Fixe',pivot:'Tourne sur place',move:'Se déplace',free:'Libre',line:'Glisse sur sa ligne','line-turn':'Glisse et tourne'};

function jointThumb(piece,turn){const points=[[25,5],[45,25],[25,45],[5,25]];return `<svg viewBox="0 0 50 50" aria-hidden="true"><rect x="3" y="3" width="44" height="44" rx="9" fill="#faf8ec" stroke="#c9d7bc"/>${jointPorts(piece,turn).map((color,dir)=>color===null?'':`<path d="M25 25L${points[dir].join(' ')}" stroke="${COLORS[color].hex}" stroke-width="6" stroke-linecap="round"/>`).join('')}<circle cx="25" cy="25" r="9" fill="#f7f4e6"/><text x="25" y="29" text-anchor="middle" fill="#526e5c" font-size="11">${piece.id+1}</text></svg>`;}

export const meadowConfigs={
  bascules:{name:'Bascules',rules:basculesRules,eyebrow:'UN GALET, LE BON APPUI',title:'Un petit galet.<br> <em>Tout un chemin.</em>',copy:'Basculez d’une dalle à l’autre.<br>Retrouvez l’ouverture du jardin.',steps:[['Choisissez le bon appui.','Debout, le galet occupe une case. Couché, il en occupe deux.'],['Préparez les ponts.','Les boutons ouvrent les passages. Les dalles légères supportent seulement le galet couché.']],note:'Glissez en diagonale sur le jardin · Les flèches basculent le galet',unit:'galet à guider',reserve:'Quatre petits appuis.',reserveCopy:'Une bascule change la place et la posture. L’ouverture attend le galet debout.',finish:'Le galet a trouvé sa place.',delay:350,invalid:'Cet appui manque, le pont est fermé ou cette dalle ne supporte pas le galet debout.',total:()=>1,remaining:g=>g.won?0:1,
    rulesText:['Le galet mesure deux cases. Debout, il s’étale sur deux cases au prochain basculement ; couché dans son axe, il se redresse au prochain bord.','Toute son empreinte doit être soutenue. Les bords vides et les ponts fermés bloquent le déplacement. Les dalles dorées fragiles ne supportent que le galet couché.','Un bouton rond s’active dès qu’une partie du galet arrive dessus. Un bouton carré demande le galet debout. Chaque nouvelle arrivée inverse l’état du pont associé.','Rejoignez l’ouverture en position debout. Glissez sur le plateau, utilisez les boutons ou les quatre flèches. Annuler restitue la posture et les ponts exactement.'],
    controls(g,selected,hint){const gates=[...new Set(g.level.field.filter(t=>t?.kind==='bridge').map(t=>t.gate))];return `${directions(hint)}<p class="meadow-posture">${g.state.pose==='upright'?'▣ Le galet est debout.':'▬ Le galet est couché.'}</p><div class="meadow-ledger">${gates.map(id=>`<span>Le pont ${id+1}<strong>${g.state.gates&(1<<id)?'Ouvert':'Fermé'}</strong></span>`).join('')}</div><p class="bounty-note">Un appui refusé ne coûte aucune vie.</p>`;},
  },
  sillons:{name:'Sillons',rules:sillonsRules,eyebrow:'LE JARDIN PREND SA COULEUR',title:'Un petit coup.<br> <em>Toute une allée.</em>',copy:'Glissez entre les pierres.<br>Colorez chaque case du jardin.',steps:[['Laissez le pinceau glisser.','Il colore son passage et s’arrête à la prochaine pierre ou au bord.'],['Retrouvez les petites allées.','Les ronds font une halte. Les flèches imposent le sens du prochain départ.']],note:'Glissez dans une direction · Colorez toutes les petites allées',unit:'cases à colorer',reserve:'Un pinceau en promenade.',reserveCopy:'Chaque glissade colore tout son passage. Une allée déjà peinte reste traversable.',finish:'Le jardin a toutes ses couleurs.',delay:350,invalid:'Cette direction est bloquée, ou une flèche impose un autre départ.',total:g=>g.level.field.filter(Boolean).length,remaining:g=>g.level.field.filter((v,id)=>v&&!g.state.painted[id]).length,
    rulesText:['Glissez vers le haut, la droite, le bas ou la gauche. Le pinceau poursuit sa course jusqu’au bord, une pierre ou une halte ronde.','Toutes les cases traversées se colorent. Vous pouvez repasser librement dans une allée déjà peinte. Les petites plantes sont des obstacles fixes.','Dans les chapitres avancés, une flèche arrête le pinceau et impose la direction de son prochain départ. Une halte simple laisse choisir librement.','Colorez chaque case du jardin. Une glissade entière est un seul geste à annuler. Les boutons et les flèches du clavier permettent de jouer sans glisser.'],controls:(g,s,hint)=>`${directions(hint)}<div class="meadow-ledger"><span>Déjà colorées<strong>${g.state.painted.filter(Boolean).length} / ${g.level.field.filter(Boolean).length}</strong></span><span>Le jardin<strong>${g.level.cols} × ${g.level.rows}</strong></span></div><p class="bounty-note">Un rond fait une halte. Une flèche donne le sens.</p>`,
  },
  raccords:{name:'Raccords',rules:raccordsRules,eyebrow:'UNE PETITE CONSTELLATION DE LIENS',title:'Un lien.<br> <em>Puis tout se rejoint.</em>',copy:'Tournez les petites pièces.<br>Retrouvez tous les bons raccords.',steps:[['Choisissez votre pièce.','Les petites marques indiquent ce qu’elle peut faire : bouger, tourner ou glisser sur sa ligne.'],['Réunissez chaque lien.','Les couleurs voisines se raccordent. Retrouvez une seule constellation sans lien ouvert.']],note:'Choisissez une pièce · Glissez-la · T pour tourner',unit:'pièces à accorder',reserve:'Chaque pièce a son geste.',reserveCopy:'Une attache fixe, une pièce qui tourne, une voisine qui glisse. Retrouvez leurs bons côtés.',finish:'Tout se rejoint enfin.',delay:350,invalid:'Cette pièce est fixe, sa ligne ne rejoint pas cette case ou la place est occupée.',total:g=>g.level.pieces.length,remaining:g=>{const c=jointConnections(g.level,g.state);return Math.max(c.loose.filter(n=>n>0).length,c.groups.length-1);},
    rulesText:['Les pattes de même couleur se raccordent seulement entre cases voisines. Aucun lien ne doit dépasser du plateau ou rester ouvert.','Les pièces fixes ne bougent pas. Les pivots tournent sur place. Les pièces vertes se déplacent sans tourner. Les pièces libres acceptent les deux gestes.','Les pièces marquées d’une ligne glissent seulement sur leur rangée. Les variantes dorées peuvent aussi tourner. Une case ne peut contenir qu’une seule pièce.','Reliez toutes les pièces en une seule constellation. Choisissez une pièce puis une place vide, faites-la glisser, ou tournez avec T et le bouton. Un clic supplémentaire sur la pièce choisie la tourne si elle le permet.'],
    controls(g,selected,hint){const piece=g.level.pieces[selected],turnable=piece&&!['fixed','move','line'].includes(piece.kind);return `<div class="meadow-pieces">${g.level.pieces.map(p=>`<button data-joint-pick="${p.id}" aria-label="Choisir la pièce ${p.id+1}" aria-pressed="${selected===p.id}" class="${hint?.action?.id===p.id?'hinted':''}">${jointThumb(p,g.state.turns[p.id])}<small>${JOINT_NAMES[p.kind]}</small></button>`).join('')}</div><div class="bounty-actions"><button data-joint-turn ${!turnable?'disabled':''}>Tourner la pièce <kbd>T</kbd></button></div><span class="pocket-reserve-label">CHOISISSEZ UNE PLACE LIBRE</span><div class="meadow-cells" style="--cols:${g.level.cols}">${Array.from({length:g.level.cols*g.level.rows},(_,id)=>`<button data-joint-cell="${id}" aria-label="Déplacer en ${String.fromCharCode(65+id%g.level.cols)}${Math.floor(id/g.level.cols)+1}" ${selected===null||!jointCanShift(g.level,g.state,selected,id)?'disabled':''}>${String.fromCharCode(65+id%g.level.cols)}${Math.floor(id/g.level.cols)+1}</button>`).join('')}</div>`;},
  },
};
