import {cagettesRules} from './cagettes-puzzle.js';
import {cairnsRules,cairnTop} from './cairns-puzzle.js';
import {jalonsRules,jalonNext} from './jalons-puzzle.js';

const directions=hint=>`<div class="meadow-directions" aria-label="Déplacer le jardinier">${['Monter','Aller à droite','Descendre','Aller à gauche'].map((name,dir)=>`<button data-orchard-dir="${dir}" aria-label="${name}" class="${hint?.action?.dir===dir?'hinted':''}">${['↑','→','↓','←'][dir]}</button>`).join('')}</div>`;
export const orchardConfigs={
  cagettes:{name:'Cagettes',rules:cagettesRules,eyebrow:'CHAQUE PANIER TROUVE SA PLACE',title:'Un petit jardin.<br> <em>Tout à ranger.</em>',copy:'Poussez les paniers.<br>Retrouvez les petites fleurs.',steps:[['Passez derrière.','Le jardinier pousse une seule cagette à la fois. Il ne peut jamais la tirer.'],['Gardez une allée.','Une cagette contre une haie peut bloquer le chemin. Prenez le temps de préparer chaque poussée.']],note:'Glissez, cliquez une case voisine ou utilisez les flèches.',unit:'cagettes à ranger',reserve:'Les paniers du jardin.',reserveCopy:'Les fleurs accueillent n’importe quelle cagette. Poussez-les toutes au bon endroit.',finish:'Un petit jardin bien rangé.',delay:240,invalid:'Une haie ou une cagette bloque ce pas. Deux cagettes ne se poussent pas ensemble.',total:g=>g.level.boxes.length,remaining:g=>g.state.boxes.filter(id=>!g.level.goals.includes(id)).length,
    rulesText:['Déplacez le jardinier d’une case avec les flèches, un glissement, ou un clic sur une case voisine.','En marchant vers une cagette, vous la poussez d’une case. Vous ne pouvez ni la tirer, ni en pousser deux ensemble.','Les haies bloquent le jardinier et les cagettes. Rangez chaque cagette sur une fleur ; les fleurs n’ont pas de couleur imposée.','Un coin peut enfermer une cagette. Annulez librement. Les indices proposent une suite vérifiée ou un retour à annuler.'],
    controls:(g,selected,hint)=>directions(hint)+`<div class="meadow-ledger">${g.state.boxes.map((id,n)=>`<span>Panier ${n+1}<strong>${g.level.goals.includes(id)?'Sur une fleur ✓':'À guider'}</strong></span>`).join('')}</div>`,
  },
  cairns:{name:'Cairns',rules:cairnsRules,eyebrow:'LES PETITES TOURS PRENNENT LEUR TEMPS',title:'Un anneau.<br> <em>Un nouvel appui.</em>',copy:'Déplacez les petites pierres.<br>Retrouvez le sommet fleuri.',steps:[['Prenez celui du dessus.','Seul le plus petit anneau présent sur une tige peut être déplacé.'],['Suivez les petits ponts.','Un grand anneau ne peut pas recouvrir un plus petit. Les ponts indiquent les tiges qui communiquent.']],note:'Choisissez une tige, puis une destination. Les touches 1 à 4 choisissent les tiges.',unit:'anneaux à guider',reserve:'Le sommet à rejoindre.',reserveCopy:'Gardez les petits anneaux au-dessus des grands. Faites circuler les tours par les ponts.',finish:'Tous les anneaux au sommet.',delay:360,invalid:'Ce pont est absent, ou un anneau plus petit occupe déjà cette tige.',total:g=>g.level.count,remaining:g=>g.state.disks.filter(at=>at!==g.level.goal).length,
    rulesText:['Tous les anneaux doivent rejoindre la tige marquée BUT. Le plus petit porte le numéro 1.','On ne déplace que l’anneau du dessus. Un grand anneau ne peut jamais être posé sur un plus petit.','Choisissez une tige puis une autre, faites glisser l’anneau, ou utilisez les touches 1 à 4. Choisir une seconde fois la même tige annule la sélection.','Les tiges ne communiquent que si un pont les relie. Les derniers chapitres retirent certains ponts : utilisez les appuis intermédiaires.'],
    controls(g,selected,hint){return `<p class="meadow-posture">Le but : <strong>tige ${String.fromCharCode(65+g.level.goal)}</strong><br>${g.level.pegs} tiges · ${g.level.count} anneaux</p><div class="orchard-pegs">${Array.from({length:g.level.pegs},(_,id)=>`<button data-cairn-peg="${id}" aria-pressed="${selected===id}" class="${hint?.action?.from===id||hint?.action?.to===id?'hinted':''}" ${selected===null&&cairnTop(g.state,id)<0?'disabled':''}><strong>${String.fromCharCode(65+id)}</strong><small>${id===g.level.goal?'Le sommet':'Un appui'}</small><span>${g.state.disks.flatMap((at,n)=>at===id?[n+1]:[]).join(' · ')||'Libre'}</span></button>`).join('')}</div><span class="pocket-reserve-label">LES PONTS DISPONIBLES</span><div class="orchard-bridges">${g.level.links.map(([a,b])=>`<span>${String.fromCharCode(65+a)} ↔ ${String.fromCharCode(65+b)}</span>`).join('')}</div>${selected===null?'':`<p class="meadow-posture">Anneau ${cairnTop(g.state,selected)+1} choisi sur ${String.fromCharCode(65+selected)}.</p>`}`;},
  },
  jalons:{name:'Jalons',rules:jalonsRules,eyebrow:'CHAQUE PETIT REPÈRE COMPTE',title:'Un numéro.<br> <em>Tout un chemin.</em>',copy:'Suivez les petits jalons.<br>Ne laissez aucune case derrière.',steps:[['Suivez les nombres.','Partez de 1. Rejoignez les numéros dans l’ordre, jusqu’au dernier.'],['Visitez tout le jardin.','Le chemin parcourt chaque case une seule fois. Les murets vous invitent à faire un détour.']],note:'Tracez depuis le bout du chemin, cliquez une case voisine ou utilisez les flèches.',unit:'cases à parcourir',reserve:'De repère en repère.',reserveCopy:'Un seul chemin, dans le bon ordre. Les numéros sont des étapes ; toutes les cases comptent.',finish:'Un chemin sans rien oublier.',delay:240,invalid:'Le chemin doit rester voisin, éviter les murets et suivre les nombres dans l’ordre.',total:g=>g.level.cols*g.level.rows,remaining:g=>g.level.cols*g.level.rows-g.state.path.length,
    rulesText:['Le chemin commence sur 1. Passez par 2, puis 3, jusqu’au dernier numéro.','Toutes les cases doivent être parcourues une seule fois. Vous ne pouvez ni croiser votre chemin ni traverser un muret.','Le dernier numéro termine le chemin : rejoignez-le seulement lorsque toutes les autres cases sont visitées.','Faites glisser depuis le bout du chemin. Revenez sur le geste en cours pour raccourcir le tracé avant de relâcher. Chaque geste s’annule en entier. Les boutons et les flèches permettent aussi d’avancer case par case.'],
    controls(g,selected,hint){const head=g.state.path.at(-1);return `<p class="meadow-posture">${jalonNext(g.level,g.state)<=g.level.markCount?`Prochain jalon : ${jalonNext(g.level,g.state)}`:'Tous les repères réunis'}<br>${g.state.path.length} / ${g.level.cols*g.level.rows} cases</p><div class="orchard-jalons" style="--cols:${g.level.cols}">${Array.from({length:g.level.cols*g.level.rows},(_,id)=>`<button data-jalon-cell="${id}" aria-label="Rejoindre ${String.fromCharCode(65+id%g.level.cols)}${Math.floor(id/g.level.cols)+1}${g.level.marks[id]?`, jalon ${g.level.marks[id]}`:''}" ${!jalonsRules.move(g.level,g.state,{path:[head,id]})?'disabled':''} class="${hint?.action?.path.at(-1)===id?'hinted':''}">${g.level.marks[id]||`${String.fromCharCode(65+id%g.level.cols)}${Math.floor(id/g.level.cols)+1}`}</button>`).join('')}</div>`;},
  },
};
