import { COLORS } from './pocket-core.js';
import { noeudsRules, ropeCrossings } from './noeuds-puzzle.js';
import { gouttesRules, inkUsed, WATER_TOTAL } from './gouttes-puzzle.js';
const dot=color=>`<span class="color-dot" style="--color:${COLORS[color].hex};${color===7?'color:#fffaf0':''}">${COLORS[color].mark}</span>`;
export const physicsConfigs={
  noeuds:{name:'Nœuds',rules:noeudsRules,eyebrow:'UN PETIT MÉLI-MÉLO, UN FIL À LA FOIS',title:'Les fils<br> <em>se détendent.</em>',copy:'Déplacez les petites attaches.<br>Retrouvez un jardin sans nœuds.',steps:[['Prenez une attache.','Faites-la glisser vers un plot vide, ou sélectionnez-la puis choisissez son nouvel emplacement.'],['Séparez les fils.','Plus aucune corde ne doit en croiser ou en toucher une autre. Les attaches vissées restent fixes.']],note:'Déplacez une attache vers un plot vide',unit:'croisements à défaire',reserve:'Les petites attaches.',reserveCopy:'Les deux bouts d’une corde portent la même couleur. Les attaches marquées d’une vis sont fixes.',finish:'Tous les fils respirent.',delay:220,invalid:'Ce plot est occupé, ou cette attache est fixe.',
    rulesText:['Faites glisser une attache colorée jusqu’à un plot vide. Vous pouvez aussi cliquer l’attache puis le plot, ou utiliser les boutons.','La corde reste reliée à ses deux attaches. Elle se tend entre elles ; les passages et les contacts avec une autre corde comptent comme des croisements.','Les attaches marquées d’une vis ne bougent pas. Les chapitres suivants ajoutent plus de cordes, de plots et de points fixes.','Séparez toutes les cordes pour terminer. Plusieurs dispositions peuvent fonctionner. Un indice vérifie une route complète depuis votre placement actuel, avec des plots libres pour déplacer les voisins.'],
    total:game=>game.level.ropes.length*(game.level.ropes.length-1)/2,remaining:game=>ropeCrossings(game.level,game.state).length,
    controls(game,selected,hint){return `<div class="physics-pins">${game.level.pins.map((pin,id)=>`<button data-select="${id}" aria-pressed="${selected===id}" ${pin.fixed?'disabled':''} class="${hint?.action?.pin===id?'hinted':''}" aria-label="Attache ${id+1}, ${COLORS[pin.color].name}${pin.fixed?', fixe':''}">${dot(pin.color)}<small>${id+1} ${pin.fixed?'⊕':''}</small></button>`).join('')}</div><span class="pocket-reserve-label">${selected===null?'CHOISISSEZ UNE ATTACHE MOBILE':`ATTACHE ${selected+1} · CHOISISSEZ UN PLOT VIDE`}</span><div class="physics-pegs" style="--size:${game.level.size}">${game.level.pegs.map((p,peg)=>({p,peg})).sort((a,b)=>a.p[1]-b.p[1]||a.p[0]-b.p[0]).map(({peg})=>`<button data-peg="${peg}" ${selected===null||game.state.pins.includes(peg)?'disabled':''} class="${hint?.action?.peg===peg?'hinted':''}" aria-label="Plot ${peg+1}${game.state.pins.includes(peg)?', occupé':', libre'}">${game.state.pins.includes(peg)?'●':peg+1}</button>`).join('')}</div>`;},
  },
  gouttes:{name:'Gouttes',rules:gouttesRules,eyebrow:'UN TRAIT, UN DÉTOUR, UN VERRE HEUREUX',title:'L’eau trouve<br> <em>son chemin.</em>',copy:'Dessinez des petits ponts.<br>Guidez les gouttes dans le verre.',steps:[['Dessinez avant la pluie.','Tracez vos rampes avec le doigt ou la souris. Un trait posé reste en place pour guider l’eau.'],['Ouvrez le robinet.','Laissez couler les gouttes. La gravité et les obstacles feront le reste. Annulez et ajustez autant que vous voulez.']],note:'Dessinez une rampe, puis laissez couler l’eau',unit:'gouttes à recueillir',reserve:'Un petit trait suffit ?',reserveCopy:'Les traits sont des rampes fixes. Gardez de l’encre pour les virages et laissez une ouverture au-dessus du verre.',finish:'Un verre plein de sourires.',delay:0,invalid:'Ce trait traverse un obstacle, sort du jardin ou dépasse l’encre disponible.',
    rulesText:['Faites glisser le doigt ou la souris dans le jardin pour dessiner un trait. Il devient une rampe fixe : les gouttes rebondissent et glissent dessus sous l’effet de la gravité.','Les blocs du jardin sont solides. Votre trait doit rester dans le jardin et ne peut pas traverser un bloc. L’encre disponible indique la longueur totale que vous pouvez dessiner.','Cliquez « Laisser couler » ou appuyez sur E pour libérer 60 gouttes. Le repère du verre indique combien il faut en recueillir. Les chapitres suivants ajoutent des obstacles, des changements de direction et un objectif plus exigeant.','Une tentative ratée ne coûte rien. Annulez le dernier trait ou effacez vos rampes, puis réessayez. Un indice peut effacer vos traits avant de proposer une route vérifiée avec la même simulation d’eau.'],
    total:game=>game.level.goal,remaining:game=>Math.max(0,game.level.goal-(game.state.result?.caught??0)),
    controls(game){return `<div class="physics-water-controls"><button data-water-run class="water-run">◉ Laisser couler <kbd>E</kbd></button><button data-water-clear ${!game.state.lines.length&&!game.state.result?'disabled':''}>↶ Effacer les rampes</button><span class="pocket-reserve-label">L’ENCRE DU JARDIN</span><div class="physics-ink"><span style="width:${Math.max(0,100*(1-inkUsed(game.state.lines)/game.level.ink))}%"></span></div><p>${Math.floor(game.level.ink-inkUsed(game.state.lines))} / ${game.level.ink} unités restantes</p><span class="pocket-reserve-label">LE VERRE ATTEND SES GOUTTES</span><div class="physics-water-result"><strong>${game.state.result?.caught??0} / ${game.level.goal}</strong><small>${WATER_TOTAL} gouttes dans le robinet</small></div><details class="physics-assisted"><summary>Tracer avec des points</summary><p>Choisissez le départ, puis les points suivants. Chaque point est relié au précédent. Terminez pour poser la rampe.</p><div class="physics-point-picker"><label>X <input id="water-x" type="number" min="35" max="605" value="100"></label><label>Y <input id="water-y" type="number" min="75" max="550" value="150"></label></div><button data-water-point>Ajouter ce point</button><button data-water-place>Poser le trait</button><button data-water-cancel>Annuler le tracé</button><small id="water-point-status" role="status"></small></details></div>`;},
  },
};
