import {COLORS} from './pocket-core.js';
import {ruisseauxRules,waterRoute} from './ruisseaux-puzzle.js';
import {balancierRules} from './balancier-puzzle.js';
import {geleesRules,jellyCells} from './gelees-puzzle.js';
export function jellySvg(piece,turns=0){const cells=jellyCells(piece,turns),w=Math.max(...cells.map(p=>p[0]))+1,h=Math.max(...cells.map(p=>p[1]))+1;return `<svg viewBox="0 0 ${w*20+8} ${h*20+8}" aria-hidden="true">${cells.map(([x,y])=>`<rect x="${4+x*20}" y="${4+y*20}" width="20" height="20" rx="5" fill="${COLORS[piece.color].hex}"/>`).join('')}</svg>`;}
export const springConfigs={
  ruisseaux:{name:'Ruisseaux',rules:ruisseauxRules,eyebrow:'UN PEU D’EAU POUR LES PETITES FLEURS',title:'De dalle<br> <em>en dalle.</em>',copy:'Faites glisser les petits canaux.<br>Retrouvez le chemin de l’eau.',steps:[['Déplacez une dalle.','Une place vide permet de faire glisser sa voisine. Les canaux gardent leur orientation.'],['Arrosez le jardin.','Reliez la source au petit bassin en passant par toutes les fleurs du plateau.']],note:'Faites glisser une dalle vers une place vide · Flèches pour la dalle choisie',unit:'fleurs et arrivée à relier',reserve:'Les dalles du jardin.',reserveCopy:'La source, l’arrivée et les pierres restent fixes. Les autres dalles se déplacent dans les places vides.',finish:'Un jardin bien arrosé.',delay:280,invalid:'Cette dalle doit être mobile et voisine d’une case vide.',
    total:g=>g.level.stars.length+1,remaining:g=>{const r=waterRoute(g.level,g.state);return g.level.stars.length+1-r.stars-Number(r.reached);},
    rulesText:['Faites glisser une dalle mobile horizontalement ou verticalement vers une case vide. Vous pouvez aussi cliquer son départ puis sa destination, ou utiliser les flèches.','Les dalles gardent leurs canaux : elles ne tournent pas. Les deux bouts du ruisseau et les pierres sont fixes.','L’eau avance seulement lorsque les deux canaux voisins se rejoignent. Un canal qui débouche sur du bois, un bord ou une case vide arrête le ruisseau.','Reliez la source à l’arrivée et arrosez toutes les fleurs marquées sur le jardin. Chaque plateau dispose d’une suite complète de déplacements. Annulez ou suivez un indice vérifié.'],
    controls(g,selected,hint){return `<div class="spring-grid" style="--cols:${g.level.size}">${g.state.field.map((tile,id)=>`<button data-stream="${id}" aria-pressed="${selected===id}" class="${hint?.action?.from===id||hint?.action?.to===id?'hinted':''}" aria-label="Case ${id+1}, ${tile===null?'vide':g.level.tiles[tile].fixed?'dalle fixe':'dalle mobile'}">${tile===null?'+':id===g.level.source?'◉':id===g.level.goal?'✿':g.level.tiles[tile].type==='stone'?'▧':id+1}</button>`).join('')}</div><p class="bounty-note">Les fleurs doivent toutes recevoir de l’eau.</p>`;},
  },
  balancier:{name:'Balancier',rules:balancierRules,eyebrow:'UN PETIT ÉLAN, UNE CORDE DE MOINS',title:'Une baie.<br> <em>Un joli vol.</em>',copy:'Coupez les bons fils.<br>Retrouvez le petit panier.',steps:[['Laissez la baie se balancer.','Lancez le mouvement, puis choisissez le moment où couper une corde. Vous pouvez faire une pause.'],['Récoltez les petits pétales.','La baie doit toucher chaque pétale avant de rejoindre le panier. Son élan continue après la coupe.']],note:'Lancez le balancier · Coupez une corde · Espace pour la pause',unit:'pétales et baie à récolter',reserve:'Les petits fils.',reserveCopy:'Coupez une corde sur le plateau ou avec son bouton. Les indices exécutent une coupe au moment vérifié.',finish:'La baie a trouvé son panier.',delay:0,invalid:'Cette corde est déjà coupée, ou la baie a quitté le jardin. Annulez et retrouvez un bon moment.',
    total:g=>g.level.stars.length+1,remaining:g=>g.level.stars.length+1-(g.state.result?.collected.length??0)-Number(g.state.result?.caught??false),
    rulesText:['Le mouvement commence en pause. Cliquez Lancer le balancier, ou appuyez sur Espace. Le pendule et la gravité dirigent réellement la baie.','Cliquez une corde ou traversez-la avec un geste pour la couper. Les boutons font la même coupe au moment courant. Une corde coupée libère son élan ; les autres continuent de retenir la baie.','Touchez tous les petits pétales, puis rejoignez le panier. Les pierres dévient la baie et les bords ouverts peuvent la laisser s’échapper. Vous pouvez annuler chaque coupe et recommencer sans limite de vies.','Une pause laisse le temps d’observer. Les indices indiquent un moment vérifié : Entrée ou le bouton de la corde remettent le pendule à cet instant et exécutent la coupe. Recharge et annulation conservent les coupes et leur instant exact.'],
    controls(g,selected,hint){return `<div class="spring-clock"><span>LE PETIT BALANCIER</span><strong id="swing-clock">0.00 s</strong><button data-swing-pause>Lancer le balancier <kbd>Espace</kbd></button></div><div class="spring-ropes">${g.level.ropes.map((r,id)=>`<button data-rope="${id}" ${g.state.cuts.some(a=>a.rope===id)?'disabled':''} class="${hint?.action?.rope===id?'hinted':''}"><span>${g.state.cuts.some(a=>a.rope===id)?'✓':'✂'}</span>Corde ${id+1}<small>${hint?.action?.rope===id?`À ${(hint.action.tick/120).toFixed(2)} s · moment vérifié`:'Couper au moment courant'}</small></button>`).join('')}</div>`;},
  },
  gelees:{name:'Gelées',rules:geleesRules,eyebrow:'LES PETITS REBONDS FONT LES BELLES PAUSES',title:'Un petit pot.<br> <em>Bien rempli.</em>',copy:'Tournez les petites gelées.<br>Trouvez leur place dans le pot.',steps:[['Choisissez une forme.','Tournez-la par quarts de tour, puis faites-la glisser au-dessus de la bonne colonne.'],['Préparez l’empilement.','Les formes tombent tout droit. Une gelée peut couvrir le passage dont une autre a encore besoin.']],note:'Choisissez une gelée · Tournez-la avec T · Posez-la dans une colonne',unit:'cases à remplir',reserve:'Les petites douceurs.',reserveCopy:'Chaque forme est disponible une seule fois. Remplissez le pot en gardant les passages nécessaires.',finish:'Toutes les douceurs rangées.',delay:0,invalid:'Cette gelée ne tient pas ici : tournez-la, changez de colonne ou annulez une forme qui bloque son passage.',
    total:g=>g.level.total,remaining:g=>g.state.field.filter(v=>v===null).length,
    rulesText:['Choisissez une gelée dans la réserve. Le bouton Tourner ou T la tourne d’un quart de tour. Vous pouvez également suivre une orientation indiquée par un indice.','Faites glisser la forme au-dessus du pot ou cliquez une colonne. Elle tombe verticalement jusqu’au premier appui, sans traverser une pierre ou une gelée. Les flèches déplacent son aperçu ; Espace la pose.','Remplissez toutes les cases du pot avec la réserve entière. Une forme qui dépasserait la ligne blanche est refusée. Aucun groupe ni aucune ligne ne disparaît.','Pensez à l’ordre : un surplomb peut fermer l’accès d’une forme suivante. Les petits rebonds accompagnent sa pose dans le moule. Annulation exacte, indices vérifiés et sauvegarde restent disponibles.'],
    controls(g,selected,hint){return `<div class="spring-jellies">${g.level.order.filter(id=>!g.state.used.includes(id)).map(id=>`<button data-jelly="${id}" aria-pressed="${selected===id}" class="${hint?.action?.id===id?'hinted':''}" aria-label="Choisir la gelée ${id+1}, ${g.level.pieces[id].cells.length} carrés">${jellySvg(g.level.pieces[id])}<small>${id+1} · ${g.level.pieces[id].cells.length} carrés</small></button>`).join('')}</div><div class="bounty-actions"><button data-jelly-rotate ${selected===null?'disabled':''}>Tourner la gelée <kbd>T</kbd></button></div><span class="pocket-reserve-label">LA COLONNE DE DÉPART</span><div class="spring-grid" style="--cols:${g.level.cols}">${Array.from({length:g.level.cols},(_,x)=>`<button data-jelly-column="${x}" ${selected===null?'disabled':''} aria-label="Poser dans la colonne ${x+1}">${x+1}</button>`).join('')}</div>`;},
  },
};
