import './bounty-style.css';
import { COLORS, CHAPTERS, LEVEL_COUNT, PocketGame, clone, encodePocket, decodePocket } from './pocket-core.js';
import { passagesRules } from './passages-puzzle.js';
import { voyageRules, accessiblePassengers } from './voyage-puzzle.js';
import { carrouselRules } from './carrousel-puzzle.js';
import { broderieRules, accessibleSpools } from './broderie-puzzle.js';
import { SuiteCanvas } from './suite-canvas.js';
import { GardenCanvas } from './garden-canvas.js';
import { gardenConfigs } from './garden-config.js';
import { neighbors } from './liaisons-puzzle.js';
import { PhysicsCanvas } from './physics-canvas.js';
import { physicsConfigs } from './physics-config.js';
import { HarvestCanvas } from './harvest-canvas.js';
import { harvestConfigs } from './harvest-config.js';
import { sandWidth } from './dunes-puzzle.js';
import { BountyCanvas } from './bounty-canvas.js';
import { bountyConfigs } from './bounty-config.js';
import { chainNeighbors } from './recolte-puzzle.js';
import { activePieces, pieceWidth, pieceHeight } from './mosaique-puzzle.js';

const mode=document.body.dataset.pocket, $=s=>document.querySelector(s), base=import.meta.env.BASE_URL;
const configs={
  ...gardenConfigs,
  ...physicsConfigs,
  ...harvestConfigs,
  ...bountyConfigs,
  passages:{name:'Passages',rules:passagesRules,eyebrow:'UN PEU DE PLACE, UN NOUVEAU CHEMIN',title:'Une porte.<br> <em>Un passage.</em>',copy:'Faites glisser les couleurs.<br>Ouvrez les petites portes.',steps:[['Choisissez votre bloc.','Faites-le glisser de case en case, ou sélectionnez-le puis utilisez les flèches.'],['Préparez les passages.','Chaque bloc rejoint sa porte colorée. Déplacez les voisins qui lui barrent la route.']],note:'Faites glisser un bloc · Flèches pour le déplacer',unit:'blocs à libérer',reserve:'Les petites portes.',reserveCopy:'Sélectionnez un bloc, puis guidez-le vers la porte de sa couleur.',finish:'Toutes les portes ouvertes.',delay:0,rulesText:['Cliquez un bloc pour le choisir. Faites-le glisser horizontalement ou verticalement, ou utilisez le clavier et les boutons directionnels.','Les blocs restent entiers : les haies, les autres pièces et les bords fermés empêchent leur déplacement.','Chaque bloc possède une porte de sa couleur. Alignez toute sa largeur avec cette porte, puis poussez-le vers l’extérieur.','Déplacer un voisin peut libérer un passage. Un indice ne propose un coup que lorsqu’une route complète a été vérifiée. Vous pouvez annuler chaque déplacement.']},
  voyage:{name:'Voyage',rules:voyageRules,eyebrow:'LES PETITS DÉPARTS FONT LES GRANDS VOYAGES',title:'Tout le monde<br> <em>à bord.</em>',copy:'Des voisins à embarquer.<br>Une couleur, un départ.',steps:[['Libérez l’allée.','Seuls les voyageurs reliés au quai par un passage libre peuvent se lever.'],['Gardez une place.','Le bus prend sa couleur. Les autres voyageurs attendent sur les cinq places du banc.']],note:'Choisissez un voyageur accessible',unit:'voyageurs à embarquer',reserve:'La salle d’attente.',reserveCopy:'Le bus attend sa couleur. Un bus complet part et laisse arriver le suivant.',finish:'Le dernier bus est parti.',delay:420,rulesText:['Cliquez un voyageur accessible dans la salle ou dans la liste. Il doit pouvoir rejoindre le quai du bas par une allée libre.','Le bus actuel embarque les voyageurs de sa couleur. Les autres s’installent sur les cinq places du banc.','Un bus complet part. Les voyageurs du banc rejoignent automatiquement le prochain bus compatible. Les billets indiquent les départs à venir.','Un choix qui dépasserait la capacité du banc est refusé. Annulez ou demandez un indice pour retrouver une suite gagnante.']},
  carrousel:{name:'Carrousel',rules:carrouselRules,eyebrow:'UN PETIT TOUR, UNE COULEUR DE MOINS',title:'Et ça<br> <em>tourne encore.</em>',copy:'De petits tireurs en promenade.<br>Des images à faire disparaître.',steps:[['Lancez un petit tireur.','Choisissez le premier d’une file. Il fait un tour du tapis et vise les pixels accessibles de sa couleur.'],['Préparez le prochain tour.','S’il lui reste des billes, il attend sur l’une des cinq places. Relancez-le après avoir dégagé sa couleur.']],note:'Envoyez un petit tireur · Relancez ceux qui attendent',unit:'pixels à dégager',reserve:'Prêts pour un tour ?',reserveCopy:'Chaque nombre indique les billes restantes. Un tour peut en utiliser une partie seulement.',finish:'Un dernier tour de piste.',delay:680,rulesText:['La première créature de chaque file peut partir sur le tapis. Son nombre indique ses billes : une bille retire un pixel de sa couleur.','Seuls les pixels atteignables depuis l’extérieur, à travers les espaces déjà vides, peuvent être touchés. Un tour a un nombre limité de tirs.','Un tireur vide quitte la piste. Avec des billes restantes, il prend une des cinq places d’attente. Cliquez dessus pour le relancer.','Un tireur en attente qui ne peut toucher aucun pixel ne peut pas être relancé. Cinq tireurs en attente bloquent les nouvelles arrivées : annulez ou demandez un indice.']},
  broderie:{name:'Broderie',rules:broderieRules,eyebrow:'LES PETITS FILS FONT LES BELLES IMAGES',title:'Trois fils.<br> <em>Une image.</em>',copy:'Une bobine, une couleur.<br>Faites apparaître un petit tableau.',steps:[['Prenez un fil découvert.','Les bobines du dessus cachent celles du dessous. Choisissez parmi celles qui sont libres.'],['Réunissez trois couleurs.','Trois bobines identiques brodent une partie de l’image et libèrent leurs places.']],note:'Choisissez une bobine découverte · Réunissez trois couleurs',unit:'bobines à assembler',reserve:'Les sept petites places.',reserveCopy:'Réunissez trois bobines de la même couleur pour broder un morceau du tableau.',finish:'Un petit tableau terminé.',delay:430,rulesText:['Cliquez une bobine dont aucune autre ne couvre le dessus, dans le tas ou dans la liste. Elle rejoint les sept places de travail.','Trois bobines de la même couleur sont utilisées ensemble. Elles brodent une partie de l’image puis libèrent leurs trois places.','Les emplacements en pointillés attendent vos fils. Chaque tableau comporte plusieurs parties colorées : toutes doivent être brodées.','Gardez assez de places pour compléter vos groupes. Une sélection qui dépasserait les sept places est refusée. Annulation, indices et reprise sont toujours disponibles.']},
};
const config=configs[mode],rules=config.rules,key=`cubecubecube-${mode}-v1`;let saved;
try{saved=decodePocket(rules,JSON.parse(localStorage.getItem(key)));}catch{/* Storage is optional. */}
let game=saved?.game||new PocketGame(rules),completed=saved?.completed||new Set(),sound=saved?.sound||false;
let selected=null,hint=null,scene,chapter=Math.floor(game.level.index/12),busyUntil=0,audio,finishTimer,hintTimer;
$('#app').innerHTML=`<header class="pocket-header"><a class="pocket-brand" href="${base}"><span>↗</span><strong>cube cube cube<small>A small escape.</small></strong></a><nav class="pocket-nav" aria-label="Navigation"><a href="${base}">Les jeux</a><button id="pocket-collection">La collection <span id="pocket-total"></span></button><button id="pocket-help" aria-label="Voir les règles">?</button></nav></header>
<main class="pocket-layout"><section class="pocket-intro"><span class="eyebrow">${config.eyebrow}</span><h1>${config.title}</h1><p>${config.copy}</p>${config.steps.map(([title,text],i)=>`<div class="pocket-tip"><span>0${i+1}</span><div><strong>${title}</strong><p>${text}</p></div></div>`).join('')}<span class="slow-note">✳ Pas de chrono. Prenez votre temps.</span></section><section class="pocket-play" aria-label="Puzzle ${config.name}"><div class="pocket-heading"><div><span id="pocket-number" class="eyebrow"></span><h2 id="pocket-title"></h2><span id="pocket-difficulty" class="difficulty"></span></div><div class="pocket-count"><strong id="pocket-remaining"></strong><small>${config.unit}</small></div></div><div class="pocket-progress"><span id="pocket-progress"></span></div><div id="pocket-stage" class="pocket-stage"><span class="pocket-stage-note">${config.name.toUpperCase()} · UNE PETITE PAUSE</span><div id="pocket-finish" class="pocket-finish" hidden><span class="eyebrow">UNE BELLE CHOSE DE PLUS</span><h2>${config.finish}</h2><p id="pocket-finish-copy"></p><button id="pocket-next">Le prochain puzzle →</button><button id="pocket-replay" class="secondary">Rejouer ce puzzle</button></div></div><div class="pocket-toolbar"><button id="pocket-undo">↶ Annuler <kbd>U</kbd></button><button id="pocket-hint">✧ Un petit indice <kbd>H</kbd></button><button id="pocket-restart">↻ Recommencer <kbd>R</kbd></button><button id="pocket-sound" aria-label="Activer le son" aria-pressed="false">♫</button></div><p id="pocket-status" role="status" aria-live="polite">${config.note}</p></section><aside class="pocket-aside" aria-label="Réserve et commandes"><span class="eyebrow">À VOUS DE CHOISIR</span><h2>${config.reserve}</h2><p>${config.reserveCopy}</p><div id="pocket-controls"></div></aside></main>
<footer class="pocket-footer"><span>Les petites choses font les belles pauses.</span><span>48 puzzles · Sans publicité · Sauvegardé ici ✳</span></footer><dialog id="pocket-collection-dialog" class="pocket-dialog"><div class="pocket-dialog-head"><h2>La collection.</h2><button data-close aria-label="Fermer la collection">×</button></div><p>48 petits puzzles. Quatre chapitres, de plus en plus malins. Tous sont accessibles.</p><div id="pocket-chapters" class="pocket-chapters">${CHAPTERS.map((title,i)=>`<button data-chapter="${i}">${title}</button>`).join('')}</div><div id="pocket-levels" class="pocket-levels"></div></dialog><dialog id="pocket-help-dialog" class="pocket-dialog"><div class="pocket-dialog-head"><h2>${config.name}.</h2><button data-close aria-label="Fermer les règles">×</button></div><ol>${config.rulesText.map(text=>`<li>${text}</li>`).join('')}</ol><p>H : indice · Entrée : jouer l’indice · U : annuler · R : recommencer.${mode==='passages'?' Flèches : déplacer le bloc choisi.':mode==='carrousel'?' 1–4 : lancer une file.':''}</p><p>Votre progression reste sur cet appareil. Les sons sont facultatifs.</p><button data-close class="tool-button hint-button">C’est parti →</button></dialog>`;
function persist(){try{localStorage.setItem(key,JSON.stringify(encodePocket(game,completed,sound)));}catch{/* Play remains available without storage. */}}
function status(text){$('#pocket-status').textContent=text;}
function remaining(){return config.remaining?config.remaining(game):mode==='passages'?game.state.blocks.length:mode==='broderie'?game.level.spools.length-game.state.removed.length:(mode==='voyage'?game.level.passengers.length:game.level.cells.length)-game.state.removed.length;}
function total(){return config.total?config.total(game):mode==='passages'?game.level.blocks.length:mode==='broderie'?game.level.spools.length:mode==='voyage'?game.level.passengers.length:game.level.cells.length;}
function enabled(){return performance.now()>=busyUntil&&!scene?.running&&!$('dialog[open]')&&!game.won;}
const dot=color=>`<span class="color-dot" style="--color:${COLORS[color].hex};${color===7?'color:#fffaf0':''}">${COLORS[color].mark}</span>`;
const chip=color=>`<span style="--color:${COLORS[color].hex};${color===7?'color:#fffaf0':''}" title="${COLORS[color].name}">${COLORS[color].mark}</span>`;
function pigSvg(color){return `<svg viewBox="0 0 50 40" aria-hidden="true"><ellipse cx="25" cy="23" rx="19" ry="14" fill="${COLORS[color].hex}"/><path d="m12 14-1-10 10 8m11 1 8-9-1 11" fill="${COLORS[color].hex}"/><ellipse cx="32" cy="25" rx="10" ry="7" fill="#fae6d0"/><circle cx="29" cy="24" r="1.4" fill="#6c725b"/><circle cx="35" cy="24" r="1.4" fill="#6c725b"/><circle cx="22" cy="15" r="3" fill="#fffaf0"/><circle cx="23" cy="15" r="1.5" fill="#40574c"/></svg>`;}
function spoolSvg(color){return `<svg viewBox="0 0 40 42" aria-hidden="true"><rect x="7" y="6" width="26" height="30" rx="6" fill="${COLORS[color].hex}"/><path d="M8 14q12 5 24 0m-24 6q12 5 24 0m-24 6q12 5 24 0" stroke="#ffffff80" fill="none"/><path d="M4 5H36M4 37H36" stroke="#d0b891" stroke-width="6" stroke-linecap="round"/><text x="20" y="26" text-anchor="middle" font-size="12" fill="${color===7?'#fffaf0':'#365849'}">${COLORS[color].mark}</text></svg>`;}
function controls(){
  if(config.controls)return config.controls(game,selected,hint);
  if(mode==='passages')return `<div class="creature-list">${game.level.blocks.map(b=>`<button data-select="${b.id}" class="creature-button" style="--color:${COLORS[b.color].hex}" aria-pressed="${selected===b.id}" ${!game.state.blocks.some(n=>n.id===b.id)?'disabled':''}><span>${game.state.blocks.some(n=>n.id===b.id)?COLORS[b.color].mark:'✓'}</span>${COLORS[b.color].name}<small>${b.w} × ${b.h}</small></button>`).join('')}</div><p class="pocket-reserve-label">${selected===null?'Choisissez un bloc dans la cour.':`${COLORS[game.level.blocks[selected].color].name} · Bloc sélectionné`}</p><div class="pocket-pad" aria-label="Déplacer le bloc"><button data-direction="0,-1" aria-label="Monter">↑</button><button data-direction="-1,0" aria-label="Aller à gauche">←</button><button data-direction="0,1" aria-label="Descendre">↓</button><button data-direction="1,0" aria-label="Aller à droite">→</button></div>`;
  if(mode==='voyage'){
    const bus=game.level.buses[game.state.bus],ready=accessiblePassengers(game.level,game.state);
    return `<div class="suite-bus" style="--color:${bus?COLORS[bus.color].hex:'#cad5bd'}"><span>LE BUS À QUAI</span><strong>${bus?`${COLORS[bus.color].mark} ${game.state.boarded} / ${bus.count}`:'✓'}</strong><small>${bus?COLORS[bus.color].name:'Tous les bus sont partis'}</small><i></i><i></i></div><span class="pocket-reserve-label">LE BANC · ${game.state.buffer.length} / 5</span><div class="pocket-buffer">${Array.from({length:5},(_,i)=>game.state.buffer[i]!==undefined?chip(game.level.passengers[game.state.buffer[i]].color):'<span>·</span>').join('')}</div><span class="pocket-reserve-label">LES PROCHAINS BILLETS</span><div class="suite-tickets">${game.level.buses.slice(game.state.bus+1).map(b=>`<span style="--color:${COLORS[b.color].hex}">${COLORS[b.color].mark} ${b.count}</span>`).join('')}</div><span class="pocket-reserve-label">VOYAGEURS ACCESSIBLES</span><div class="suite-options">${ready.map(id=>`<button data-piece="${id}" class="${hint?.action===id?'hinted':''}" aria-label="Voyageur ${id+1}, ${COLORS[game.level.passengers[id].color].name}">${dot(game.level.passengers[id].color)}<small>${id+1}</small></button>`).join('')}</div>`;
  }
  if(mode==='carrousel')return `<span class="pocket-reserve-label">LES CINQ PLACES · RELANCEZ UN TIREUR</span><div class="suite-waiting">${game.state.waiting.map((pig,slot)=>`<button data-waiting="${slot}" ${!pig?'disabled':''} class="${hint?.action?.type==='waiting'&&hint.action.slot===slot?'hinted':''}" aria-label="${pig?`Relancer ${COLORS[pig.color].name}, ${pig.ammo} billes`:`Place ${slot+1} libre`}">${pig?`${pigSvg(pig.color)}<strong>${pig.ammo}</strong>`:'<span>+</span>'}</button>`).join('')}</div><span class="pocket-reserve-label">LE PREMIER TIREUR DE CHAQUE FILE</span><div class="bobbin-queues">${game.level.queues.map((queue,q)=>`<div class="bobbin-queue"><span class="eyebrow">0${q+1}</span>${queue.slice(game.state.queues[q],game.state.queues[q]+3).map((pig,i)=>`<button class="bobbin-button ${i?'buried':'ready'} ${!i&&hint?.action?.type==='queue'&&hint.action.q===q?'hinted':''}" data-queue="${q}" ${i||!game.state.waiting.includes(null)?'disabled':''} aria-label="${COLORS[pig.color].name}, ${pig.ammo} billes, file ${q+1}">${pigSvg(pig.color)}<strong>${pig.ammo}</strong><small>${COLORS[pig.color].mark} ${i?'En réserve':'Un tour ↑'}</small></button>`).join('')||'<small>✓</small>'}${queue.length-game.state.queues[q]>3?`<small>+${queue.length-game.state.queues[q]-3}</small>`:''}</div>`).join('')}</div>`;
  const ready=accessibleSpools(game.level,game.state),colors=[...new Set(game.level.cells)];
  return `<span class="pocket-reserve-label">EN COURS · ${game.state.buffer.length} / 7</span><div class="pocket-buffer">${Array.from({length:7},(_,i)=>game.state.buffer[i]!==undefined?chip(game.state.buffer[i]):'<span>·</span>').join('')}</div><span class="pocket-reserve-label">LE TABLEAU · ${game.state.stitched.length} / ${game.level.patches.length} PARTIES</span><div class="suite-patches">${colors.map(color=>`<span>${dot(color)}<small>${game.level.patches.filter(p=>p.color===color&&!game.state.stitched.includes(p.id)).length} à broder</small></span>`).join('')}</div><span class="pocket-reserve-label">BOBINES DÉCOUVERTES</span><div class="suite-options spools">${ready.map(id=>`<button data-piece="${id}" class="${hint?.action===id?'hinted':''}" aria-label="Bobine ${id+1}, ${COLORS[game.level.spools[id].color].name}">${spoolSvg(game.level.spools[id].color)}<small>${id+1}</small></button>`).join('')}</div>`;
}
function update(previous=null,action=null){
  $('#pocket-number').textContent=`PUZZLE ${String(game.level.index+1).padStart(2,'0')} / 48 · ${config.name.toUpperCase()}`;$('#pocket-title').textContent=game.level.title;$('#pocket-difficulty').textContent=CHAPTERS[game.level.tier];$('#pocket-remaining').textContent=remaining();$('#pocket-progress').style.width=`${100*(1-remaining()/total())}%`;
  $('#pocket-undo').disabled=!game.history.length;$('#pocket-hint').disabled=game.won;$('#pocket-sound').setAttribute('aria-pressed',String(sound));$('#pocket-sound').setAttribute('aria-label',sound?'Couper le son':'Activer le son');$('#pocket-controls').innerHTML=controls();scene?.update(game.level,game.state,hint,selected,previous,action);
  if((mode==='gouttes'||mode==='dunes')&&(scene?.running||game.won))$('#pocket-controls').querySelectorAll('button').forEach(b=>b.disabled=true);
  if(game.won)completed.add(game.level.index);$('#pocket-total').textContent=`${completed.size} / 48`;$('#pocket-finish').hidden=!game.won||performance.now()<busyUntil||Boolean(scene?.running);$('#pocket-finish-copy').textContent=completed.size===LEVEL_COUNT?'Les 48 puzzles sont dans votre collection. Bravo !':`${completed.size} puzzle${completed.size>1?'s':''} dans votre collection. Prenez le temps de savourer.`;$('#pocket-next').textContent=game.level.index===47?'Retrouver la collection →':'Le prochain puzzle →';persist();
}
function tone(){if(!sound)return;try{audio||=new(window.AudioContext||window.webkitAudioContext)();audio.resume();const osc=audio.createOscillator(),gain=audio.createGain(),now=audio.currentTime;osc.frequency.setValueAtTime(game.won?660:300+remaining()%7*50,now);gain.gain.setValueAtTime(.035,now);gain.gain.exponentialRampToValueAtTime(.001,now+.16);osc.connect(gain).connect(audio.destination);osc.start(now);osc.stop(now+.17);}catch{/* Audio is optional. */}}
function play(action){
  if(!enabled())return false;const previous=clone(game.state);
  if(!game.play(action)){status(config.invalid||(mode==='passages'?'Ce passage est occupé ou cette porte ne correspond pas au bloc.':mode==='voyage'?'Ce voyageur est bloqué, ou le banc est plein.':mode==='carrousel'?'Aucun pixel de cette couleur n’est accessible, ou les cinq places sont occupées.':'Cette bobine est couverte, ou les sept places sont pleines.'));return false;}
  hint=null;if(mode==='passages'&&!game.state.blocks.some(b=>b.id===selected))selected=null;
  if(mode==='potions')selected=null;
  if(mode==='alveoles'&&!game.level.queues[selected]?.[game.state.queues[selected]])selected=null;
  if(mode==='dunes'&&!game.level.queues[selected]?.[game.state.queues[selected]])selected=null;
  if(bountyConfigs[mode])selected=null;
  busyUntil=performance.now()+(matchMedia('(prefers-reduced-motion: reduce)').matches?0:config.delay);update(previous,action);tone();status(config.afterStatus?.(game)||(mode==='gouttes'&&action.type==='run'&&scene.running?'L’eau arrive… Regardez vos petites rampes travailler.':game.won?'Une belle chose de plus dans votre collection.':config.note));
  clearTimeout(finishTimer);if(game.won)finishTimer=setTimeout(()=>update(),Math.max(0,busyUntil-performance.now())+10);return true;
}
function cancelPending(){clearTimeout(finishTimer);clearTimeout(hintTimer);busyUntil=0;hint=null;selected=null;}
function undo(){cancelPending();if(game.undo()){update();status('Votre dernier choix est annulé.');}}
function restart(){cancelPending();game.restart();update();status('Le même puzzle, une nouvelle tentative.');}
function load(index){cancelPending();game=new PocketGame(rules,index);update();status(config.note);}
function select(id){if(!enabled())return;if((mode==='alveoles'||mode==='dunes')&&!game.level.queues[id]?.[game.state.queues[id]])return;if(mode==='mosaique'&&!activePieces(game.level,game.state).some(p=>p.id===id))return;if(mode==='noeuds'&&game.level.pins[id]?.fixed){status('Cette attache est vissée. Déplacez les autres bouts.');return;}selected=id;hint=null;update();status(mode==='mosaique'?'La pièce est choisie. Faites-la glisser ou cliquez sa case de départ.':mode==='dunes'?'Le bloc est choisi. Cliquez dans le bac ou choisissez une colonne.':mode==='noeuds'?'L’attache est choisie. Faites-la glisser ou cliquez un plot vide.':mode==='alveoles'?'La pile est choisie. Posez-la dans une alvéole vide.':mode==='liaisons'?'Partez d’un point de cette couleur, puis choisissez les cases voisines.':'Le bloc est choisi. Faites-le glisser ou utilisez les flèches.');}
function chainCell(id){if(!enabled()||game.state.field[id]===null)return;hint=null;const path=Array.isArray(selected)?selected:[],back=path.indexOf(id);if(back>=0)selected=path.slice(0,back+1);else if(!path.length||game.state.field[id]===game.state.field[path[0]]&&chainNeighbors(game.level,path.at(-1),id))selected=[...path,id];else{status('Choisissez une bille voisine de même couleur.');return;}update();status(`${selected.length} bille${selected.length>1?'s':''} choisie${selected.length>1?'s':''}. Validez la chaîne à partir de trois.`);}
function number(id){if(!enabled()||game.state.field[id]===null)return;if(selected===id){selected=null;hint=null;update();}else if(selected===null){selected=id;hint=null;update();status('Le premier nombre est choisi. Cherchez sa paire libre.');}else play({a:selected,b:id});}
function mosaic(id){if(selected===null){status('Choisissez d’abord une pièce.');return;}play({id:selected,x:id%game.level.size,y:Math.floor(id/game.level.size)});}
function sand(x){if(selected===null){status('Choisissez d’abord un bloc dans une des trois files.');return;}play({q:selected,x});}
function holeDirection(dx,dy){play({type:'path',path:[[Math.max(50,Math.min(590,game.state.hole[0]+dx*22)),Math.max(60,Math.min(540,game.state.hole[1]+dy*22))]]});}
function peg(id){if(selected===null){status('Choisissez d’abord une attache mobile.');return;}play({pin:selected,peg:id});}
function waterProgress(caught){if(mode!=='gouttes')return;$('#pocket-remaining').textContent=Math.max(0,game.level.goal-caught);$('#pocket-progress').style.width=`${Math.min(100,caught/game.level.goal*100)}%`;const counter=$('.physics-water-result strong');if(counter)counter.textContent=`${caught} / ${game.level.goal}`;}
function settled(){if(mode!=='gouttes'&&mode!=='dunes')return;update();status(mode==='dunes'?(game.won?'Une dernière dune, une belle chose de plus.':config.note):game.won?'Le verre est heureux. Une belle chose de plus dans votre collection.':'Le verre attend encore quelques gouttes. Annulez, ajustez vos traits et réessayez.');}
function waterPoint(){if(!enabled())return;const x=Number($('#water-x').value),y=Number($('#water-y').value);if(!Number.isFinite(x)||!Number.isFinite(y)||x<35||x>605||y<75||y>550){status('Choisissez un point dans le jardin : X de 35 à 605, Y de 75 à 550.');return;}scene.assisted||=[];if(scene.assisted.length>=160)return;scene.assisted.push([x,y]);$('#water-point-status').textContent=`${scene.assisted.length} point${scene.assisted.length>1?'s':''} · ${scene.assisted.map(p=>p.join(', ')).join(' → ')}`;}
function bottle(id){if(!enabled())return;if(selected===id){selected=null;update();status(config.note);}else if(selected===null){if(!game.state.bottles[id].length){status('Choisissez d’abord une fiole contenant du liquide.');return;}selected=id;hint=null;update();status(`Fiole ${id+1} choisie. Cliquez sa destination.`);}else play({from:selected,to:id});}
function hex(cell){if(selected===null){status('Choisissez d’abord une pile dans une des trois files.');return;}play({q:selected,cell});if(!game.level.queues[selected]?.[game.state.queues[selected]]){selected=null;update();}}
function liaisonCell(cell){
  if(!enabled())return;const color=game.level.pairs.findIndex(p=>p.includes(cell));
  if(color>=0){const path=game.state.paths[color];if(selected===color&&path.length&&path[0]!==cell&&neighbors(game.level.size,path.at(-1),cell)){play({color,path:[...path,cell]});return;}selected=color;if(path.at(-1)===cell&&path.length>1)return;hint=null;play({color,path:[cell]});update();return;}
  if(selected===null){status('Choisissez un point ou une couleur pour commencer.');return;}
  const path=game.state.paths[selected].length?game.state.paths[selected]:[game.level.pairs[selected][0]],back=path.indexOf(cell);
  if(back>=0)play({color:selected,path:path.slice(0,back+1)});else if(neighbors(game.level.size,path.at(-1),cell))play({color:selected,path:[...path,cell]});else status('Choisissez une case voisine du bout de votre chemin.');
}
function direction(dx,dy){if(selected===null){status('Choisissez d’abord un bloc.');return;}play({id:selected,dx,dy});}
function showHint(){if(!enabled())return;status('Je cherche une suite qui mène jusqu’au bout…');hintTimer=setTimeout(()=>{hint=game.hint();if(mode==='passages'&&hint?.action)selected=hint.action.id;if((mode==='alveoles'||mode==='dunes')&&hint?.action)selected=hint.action.q;if(mode==='mosaique'&&hint?.action)selected=hint.action.id;if(mode==='recolte'&&hint?.action)selected=hint.action.path;if(mode==='potions'&&hint?.action)selected=hint.action.from;if(mode==='liaisons'&&hint?.action)selected=hint.action.color;if(mode==='noeuds'&&hint?.action)selected=hint.action.pin;update();status(hint?.undo?'La recherche ne trouve pas de suite complète. Annulez un détour avec Entrée.':mode==='gouttes'&&hint?.action?.type==='clear'?'Effacez ces rampes pour dessiner une route vérifiée. Entrée exécute l’indice.':mode==='gouttes'&&hint?.action?.type==='run'?'Les rampes sont prêtes. Laissez couler, ou appuyez sur Entrée.':mode==='liaisons'&&hint?.action?.path.length===0?'Effacez ce détour pour ouvrir une route complète. Entrée exécute l’indice.':hint?'Le prochain choix est indiqué. Cliquez dessus ou appuyez sur Entrée.':'Aucun indice trouvé pour ce plateau.');$('#pocket-canvas').focus({preventScroll:true});},20);}
function collection(){
  $('#pocket-chapters').querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.chapter)===chapter)));
  $('#pocket-levels').innerHTML=Array.from({length:12},(_,i)=>{const index=chapter*12+i,level=rules.create(index);return `<button data-level="${index}" aria-current="${index===game.level.index}" aria-label="Puzzle ${index+1}, ${level.title}${completed.has(index)?', terminé':''}"><strong>${String(index+1).padStart(2,'0')} ${completed.has(index)?'✓':''}</strong><small>${level.title}</small></button>`;}).join('');
}
$('#pocket-controls').addEventListener('click',event=>{const b=event.target.closest('button');if(!b||b.disabled)return;if(b.dataset.select!==undefined)select(Number(b.dataset.select));if(b.dataset.piece!==undefined)play(Number(b.dataset.piece));if(b.dataset.queue!==undefined)play({type:'queue',q:Number(b.dataset.queue)});if(b.dataset.waiting!==undefined)play({type:'waiting',slot:Number(b.dataset.waiting)});if(b.dataset.direction)direction(...b.dataset.direction.split(',').map(Number));if(b.dataset.bottle!==undefined)bottle(Number(b.dataset.bottle));if(b.dataset.hex!==undefined)hex(Number(b.dataset.hex));if(b.dataset.cell!==undefined)liaisonCell(Number(b.dataset.cell));if(b.hasAttribute('data-clear')&&selected!==null)play({color:selected,path:[]});});
$('#pocket-undo').addEventListener('click',undo);$('#pocket-restart').addEventListener('click',restart);$('#pocket-replay').addEventListener('click',restart);$('#pocket-hint').addEventListener('click',showHint);$('#pocket-sound').addEventListener('click',()=>{sound=!sound;update();tone();});
$('#pocket-next').addEventListener('click',()=>{if(game.level.index<47)load(game.level.index+1);else{chapter=0;collection();$('#pocket-collection-dialog').showModal();}});
$('#pocket-collection').addEventListener('click',()=>{chapter=Math.floor(game.level.index/12);collection();$('#pocket-collection-dialog').showModal();});$('#pocket-help').addEventListener('click',()=>$('#pocket-help-dialog').showModal());document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));
$('#pocket-chapters').addEventListener('click',event=>{const b=event.target.closest('[data-chapter]');if(b){chapter=Number(b.dataset.chapter);collection();}});$('#pocket-levels').addEventListener('click',event=>{const b=event.target.closest('[data-level]');if(b){$('#pocket-collection-dialog').close();load(Number(b.dataset.level));}});
document.addEventListener('keydown',event=>{if($('dialog[open]')||['INPUT','TEXTAREA'].includes(event.target.tagName)||event.ctrlKey||event.metaKey||event.altKey)return;const key=event.key.toLowerCase();if(key==='h'){event.preventDefault();showHint();}if(key==='u'){event.preventDefault();undo();}if(key==='r'){event.preventDefault();restart();}if(key==='enter'&&hint){event.preventDefault();if(hint.undo)undo();else play(hint.action);}if(mode==='carrousel'&&/^[1-4]$/.test(key)){event.preventDefault();play({type:'queue',q:Number(key)-1});}if(mode==='passages'&&['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(event.key)){event.preventDefault();direction(...({ArrowUp:[0,-1],ArrowDown:[0,1],ArrowLeft:[-1,0],ArrowRight:[1,0]})[event.key]);}});
document.addEventListener('keydown',event=>{if(!gardenConfigs[mode]||$('dialog[open]')||['INPUT','TEXTAREA'].includes(event.target.tagName)||event.ctrlKey||event.metaKey||event.altKey)return;if(mode==='alveoles'&&/^[1-3]$/.test(event.key)){event.preventDefault();select(Number(event.key)-1);}if(mode==='potions'&&/^[1-8]$/.test(event.key)&&Number(event.key)<=game.state.bottles.length){event.preventDefault();bottle(Number(event.key)-1);}if(mode==='liaisons'&&selected!==null&&['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(event.key)){event.preventDefault();const size=game.level.size,last=game.state.paths[selected].at(-1)??game.level.pairs[selected][0],delta=({ArrowUp:-size,ArrowDown:size,ArrowLeft:-1,ArrowRight:1})[event.key],cell=last+delta;if(cell>=0&&cell<size**2&&neighbors(size,last,cell))liaisonCell(cell);}});
$('#pocket-controls').addEventListener('click',event=>{const b=event.target.closest('button');if(!b||b.disabled)return;if(b.dataset.peg!==undefined)peg(Number(b.dataset.peg));if(b.hasAttribute('data-water-run'))play({type:'run'});if(b.hasAttribute('data-water-clear'))play({type:'clear'});if(b.hasAttribute('data-water-point'))waterPoint();if(b.hasAttribute('data-water-place')){if(scene.assisted?.length>=2)play({type:'draw',path:scene.assisted});else status('Ajoutez au moins deux points avant de poser le trait.');}if(b.hasAttribute('data-water-cancel')){scene.assisted=[];$('#water-point-status').textContent='Le tracé est annulé.';}});
document.addEventListener('keydown',event=>{if(mode!=='gouttes'||$('dialog[open]')||['INPUT','TEXTAREA'].includes(event.target.tagName)||event.ctrlKey||event.metaKey||event.altKey)return;if(event.key.toLowerCase()==='e'){event.preventDefault();play({type:'run'});}});
$('#pocket-controls').addEventListener('click',event=>{const b=event.target.closest('button');if(!b||b.disabled)return;if(b.dataset.gate!==undefined)play(Number(b.dataset.gate));if(b.dataset.sandX!==undefined)sand(Number(b.dataset.sandX));if(b.dataset.food!==undefined)play({type:'visit',id:Number(b.dataset.food)});if(b.dataset.holeDir)holeDirection(...b.dataset.holeDir.split(',').map(Number));});
document.addEventListener('keydown',event=>{if(!harvestConfigs[mode]||$('dialog[open]')||['INPUT','TEXTAREA'].includes(event.target.tagName)||event.ctrlKey||event.metaKey||event.altKey)return;
  if(mode==='ecluses'&&/^[1-9]$/.test(event.key)){event.preventDefault();play(Number(event.key)-1);}
  if(mode==='dunes'){
    if(/^[1-3]$/.test(event.key)){event.preventDefault();select(Number(event.key)-1);}
    const piece=selected===null?null:game.level.queues[selected]?.[game.state.queues[selected]];
    if(piece&&['ArrowLeft','ArrowRight',' '].includes(event.key)){event.preventDefault();const max=game.level.width-sandWidth(piece),x=Math.max(0,Math.min(max,scene.cursor??hint?.action?.x??Math.floor(max/2)));if(event.key===' ')sand(x);else{scene.cursor=Math.max(0,Math.min(max,x+(event.key==='ArrowRight'?1:-1)));hint=null;update();}}
  }
  if(mode==='fringale'&&['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(event.key)){event.preventDefault();holeDirection(...({ArrowUp:[0,-1],ArrowDown:[0,1],ArrowLeft:[-1,0],ArrowRight:[1,0]})[event.key]);}
});
$('#pocket-controls').addEventListener('click',event=>{const b=event.target.closest('button');if(!b||b.disabled)return;if(b.dataset.chain!==undefined)chainCell(Number(b.dataset.chain));if(b.hasAttribute('data-chain-commit')&&Array.isArray(selected))play({path:selected});if(b.hasAttribute('data-chain-clear')){selected=null;hint=null;update();status('Le tracé est effacé.');}if(b.dataset.number!==undefined)number(Number(b.dataset.number));if(b.dataset.mosaic!==undefined)mosaic(Number(b.dataset.mosaic));});
document.addEventListener('keydown',event=>{if(!bountyConfigs[mode]||$('dialog[open]')||['INPUT','TEXTAREA'].includes(event.target.tagName)||event.ctrlKey||event.metaKey||event.altKey)return;
  if(mode==='recolte'&&event.key==='Enter'&&Array.isArray(selected)&&!hint){event.preventDefault();play({path:selected});}
  if(mode==='recolte'&&event.key==='Escape'){selected=null;hint=null;scene.draft=null;update();}
  if(mode==='mosaique'){
    if(/^[1-3]$/.test(event.key)){event.preventDefault();const p=activePieces(game.level,game.state)[Number(event.key)-1];if(p)select(p.id);}
    const piece=game.level.pieces[selected];if(piece&&['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(event.key)){event.preventDefault();const cursor=scene.cursor??hint?.action??{x:0,y:0};if(event.key===' ')play({id:selected,...cursor});else{const [dx,dy]=({ArrowUp:[0,-1],ArrowDown:[0,1],ArrowLeft:[-1,0],ArrowRight:[1,0]})[event.key];scene.cursor={x:Math.max(0,Math.min(game.level.size-pieceWidth(piece),cursor.x+dx)),y:Math.max(0,Math.min(game.level.size-pieceHeight(piece),cursor.y+dy))};hint=null;update();}}
  }
});
scene=new (bountyConfigs[mode]?BountyCanvas:harvestConfigs[mode]?HarvestCanvas:physicsConfigs[mode]?PhysicsCanvas:gardenConfigs[mode]?GardenCanvas:SuiteCanvas)($('#pocket-stage'),mode,{enabled,play,select,direction,bottle,hex,peg,waterProgress,settled,sand,number,mosaic});update();
window.__pocketDebug={get game(){return game;},get scene(){return scene;},get hint(){return hint;},get selected(){return selected;},get ready(){return performance.now()>=busyUntil&&!scene?.running;}};
window.addEventListener('pagehide',()=>{persist();scene.dispose();});window.addEventListener('pageshow',event=>{if(event.persisted)location.reload();});
