import {valisesRules,luggageCells} from './valises-puzzle.js';
import {sanglesRules,beltLength} from './sangles-puzzle.js';
import {tracesRules} from './traces-puzzle.js';
import {COLORS} from './pocket-core.js';
import {travelIcon} from './travel-previews.js';
const luggageThumb=p=>{const cells=luggageCells(p),w=Math.max(...cells.map(q=>q[0]))+1,h=Math.max(...cells.map(q=>q[1]))+1,step=Math.min(48/w,48/h),x=(60-step*w)/2,y=(60-step*h)/2;return `<svg viewBox="0 0 60 60" aria-hidden="true">${cells.map(([a,b])=>`<rect x="${x+a*step}" y="${y+b*step}" width="${step}" height="${step}" rx="1" fill="${COLORS[p.color].hex}" stroke="#fff4dd99" stroke-width=".7"/>`).join('')}<g transform="translate(18 15)">${travelIcon(p.icon,'#f6ead0').replace('<svg ','<svg width="24" height="30" ')}</g></svg>`;};
export const travelConfigs={
  valises:{name:'Valises',rules:valisesRules,eyebrow:'UNE PLACE POUR CHAQUE SOUVENIR',title:'Tout rentre.<br> <em>On peut partir.</em>',copy:'Tournez les petites affaires.<br>Rangez-les dans la valise.',steps:[['Choisissez une affaire.','Faites-la glisser dans la valise. Tournez-la pour trouver la bonne place.'],['Gardez les bons espaces.','Les affaires restent entières. Rien ne se superpose, et les petites poches restent libres.']],note:'Choisissez une affaire · T pour tourner · Glissez-la dans la valise',unit:'affaires à ranger',reserve:'Les affaires du voyage.',reserveCopy:'Un chapeau, un appareil, quelques souvenirs. Chaque silhouette a sa place.',finish:'Tout est dans la valise.',delay:250,invalid:'Cette affaire dépasse, rencontre une poche ou touche un voisin.',total:g=>g.level.pieces.length,remaining:g=>g.state.placed.filter(p=>!p).length,
    rulesText:['Cliquez une affaire dans la réserve ou sur le plateau. Faites-la glisser dans la valise, ou choisissez sa case de départ avec les boutons.','T ou le bouton Tourner fait un quart de tour. Les flèches déplacent l’aperçu ; Espace le pose. Aucune affaire ne tombe automatiquement.','Les silhouettes doivent rester dans la valise, sans se superposer ni recouvrir les petites poches cousues. Vous pouvez déplacer une affaire déjà rangée ou la retirer.','Toutes les affaires et toutes les places de la valise doivent être occupées. Chaque geste s’annule. Les indices vérifient une suite complète, en retirant d’abord une affaire qui empêche le rangement.'],
    controls(g,selected,hint){return `<div class="travel-items">${g.level.order.map(id=>{const p=g.level.pieces[id];return `<button data-bag-pick="${id}" aria-pressed="${selected===id}" class="${hint?.action?.id===id?'hinted':''}" aria-label="Choisir l’affaire ${id+1}">${luggageThumb(p)}<strong>${id+1} ${g.state.placed[id]?'✓':''}</strong><small>${p.cells.length} ${p.cells.length>1?'places':'place'}</small></button>`;}).join('')}</div><div class="bounty-actions"><button data-bag-turn ${selected===null?'disabled':''}>Tourner <kbd>T</kbd></button><button data-bag-remove ${selected===null||!g.state.placed[selected]?'disabled':''}>Retirer de la valise</button></div><span class="pocket-reserve-label">CHOISISSEZ LA CASE DE DÉPART</span><div class="travel-cells" style="--cols:${g.level.cols}">${g.level.mask.map((v,id)=>`<button data-bag-cell="${id}" aria-label="Poser en ${String.fromCharCode(65+id%g.level.cols)}${Math.floor(id/g.level.cols)+1}" ${!v||selected===null?'disabled':''}>${v?`${String.fromCharCode(65+id%g.level.cols)}${Math.floor(id/g.level.cols)+1}`:'✦'}</button>`).join('')}</div>`;},
  },
  sangles:{name:'Sangles',rules:sanglesRules,eyebrow:'LES PETITS COLIS PRENNENT LA ROUTE',title:'Un petit tour.<br> <em>Tout reste à bord.</em>',copy:'Reliez les bonnes attaches.<br>Retenez les colis dans les virages.',steps:[['Préparez les sangles.','Reliez deux attaches, ou passez par un petit anneau. Chaque sangle a sa longueur.'],['Essayez le petit tour.','Un virage, un freinage. Les sangles retiennent réellement les colis, et une trop forte secousse peut les rompre.']],note:'Reliez les attaches · Puis essayez le petit trajet',unit:'colis à retenir',reserve:'Les sangles du voyage.',reserveCopy:'Choisissez une sangle, puis ses attaches. Un crochet après l’autre.',finish:'Tout est arrivé à bon port.',delay:0,invalid:'Choisissez au moins deux attaches différentes, sans dépasser la longueur ni traverser un colis ou une cloison.',total:g=>g.level.parcels.length,remaining:g=>g.level.parcels.length-(g.state.result?.caught??0),
    afterStatus:g=>g.state.result?(g.won?'Chaque petit colis est resté à bord.':`${g.state.result.caught} / ${g.level.parcels.length} colis retenus${g.state.result.broken.some(Boolean)?' · Une sangle a cédé':''}. Ajustez les attaches et réessayez.`):null,
    rulesText:['Choisissez une sangle, puis faites glisser d’une attache à une autre. Vous pouvez passer par deux anneaux supplémentaires. Les boutons permettent aussi de préparer le trajet de la sangle.','Une sangle a une longueur limitée. Elle ne peut traverser ni une cloison ni un colis au départ. Les petites attaches et anneaux restent fixes.','Lancer ou E fait voyager les colis pendant un virage et un freinage. Leur masse, leur élan, les cloisons, les autres colis et les sangles déterminent réellement leur mouvement. Une sangle trop chargée peut rompre.','Tous les colis doivent rester entièrement à bord à la fin du tour. Les essais ne coûtent aucune vie. Une fenêtre ou un onglet caché suspend le trajet ; annuler revient exactement avant l’essai.'],
    controls(g,selected,hint){const chosen=selected?.id??0,path=selected?.path??[],used=beltLength(g.level,path.length?path:g.state.routes[chosen]);return `<div class="travel-belts">${g.level.order.map(id=>`<button data-strap-pick="${id}" style="--color:${COLORS[g.level.belts[id].color].hex}" aria-pressed="${chosen===id}" aria-label="Choisir la sangle ${id+1}"><i></i><strong>Sangle ${id+1}</strong><small>${g.state.routes[id].length?'Attachée':'À préparer'}</small><span class="travel-strength" aria-label="Solidité ${Math.min(5,Math.ceil(g.level.belts[id].strength/100))} sur 5">${Array.from({length:5},(_,n)=>`<b class="${n<Math.min(5,Math.ceil(g.level.belts[id].strength/100))?'filled':''}"></b>`).join('')}</span></button>`).join('')}</div><p class="travel-route">${path.length?path.map(id=>id+1).join(' → '):'Choisissez la première attache.'}</p><div class="travel-length"><span>Longueur</span><i><b style="width:${Math.min(100,used/g.level.belts[chosen].maxLength*100)}%"></b></i><small>${Math.round(used/g.level.belts[chosen].maxLength*100)} %</small></div><div class="travel-posts">${g.level.posts.map(p=>`<button data-strap-post="${p.id}" class="${hint?.action?.path?.includes(p.id)?'hinted':''}" aria-label="Choisir l’attache ${p.id+1}">${p.peg?'◇':'○'} ${p.id+1}</button>`).join('')}</div><div class="bounty-actions"><button data-strap-place ${path.length<2?'disabled':''}>Attacher la sangle <kbd>↵</kbd></button><button data-strap-cancel>Effacer le tracé</button><button data-strap-remove ${!g.state.routes[chosen].length?'disabled':''}>Retirer la sangle</button><button data-cargo-run>Le petit tour <kbd>E</kbd></button></div><p class="bounty-note">Un petit tour. Autant d’essais que vous voulez.</p>`;},
  },
  traces:{name:'Tracés',rules:tracesRules,eyebrow:'UN CRAYON, TOUT UN PETIT CHEMIN',title:'Un seul trait.<br> <em>Tout se dessine.</em>',copy:'Suivez les chemins sans lever le crayon.<br>Retrouvez le dernier petit point.',steps:[['Commencez un trait.','Choisissez un point et suivez les chemins. Un point peut être traversé plusieurs fois.'],['Respectez chaque passage.','Les flèches ont un sens. Les chemins doubles attendent deux passages.']],note:'Glissez de point en point · Suivez chaque chemin le bon nombre de fois',unit:'passages à dessiner',reserve:'Le chemin du crayon.',reserveCopy:'Choisissez des points voisins, puis validez le trait. Vous pouvez aussi dessiner directement.',finish:'Un trait, un dessin terminé.',delay:140,invalid:'Ce chemin est déjà dessiné, ne rejoint pas votre crayon ou va contre une flèche.',total:g=>g.level.edges.reduce((n,e)=>n+e.count,0),remaining:g=>g.level.edges.reduce((n,e,id)=>n+e.count-g.state.used[id],0),
    rulesText:['Faites glisser d’un point à ses voisins pour dessiner un trait continu. Chaque point peut être revisité ; chaque chemin doit être parcouru exactement le nombre indiqué.','Un chemin simple se dessine une fois, un chemin double deux fois. Une petite flèche impose son sens. Les lignes ne se rejoignent qu’à leurs points.','Vous pouvez poursuivre un trait depuis son dernier point. Un glissement forme un geste entier à annuler ; annuler ne laisse aucun passage fantôme.','Les boutons permettent de tracer sans glisser. Entrée valide les points choisis ; Retour arrière retire le dernier point en préparation, Échap efface cette préparation. Les indices vérifient tous les passages restants avant de proposer le prochain.'],
    controls(g,selected,hint){const active=[...new Set(g.level.edges.flatMap(e=>[e.a,e.b]))].sort((a,b)=>a-b),path=Array.isArray(selected)?selected:[];return `<p class="travel-route">${path.length?path.map(id=>id+1).join(' → '):g.state.path.length?`Le crayon attend au point ${g.state.path.at(-1)+1}.`:'Choisissez le premier point.'}</p><div class="travel-points">${active.map(id=>`<button data-trace-node="${id}" aria-label="Choisir le point ${id+1}" class="${hint?.action?.path?.includes(id)?'hinted':''}">${id+1}</button>`).join('')}</div><div class="bounty-actions"><button data-trace-place ${path.length<2?'disabled':''}>Dessiner le trait <kbd>↵</kbd></button><button data-trace-back ${path.length<2?'disabled':''}>Un point en arrière</button><button data-trace-cancel>Effacer la préparation</button></div><p class="bounty-note">Un point peut revenir. Chaque chemin garde son compte.</p>`;},
  },
};
