import {COLORS} from './pocket-core.js';
import {bosquetsRules,bosquetStatus} from './bosquets-puzzle.js';
import {gravuresRules,engravingLines} from './gravures-puzzle.js';
import {veilleesRules} from './veillees-puzzle.js';

const coordinate=(id,n)=>`${String.fromCharCode(65+id%n)}${Math.floor(id/n)+1}`;
function tools(selected,bosquets){return `<div class="twilight-tools" aria-label="Outils du dessin">${[[1,bosquets?'Planter':'Colorer','1'],[2,'Marquer vide','2'],[0,'Effacer','0']].map(([value,name,key])=>`<button data-field-tool="${value}" aria-pressed="${(selected??1)===value}">${name} <kbd>${key}</kbd></button>`).join('')}</div>`;}
function cells(g,hint,mode){
  const n=g.level.size;return `<span class="pocket-reserve-label">LES CASES DU JARDIN</span><div class="twilight-cells" style="--cols:${n}">${Array.from({length:n*n},(_,id)=>{
    const value=mode==='veillees'?g.state.lit[id]?1:0:g.state.field[id],mark=mode==='veillees'?value?'☀':'☾':value===1?mode==='bosquets'?'✿':'■':value===2?'×':'·',state=mode==='veillees'?value?'allumée':'éteinte':value===1?mode==='bosquets'?'fleur':'colorée':value===2?'marquée vide':'non marquée',highlight=hint?.action?.cell===id||hint?.action?.cells?.includes(id);
    return `<button data-twilight-cell="${id}" aria-label="Case ${coordinate(id,n)}, ${state}" aria-pressed="${Boolean(value)}" class="${highlight?'hinted':''}" ${mode==='bosquets'?`style="--region:${COLORS[g.level.regions[id]].hex}"`:''}><span>${mark}</span><small>${coordinate(id,n)}</small></button>`;
  }).join('')}</div>`;
}
export const twilightConfigs={
  bosquets:{name:'Bosquets',rules:bosquetsRules,eyebrow:'UN PETIT COIN POUR CHAQUE FLEUR',title:'Une fleur.<br> <em>Un peu d’air.</em>',copy:'Partagez le petit jardin.<br>Gardez de la place entre les fleurs.',steps:[['Une place par allée.','Chaque ligne, chaque colonne et chaque zone de couleur accueille une seule fleur.'],['Gardez un peu d’air.','Deux fleurs ne doivent jamais se toucher, même en diagonale. Les croix gardent vos déductions.']],note:'Cliquez pour planter. 1 : fleur · 2 : croix · 0 : gomme. Flèches puis Espace pour choisir une case.',unit:'fleurs à placer',reserve:'Les petits bosquets.',reserveCopy:'Une fleur par couleur. Les croix vous aident à garder les places que vous avez éliminées.',finish:'Chaque bosquet a sa fleur.',delay:260,invalid:'Choisissez une case du jardin.',total:g=>g.level.size,remaining:g=>g.level.size-bosquetStatus(g.level,g.state).valid.length,
    rulesText:['Chaque ligne et chaque colonne accueille exactement une fleur. Chaque bosquet coloré accueille lui aussi exactement une fleur.','Les fleurs ne peuvent pas se toucher, même par un coin. Elles peuvent partager une grande diagonale si elles ne sont pas voisines.','Choisissez Planter, Marquer vide ou Effacer. Un clic supplémentaire efface la marque de l’outil actif. Un glissement marque plusieurs cases en une seule action.','Les choix qui se gênent sont signalés sans retirer de vie. Annulez librement ; un indice corrige un choix incompatible puis propose une fleur sur une solution vérifiée. Flèches : curseur, Espace ou Entrée : marquer, 1/2/0 : outil.'],
    controls(g,selected,hint){const status=bosquetStatus(g.level,g.state);return tools(selected,true)+`<p class="twilight-summary ${status.conflicts.length?'conflict':''}">${status.conflicts.length?'Des fleurs se gênent. Vous pouvez les déplacer ou les effacer.':`${status.valid.length} / ${g.level.size} fleurs espacées`}</p>`+cells(g,hint,'bosquets');},
  },
  gravures:{name:'Gravures',rules:gravuresRules,eyebrow:'LES PETITES LIGNES CACHENT UNE IMAGE',title:'Quelques nombres.<br> <em>Une petite image.</em>',copy:'Comptez les groupes de cases.<br>Faites apparaître une gravure.',steps:[['Comptez les groupes.','Un nombre indique un groupe de cases colorées. Deux groupes gardent au moins une case vide entre eux.'],['Gardez aussi les blancs.','Les colonnes et les lignes parlent du même dessin. Marquez les cases vides avec une petite croix.']],note:'Cliquez ou faites glisser pour colorer. 1 : couleur · 2 : croix · 0 : gomme. Flèches puis Espace pour marquer.',unit:'cases à déduire',reserve:'Les traits du dessin.',reserveCopy:'Une couleur, une croix. Chaque nombre décrit un groupe ; chaque blanc compte aussi.',finish:'Une petite gravure révélée.',delay:260,invalid:'Choisissez une case du papier.',total:g=>g.level.size**2,remaining:g=>g.state.field.filter(v=>v===0).length|| (engravingLines(g.level,g.state).some(lines=>lines.includes('conflict'))?1:0),
    rulesText:['Les nombres à gauche décrivent les groupes colorés de chaque ligne. Ceux du haut décrivent chaque colonne, dans le même ordre.','Deux groupes colorés doivent avoir au moins une case vide entre eux. Un indice 0 signifie que toute la ligne reste vide.','Coloriez les cases du dessin et marquez toutes les cases vides avec une croix. Les lignes impossibles sont signalées ; aucune vie ni pénalité ne vous empêche de corriger.','Utilisez les outils, les cases du panneau, ou les flèches puis Espace/Entrée. Faites glisser pour marquer plusieurs cases ; le geste entier se sauvegarde et s’annule ensemble. Un indice révèle les déductions d’une ligne à partir des contraintes, ou efface une erreur avant de continuer.'],
    controls(g,selected,hint){const lines=engravingLines(g.level,g.state),bad=lines.some(row=>row.includes('conflict'));return tools(selected,false)+`<p class="twilight-summary ${bad?'conflict':''}">${bad?'Une ligne ne correspond plus à ses indices.':`${lines.flat().filter(v=>v==='complete').length} / ${g.level.size*2} lignes complètes`}</p>`+`<details class="twilight-clues" open><summary>Lire les indices</summary><div>${[['Ligne',g.level.rows],['Colonne',g.level.columns]].map(([name,list])=>list.map((clues,id)=>`<span>${name} ${name==='Ligne'?id+1:String.fromCharCode(65+id)}<strong>${clues.join(' · ')}</strong></span>`).join('')).join('')}</div></details>`+cells(g,hint,'gravures');},
  },
  veillees:{name:'Veillées',rules:veilleesRules,eyebrow:'LES LANTERNES DU DERNIER SOIR',title:'Une lumière.<br> <em>Un peu de nuit.</em>',copy:'Une touche change les voisines.<br>Laissez le petit jardin s’endormir.',steps:[['Regardez les voisines.','Une lanterne change son état et celui de ses voisines. Une lumière allumée s’éteint, une lumière éteinte s’allume.'],['Trouvez le bon motif.','Les derniers jardins changent les diagonales et relient les bords. Le contour indique les lanternes touchées.']],note:'Choisissez une lanterne. Flèches : curseur · Espace ou Entrée : basculer.',unit:'lanternes à éteindre',reserve:'Les lumières voisines.',reserveCopy:'Chaque toucher change un petit groupe. Toucher deux fois la même lanterne annule son effet.',finish:'Le jardin s’est endormi.',delay:260,invalid:'Choisissez une lanterne du jardin.',total:g=>g.level.size**2,remaining:g=>g.state.lit.filter(Boolean).length,
    rulesText:['Touchez une lanterne pour inverser son état et celui de ses voisines. Le jardin est terminé lorsque toutes les lumières sont éteintes.','Le motif classique touche les voisines du haut, du bas, de gauche et de droite. Les jardins diagonaux touchent les quatre coins à la place.','Dans le dernier chapitre, les bords sont reliés : une voisine qui sort d’un côté revient de l’autre. Le motif et le contour du jardin montrent la règle du niveau.','Les contours en pointillés prévisualisent les lanternes qui changeront. Les indices calculent une suite complète depuis votre état actuel. Toucher deux fois la même case rend exactement le même jardin ; chaque toucher reste annulable et sauvegardé.'],
    controls(g,selected,hint){const l=g.level;return `<div class="twilight-pattern"><strong>${l.pattern==='diagonal'?'✕':'+'}</strong><span>${l.pattern==='diagonal'?'Les quatre diagonales':'Les quatre voisines'}<small>${l.wrap?'Les bords se rejoignent':'Le bord arrête les voisines'}</small></span></div>`+cells(g,hint,'veillees');},
  },
};
